### ISSUE TITLE
AdjustConfig compares objects not values for environment

### ISSUE THREAD

**Issue by bertybrace** [adjust/android_sdk#102]
Hello,

checkEnvironment() in AdjustConfig checks for a proper environment by comparing the String objects. We think comparing values should be in place.

Instead of:
environment == AdjustConfig.ENVIRONMENT_SANDBOX

use:
environment.equals(AdjustConfig.ENVIRONMENT_SANDBOX)

Please excuse me if I'm missing an important point.

**Comment by wellle** [comment]
@bertybrace: Good point, we will change it accordingly :+1:
