### ISSUE TITLE
Session control

### ISSUE THREAD

**Issue by paulocarvalhoaig** [adjust/android_sdk#103]
I'm currently implementing the new 4.0.2 SDK version, and sometimes when the Adjust tries to track the session it sends:

E/Adjust﹕ Failed to parse response (Content has been consumed)
V/Adjust﹕ Response: null

and after this happens none of the following events are tracked and the same response is given.

I've been searching for a possible cause, and testing scenarios, and I've read that in previous versions the session would some how persist for 30 minutes, and I also noticed that when I install the app the session and all the events that follow are tracked correctly, but if I uninstall and install again the session gives the error described above. Only if I wait some time the session again correctly tracked and so are the following events.

Is this the expected behavior? Do I have to wait another 30 minutes to test my trackers if I uninstall the app, or is there a workaround?

Thanks.

**Comment by nonelse** [comment]
Hi.

This error usually occurs if the HttpResponse entity is is used more than [once](http://stackoverflow.com/a/4732212). We only consume the entity once per [response](https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/Util.java#L164).

Just to be sure, did you get this behaviour by modifying the SDK or by manipulating the stack while debugging? Sometimes this is useful to see something in detail, but it could cause this behaviour.
 
Regarding the 30m rule that you are referring, we save a state file of the last activity and if it has passed 30m since the last one, it creates a new session package to send to the server. This behaviour has not change in the new versions.

Can you give more details how to reproduce this issue?

**Comment by paulocarvalhoaig** [comment]
No, I didn't change the SDK, I'm using it as it is.
The only difference I have, it's that due to project structure restrictions I don't initialize the Adjust on the onCreate method of my Applicaton Class, but in a specific class for tracking initialization. But as far as I could tell the problem is not from there, because it's initialized and receive a success response from the Adjust SDK when makes attribution:

V/Adjust﹕ Response: {"attribution":{"tracker_token":"XXXXX","tracker_name":"Organic","network":"Organic"},"timestamp":"2015-03-31T13:54:33.383Z+0000","message":"Attribution found"}

How could I been causing the HttpResponse to be used more than one time? The above event of attribution and the session event are fired practically at the same time, the attribution has returns success, the session is the one that changes from time to time.

I think this issue may be related to the way I'm using the Adjust.onResume() and Adjust.onPause(). The documentation says that I shoul call it for every activity, I use 3 activities, one of the is extending other, where I work with fragments. But still I tried many combinations and never have a stable version where the session never doesn't returns the error.

Thanks.

**Comment by paulocarvalhoaig** [comment]
Hi, 

Do you have any idea of how can I solve my problem? I tried every combination for setting the Adjust.onResume() and Adjust.onPause() and I'm still having the same problem, after successfully trancking a session if uninstall and install the app again, the session and all following events won't be tracked, only after more or less 30 minutes if I install the app the events will be 
This may not be a big problem for the end user, because in unlike the user will uninstall and install the app, but for the developers and testers is quite troublesome.

Thanks.

**Comment by wellle** [comment]
@paulocarvalhoaig: Yes we have a workflow for that. Please contact support@adjust.com and ask how you can reset test devices.

**Comment by faizalzakaria** [comment]
Hi Adjust,

We encounter the same problem as well. How could we test this in our test env then ? 

I'm unable to see any adjust.com/event being fired while the log says its triggered.

Thanks.

**Comment by wellle** [comment]
@faizalzakaria: If you see `Event tracked` in the SDK logs that means the event was send to  our servers and was tracked successfully. Please note that we send all traffic encrypted to **https**://app.adjust.com.

**Comment by dbachelder** [comment]
@wellle Can you publish the docs on resetting test devices in the readme?

**Comment by wellle** [comment]
@dbachelder: https://docs.adjust.com/en/getting-started/#testing-attribution

**Comment by uerceg** [comment]
@paulocarvalhoaig @faizalzakaria Are you still facing these issues?

**Comment by faizalzakaria** [comment]
Its all good now @uerceg .

Thanks @wellle @uerceg

**Comment by uerceg** [comment]
:+1: Glad to hear that.

**Comment by paulocarvalhoaig** [comment]
All good!
Thanks.

**Comment by uerceg** [comment]
Thanks for update guys. 👍
