### ISSUE TITLE
Will OnAttributionChangedListener Be Called If Device Data is Wiped?

### ISSUE THREAD

**Issue by T-Spoon** [adjust/android_sdk#104]
Hey,

Looking through the code - it seems as is OnAttributionChangedListener won't be called in the case of data clear on the device.  

For example, using Mixpanel, if open the app the first time I'll correctly get the OnAttributionChangedListener called and my events will be properly attributed.  But if I wipe the data, I'll have a new Mixpanel profile, but the OnAttributionChangedListener won't be called again it seems.

Is this intended?  Or did I miss something?

Cheers!

**Comment by nonelse** [comment]
Can you clarify what you mean by wiping the data? Is it uninstalling the app and reinstall it?

We don't have a feature to wipe data in our SDK, but if the attribution file is deleted and can't be read, the SDK will ask again for the attribution and OnAttributionChangedListener will be called.

Could you clarify the question, so we can try better to answer it?

Thanks!

**Comment by T-Spoon** [comment]
Sorry for not being clearer - specifically I mean going into App Settings -> Clear Data.  No uninstall involved.

So in this case we should get the attribution callback as normal?

**Comment by nonelse** [comment]
When the data is wiped, the state files are deleted and the app closed. When the app is re-open it will behave like has if it was installed, so the attribution changed function will be called again.

Hope it cleared your question, but let us know if it didn't.

**Comment by T-Spoon** [comment]
Cool.  That's just what I wanted to know.  Cheers!
