### ISSUE TITLE
Add support for Google Play Services version 7.0.0

### ISSUE THREAD

**Issue by fabiocarballo** [adjust/android_sdk#107]
Hello, 

We are unable to setup Adjust.

According to the logs we first have this message:
`
 E/Adjust﹕ Missing device id's. Please check if Proguard is correctly set with Adjust SDK
`

However, we have our build with minifyEnabled set to false. So we are not using Proguard.

After that log message we also have this ones:

```

E/Adjust﹕ Session failed (Missing device identifiers) (app_token: OUR_APP_TOKEN)
E/Adjust﹕ Attribution request failed (Missing device identifiers) (app_token: OUR_APP_TOKEN)
E/Adjust﹕ Attribution request failed (Missing device identifiers) (app_token: OUR_APP_TOKEN)
```
We have the AndroidManifest with the broadcast receiver and we setup Adjust on our Application onCreate method (by calling the method listed below).

```java
private void setupAdjust() {
        String appToken = getString(R.string.adjustAppToken);
        String environment = getString(R.string.adjustEnvironment);
        AdjustConfig config = new AdjustConfig(this, appToken, environment);
        config.setLogLevel(LogLevel.WARN);
        Adjust.onCreate(config);
}
```

Any ideas on what it could be?

**Comment by nonelse** [comment]
The setup seems ok. 
Somehow, maybe with hidden configurations, proguard might be running?
You could comment out the `minifyEnabled` setting and try again. The default is false anyway.
Also, try with the proguard exceptions anyway to see if it works that way.

**Comment by fabiocarballo** [comment]
Done what you said. Same results :/

**Comment by samdozor** [comment]
Does adjust require google ad id, or is android id sufficient (to avoid this error)? If google ad id is required, perhaps google play services isn't set up correctly in @fabiocarballo 's project?

**Comment by nonelse** [comment]
Our SDK uses google ad id if it's available, or a combination of mac address hash and android id. Obtaining in either way relies on reflection technique. Using proguard without exceptions prevents the use of reflection because of the mangling of the class names.
In theory, if proguard would not interfere, it would get one or the others device ids.
We can help you to debug the project to see what is happening. Send an email to support@adjust.com with a small description or this issue

**Comment by fabiocarballo** [comment]
Okay. I think I got what happened. We were using the version 7.0.0 of google play services. We reverted it to the version of 6.5.87 and the messages disappeared. 

Thanks for the help ;) Your hints led me to guess on what was wrong!

Btw, are you guys thinking on making it compatible with the 7.0.0 in a near future?

**Comment by wellle** [comment]
That's interesting, we will check what's going on with GPS v7. Thanks for letting us know :+1:

**Comment by nonelse** [comment]
I've just tested our example app with the new google play services and it seems to work ok.
Did you changed anything else?

**Comment by fabiocarballo** [comment]
I've just noticed that I was missing that we were missing 'google-play-services-adds'. I think that was the thing that was really wrong. Didn't know how we ever had this working some time ago at the first place. 

Sorry for all the trouble guys :/ You were really cool!

**Comment by wellle** [comment]
That's good news after all :wink:

Glad it's working now :+1:

**Comment by kaeawc** [comment]
I'm seeing this issue with Google Play Services 7.3.0

We have the google play services ads dependency:

```gradle
compile 'com.adjust.sdk:adjust-android:4.0.0'
```

And proguard exceptions:

```
-keep class com.adjust.sdk.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.ads.identifier.** { *; }

-dontwarn com.google.android.gms.**
```

**Comment by nonelse** [comment]
@kaeawc, the proguard exceptions looks ok. And you are seeing `Missing device identifiers` in the log, correct?
Can you double check if the proguard file that you configured is being correctly used by the `.gradle` file?
Can you test with and without proguard activated, to check if that is the culprit?
If these are not enough, we can try more ideas over email. You can send one over to support@adjust.com to speedy up things.
