### ISSUE TITLE
How to get notified for track finish events in 4.0.4

### ISSUE THREAD

**Issue by YixinZhu** [adjust/android_sdk#112]
Hi,

In previous versions, there was the ability to setOnFinishedListener passing in a OnFinishedListener to get notified about track events. This listener seems to have been removed. Has the capability been removed too or is there another way to do this in 4.0.4?

Thanks,
Yixin

**Comment by wellle** [comment]
We removed that delegate callback in order to streamline and simplify the most common use case of it: Being notified about attribution change only.

Could you let us know what use case you have in mind? What would you like to use this callback for?

**Comment by YixinZhu** [comment]
We used to check for the success/error of certain events for a couple of reasons: ensuring, on success, to not send that event again and tracking failures. I have a workaround for the time being but do you think that subscribing to success/error on events and messages a common use case or is that specific to something I'm doing?

**Comment by wellle** [comment]
Well I believe you should not need to care about that. If an event failed to track because the SDK can't reach our servers, it will retry it later automatically. If the event failed because some server side checks are failing, they will keep failing in the future, so there is no need to retry it. The SDK already knows all of that and handles errors accordingly.

**Comment by YixinZhu** [comment]
That's fair. I'll reopen with comments if a more compelling use case comes up. Thanks!

**Comment by gpolak** [comment]
+1 for getting the `OnFinishedListener` back.

We have two distinct code paths depending on the success/failure status. Up to now we were fine using the 3.X version but now need to upgrade to 4.1.2 for Android M compatibility.

**Comment by YixinZhu** [comment]
Great timing, we're starting to run into this issue as well looking ahead to Android M.

Re-opening this issue.

**Comment by nonelse** [comment]
We will release this feature in our next release. We will keep updating it here

**Comment by nonelse** [comment]
Since the attribution information is now obtained thru the attribution changed delegate, this response delegate would only contain information about the success or failure of the response of sessions and events. Is that what you would expect?

**Comment by uerceg** [comment]
Added to our latest `4.6.0` release: https://github.com/adjust/android_sdk/releases/tag/v4.6.0
