### ISSUE TITLE
Don't Start Session When Calling Adjust.onCreate()

### ISSUE THREAD

**Issue by T-Spoon** [adjust/android_sdk#118]
The example shows `Adjust.onCreate()` being called in the `Application` class.

It seems that `Adjust.onCreate()` also starts a session: https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/ActivityHandler.java#L398

This doesn't make sense for a lot of cases. Broadcast Receivers and background Services will initialise the Application class, causing a session to be tracked even though the user hasn't actually interacted with the app.

A better solution would be to start a session the first time `Adjust.onResume()` is called.  That way we know the user is interacting with an Activity

**Comment by wellle** [comment]
@T-Spoon: Thanks for you feedback. Are you aware of [multiple_process_app.md](https://github.com/adjust/android_sdk/blob/master/doc/multiple_process_app.md)?

Would that work for your use case?

**Comment by T-Spoon** [comment]
@wellle 
Hmm, not sure about that - what happens when the main process hasn't been created and you call `config.setProcessName()` from a background process?  Do all future tracking calls from the background process no-op?

Besides - making components of an app multi-process solely to workaround a tracking library isn't exactly a nice solution.

**Comment by dbachelder** [comment]
Agreed. Can we defer that until the first onResume?

**Comment by nonelse** [comment]
We are changing this a new release we [finshing](https://github.com/adjust/android_sdk/commit/01a1cf41e81b6c8eb100a9c7af818120f2611807).
I'll post here when it's merged.
Thanks!

**Comment by nonelse** [comment]
Fixed in [v4.0.8](https://github.com/adjust/android_sdk/releases/tag/v4.0.8)
