### ISSUE TITLE
Transaction id

### ISSUE THREAD

**Issue by proydakov** [adjust/android_sdk#120]
How i can set Transaction id in android SDK like iOS SDK?

/**
 * Set the transaction ID of a In-App Purchases to avoid revenue duplications.
 *
 * A transaction ID can be used to avoid duplicate revenue events. The last ten
 * transaction identifiers are remembered.
 *
 * @param transactionId The identifier used to avoid duplicate revenue events
 */
- (void) setTransactionId:(NSString *)transactionId;

**Comment by nonelse** [comment]
Hi. 

We still don't have that feature in the android SDK, but it's on the roadmap for a future version.
If you have some quick info on what the transaction id's are in Android, it could help jump start it.

Thanks for the feedback anyway!

**Comment by proydakov** [comment]
ok
