### ISSUE TITLE
add convenience methods or constructors to events

### ISSUE THREAD

**Issue by dbachelder** [adjust/android_sdk#121]
The new tracking code is more verbose, it would be pretty easy to trim it down. 

from this:

```
AdjustEvent e = new AdjustEvent(token);
e.setRevenue(rev, "USD");
Adjust.trackEvent(e);
```

to this

`Adjust.trackEvent(new AdjustEvent(token, rev, "USD"));`

or

`Adjust.trackEvent(new AdjustEvent(token).revenue(rev, "USD"));`

or

`Adjust.trackEvent(AdjustEvent.revenueEvent(token, rev, "USD"));`

I'm not picky.

**Comment by dbachelder** [comment]
Likewise for the config object, some fluid interface or builder pattern would be super sweet.

**Comment by uerceg** [comment]
@dbachelder Thank you for your suggestions, we're gonna discuss them definitely.

**Comment by wellle** [comment]
How about just letting settings like `setRevenue` return the receiver like `AdjustEvent`? Then you could use it like this (fluent):
```java
Adjust.trackEvent(new AdjustEvent(token).setRevenue(rev, "USD"));
```
This is backwards compatible, should work on all platforms and wouldn't increase the complexity we need to maintain as adding builders or convenience methods would.

**Comment by dbachelder** [comment]
sure, that was my second choice

**Comment by uerceg** [comment]
Hey @dbachelder.

After almost 4 years of discussions, we reached the conclusion that we're not gonna proceed with this for now. 😄

Suggestion @wellle made seems good enough for the use case.

Thanks for the suggestion and our longest open repository issue ever!

Cheers! 🍺
