### ISSUE TITLE
HTTP 500 errors for too frequent sessions

### ISSUE THREAD

**Issue by kaeawc** [adjust/android_sdk#125]
I've been trying to pare down HTTP and network errors in our app, and I noticed via Charles Proxy and NewRelic that Adjust is encountering a lot of HTTP 500 errors. It was primarily requesting  When I looked into the body of the response it seemed to indicate this is an expected error:

```
{"timestamp":"2015-05-27T02:44:54.937Z+0000","message":"Session failed (Ignoring too frequent session. Last session: 2015-05-26T16:44:53, this session: 2015-05-26T16:48:47, interval: 3m54s, min interval: 20m) (app_token: <a real app token here>, adid: <a real adid here>)"}
```

The Adjust SDK on our Android client is making these requests on its own when a user closes and opens the app. This is quite normal behavior. Why is it using an HTTP 5xx error code to indicate an __unexpected__ failure if this is expected behavior? And why is this only happening on the Android client and not iOS?

There should be a better solution for phoning home to the Adjust servers and the Adjust backend should use a different HTTP code so its not categorized as an error. [429 Too Many Requests](http://tools.ietf.org/html/rfc6585#page-3) would be better.

As a side note, I read in the documentation that 30 minutes should be the session interval, and it seems that such a constant is in the Android client SDK. Shouldn't the client therefore respect that interval and not attempt to query so often?

**Comment by nonelse** [comment]
Hi @kaeawc.

That message occurs when trying to initiate a new session on a device already registered in our servers. If for example, you delete the app and reinstall it.
You can make our servers "forget" the device for your app by following this doc: https://docs.adjust.com/en/getting-started/#testing-attribution 
Just call the forget link after uninstall the app and install it again during tests.

Regarding the HTTP 500 response, you are right that it should be a `4XX` response. It is like that for historical reasons of our SDK, and it cannot be changed properly without possible breaking compatibility.
Thanks for the feedback and if you have any doubts regarding the reset the device procedure, you can email us at support@adjust.com, so we can help.

**Comment by kaeawc** [comment]
We are seeing thousands of these errors a day in dev, and its not from integration tests that uninstall + reinstall, just ~5 people installing the new build, 3 of which are devs and therefore you'd maybe see 20-50 installs from each per day. The numbers don't seem to match up.

I'll implementing the forget link and see if that changes things.

**Comment by nonelse** [comment]
This mechanism in the server side that detects new activity states, allow us to keep the kpis numbers clean. Allowing for example, apps that wouldn't save the state would screw the numbers overall.

The 500 response is handled well by the SDK and it was prepared to work with proxy's that handle it differently.

If there is something not working correctly within these parameters we can provide some help. Otherwise, we like to get feedback for possible future changes. So thanks!

**Comment by kaeawc** [comment]
Ahk, that makes more sense. Thanks!
