### ISSUE TITLE
Deep Linking With Fragments

### ISSUE THREAD

**Issue by mertsaygi** [adjust/android_sdk#129]
I want to use Adjust's deep link reattributions. The tutorial says (https://github.com/adjust/android_sdk#14-handle-deep-linking) "you must send parameter to appWillOpenUrl method intent.getData() as uri". But i'm using fragments in my application. When i try to sent uri, the uri is my activity. How can i solve this issue with fragments?

**Comment by uerceg** [comment]
Hi @mertsaygi 

A fragment must always be embedded in an activity so if the idea of your deep link is to point to some specific fragment, it still needs to have activity in which it is embedded. So, you should be able to call `appWillOpenUrl` from the `onCreate` method of activity which embeds your fragments.

Cheers
Ugi

**Comment by uerceg** [comment]
Hi @mertsaygi 

Did you have any luck with this or is this still an issue?

**Comment by uerceg** [comment]
Please reopen if this is still an issue with the newest SDK version.
