### ISSUE TITLE
org.apache.http.HttpClient has been deprecated since API 22 and removed in API 23

### ISSUE THREAD

**Issue by hidroh** [adjust/android_sdk#138]
Hi, a lot of adjust classes depend on org.apache.http modules, e.g. [`com.adjust.sdk.Util`](https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/Util.java) uses on `org.apache.http.HttpClient`, which have been deprecated since API 22 and have just been removed from API 23.

**Comment by uerceg** [comment]
Hi @hidroh 

Thank you for your message. We are aware of this and we have already prepared `HttpURLConnection` replacement for `HttpClient`. We still didn't make release with that change included but will most probably be in our next one.

Cheers

**Comment by hidroh** [comment]
Thanks, any timeline for the next release before I can close this issue?

**Comment by uerceg** [comment]
I'll try to update you later today with some accurate ETA regarding this.

**Comment by hidroh** [comment]
Thanks! I'll leave the issue for you to close then.

**Comment by uerceg** [comment]
We'll most probably make an update during next week and it will contain the fix for this. I will announce in here once it's done and close the issue then.

Cheers

**Comment by nonelse** [comment]
Released https://github.com/adjust/android_sdk/releases/tag/v4.1.2

**Comment by hidroh** [comment]
:+1:
