### ISSUE TITLE
setOnAttributionChangedListener never called

### ISSUE THREAD

**Issue by mbernier85** [adjust/android_sdk#140]
We are trying to the data from onAttributionChanged, but the listener is never called.

How can we test, or troubleshoot the problem here ?  

            String appToken = "";
            String environment = AdjustConfig.ENVIRONMENT_PRODUCTION;
            AdjustConfig config = new AdjustConfig(this, appToken, environment);
            config.setOnAttributionChangedListener(new OnAttributionChangedListener() {
                @Override
                public void onAttributionChanged(AdjustAttribution attribution) {
                    postToSource(attribution);
                }
            });
            Adjust.onCreate(config);

we are using Adjust lib 4.1.2

**Comment by nonelse** [comment]
The listener should be called even when the install is organic. 
In sandbox mode, you should be able to see the response from the server by configuring the log level to `Verbose`.
In the response of the first session there should be a `attribution` parameter, or an `ask_in` that will start a timer to ask again for the attribution.
You'll need to reset the test device in our server to simulate a new install. Instructions at: https://docs.adjust.com/en/getting-started/#testing-attribution

If you still can't see it work, send us an email at support@adjust.com

**Comment by shynkevich-alex** [comment]
@nonelse 
Just to clarify OnAttributionChangedListener calls only once after install app?

**Comment by uerceg** [comment]
@shynkevich-alex 

We say that attribution callback is triggered **each time when attribution information changes from SDK point of view**.

So, in real life use cases that means that it will get trigger:

- First time upon initial SDK launch after app has been installed and SDK obtained attribution information from backend (in this case attribution changed from nothing (SDK locally inside your app had no attribution information stored) to something (initial attribution in this case)).
- During your app lifetime each time when attribution for some reason changes (you are running your retargeting campaigns or any other way). If backend on it's side knows that attribution for your user is supposed to be altered, it will provide SDK with new attribution information. Once SDK receives this new attribution information from backend, it will compare it with what it currently has stored as attribution info (which is the last value used to trigger attribution callback) and in case info received from backend is different than what SDK has stored, SDK will update locally attribution information and ping attribution callback again with this new attribution info.

In case you have any further questions, feel free to ping in here.

Cheers
