### ISSUE TITLE
Remove dependency on play-services-ads

### ISSUE THREAD

**Issue by anothem** [adjust/android_sdk#143]
Would you be open to exploring options where adjust sdk does not have a dependency on play-services-ads? Latest version of play-service-ads has around 13k methods which means that even though adjust is pretty lean itself, we suddenly lose about a fifth of our dex "range" if we integrate. This is a problem for our app and I can imagine for many others as well. 

I am aware this was [raised before](https://github.com/adjust/android_sdk/issues/124) as well, but I am suggesting that we consider finding a way to avoid the dependency altogether, since it seems like only very little of the functionality is actually used by the sdk.

**Comment by nonelse** [comment]
For apps that are being distributed thru Google Play Store, there are no other options. Our sdk does not depend on google play services directly, and can use other device ids if the Google Advertising id is not present. But if you are releasing in Google Play Store, you must use the Advertising id, as it is explained here: https://support.google.com/googleplay/android-developer/answer/6048248?hl=en

**Comment by anothem** [comment]
Thanks for the quick response! I was under the impression that this applied only for ads that are shown on device. But I may very well be interpreting it wrong and I'm sure you know this better. 

I'm trying to think of alternatives. Proguard is not ideal for us in this scenario, but we could use gradle to exclude a large part of the library and just leave the bits that you need to get the advertiser id, but we need to know what to exclude. Have you by any chance explored this option?

**Comment by nonelse** [comment]
That is a possible approach. We have done something similar for the adobe air sdk where we used a script to strip down the original [google play services library](https://github.com/adjust/gps_ane_builder#2-choose-your-own-google-play-servicesjar). 
I believe that this version is equivalent to the google-play-services-ads that can be obtained thru maven/gradle, but you could try it to verify. Although we are only using two methods for our sdk, since the google play services is not open source, there is not a lot that we can do to strip it down further to the bare essentials. 

If you are aware of something we can do, or if you come up with a solution for it, we would use it if possible

**Comment by kherembourg** [comment]
Same problem for me, I reach the dex limit with google play services ads.
But I don't with google analytics (com.google.android.gms:play-services-analytics) which is lighter than ads.
It seems that it's analytics that contains the AdvertisingIdClient class. 
Is it the only thing that Adjust needs ? If it's case, just adding analytics may be enough.

**Comment by uerceg** [comment]
Are you sure? Full path of AdvertisingIdClient is `com.google.android.gms.ads.identifier.AdvertisingIdClient`. (https://developers.google.com/android/reference/com/google/android/gms/ads/identifier/AdvertisingIdClient)

**Comment by kherembourg** [comment]
Yes, just tested it again, I have acces to the class and I see it in "External Libraries" : http://i.imgsafe.org/18e7222.png

**Comment by anothem** [comment]
That's interesting! I guess if it's used as a UUID for analytics as well, they might have included the code in both libraries.

**Comment by kherembourg** [comment]
No only in Analytics, ads include analytics.
That's weird but that's how it is. Ads does not have the com.google.android.gms.ads.identifier package, only analytics does.
I think Google should directy add it to play-services-base since it's mandatory for a lot a things now.

**Comment by uerceg** [comment]
@anothem @kherembourg Thanks for the hints. I have just tested app with out SDK inside and with only `-analytics` part instead of `-ads` and yes, everything we need is contained in `-analytics`. We will update official README with this info as well.

**Comment by anothem** [comment]
Yup, that should definitely help, analytics seems to be about half the method count! Thanks for looking!

**Comment by wellle** [comment]
Thanks :+1:

**Comment by anothem** [comment]
In a weird twist of situation, with 8.1.0 I'm doing better with ads than with analytics. Not sure why, as the package itself is definitely still bigger for ads, probably has to do with what other packages they are pulling in as their own dependencies.

**Comment by kherembourg** [comment]
Yes Google has posted a message about it : https://plus.google.com/+GoogleDevelopers/posts/HsSNWEQ6H4e
Conclusion : if you don't need it, don't update for now

**Comment by akshayarora** [comment]
It doesn't look like the README for Android has been updated yet and I ran into this issue just now as well: https://github.com/adjust/android_sdk#4-add-google-play-services

**Comment by nonelse** [comment]
You are right, we didn't change it at the time.
Re-tested and replaced now both in the documentation and the example app.
Thanks!
