### ISSUE TITLE
Proguard exclusions perhaps too broad

### ISSUE THREAD

**Issue by tmelz** [adjust/android_sdk#148]
The proguard config for adjust is:
```
-keep class com.adjust.sdk.** { *; }
-keep class com.google.android.gms.common.** { *; }
-keep class com.google.android.gms.ads.identifier.** { *; }
```
In play services 7.8.0 `com.google.android.gms.common.**` contains 2,295 methods by my checks. The limit for number of methods referenced in a dex file is 65,536, so this one exclusion accounts for about 3.5% of the limit.

Just from scoping around the source, it appears that only a few classes from  `com.google.android.gms.common` are actually needed. I'm no proguard expert, bug could we perhaps just `keep` the classes required? Another option would be an Adjust extension lib just for play services requirements (and then not use reflection), but I can understand why you wouldn't want to go that route.

**Comment by nonelse** [comment]
Thanks, we are already making the changes in the [proguard_exceptions][https://github.com/adjust/android_sdk/tree/proguard_exceptions] branch.
After some more tests and cleanup, it should be released

**Comment by nonelse** [comment]
Changed in the latest merge, thanks!

**Comment by tmelz** [comment]
Awesome, cheers @nonelse! Glad you guys were already ahead of me :)
