### ISSUE TITLE
Keep up with dependency version updates

### ISSUE THREAD

**Issue by plastiv** [adjust/android_sdk#153]
Hi! We are using adjustSdk at my company project and are happy with support and response from you guys. Thx!

I was checking the source code and noticed that some of the deps are outdated. I can give something back in return and send PRs to update them over the weekend. Let me know if you are interested in 3rd party contributions.

Proposed list of changes: 
- [x] commit gradle wrapper into source code. Why: right now it is excluded from the git tracking which is not pleasant when you are doing first time checkout. It is recommended by gradle team to add it to the repo https://docs.gradle.org/current/userguide/gradle_wrapper.html
- [x] update android gradle plugin 1.2.3 -> 1.5.0. Why: no breaking api change, just staying up-to-date.
- [x] update build tools 21.1.2 -> 23.0.2. Why: android tools team improves build speed with these update, but more importantly to make sure project does compiles with recent build tools without issue. 
- [x] update compile sdk 21 -> 23. Why: there were some breaking changes with removing apache http client and adding runtime permissions. I assume both of this changes do not touching adjust core. Update to verify assumption.
- [x] update support lib from example 21.0.3 -> 23.1.1. Why: major support lib version need to be the same as compileSdkVersion.
- [x] update play services from example 8.1.0 -> 8.3.0. Why: 8.1.0 analyticks package does contains advertise package by mistake https://plus.google.com/+GoogleDevelopers/posts/HsSNWEQ6H4e 8.3.0 fixes the issue. To verify that adjust still can be used with just gps analytics.
- [x] update gson from test 2.2.4 -> 2.4. Why: should be backward compatible, lets check. 
- [ ] add travis configuration. Why: this project is open-sourced, so we can use travis infrastructure for free: compile each commit (even PRs one) and run tests there. Why not use it?

**Comment by nonelse** [comment]
Thanks for the tips.
We will definitely look into to them in the next version of the sdk. The one just released only affected plugins, so it was still not updated.

**Comment by uerceg** [comment]
Selected things released in latest version.

Pull request: https://github.com/adjust/android_sdk/pull/162
SDK release: https://github.com/adjust/android_sdk/releases/tag/v4.2.0

**Comment by plastiv** [comment]
This is great. Thank you!

**Comment by uerceg** [comment]
Travis configuration will be added in some of the next releases. Thank you one more time for all your suggestions.
