### ISSUE TITLE
Deeplink: Intent chooser shown after app install/opening

### ISSUE THREAD

**Issue by trebouillon** [adjust/android_sdk#157]
## Short description

When the user clicks an Adjust link with deeplink in it and needs to install and open the app, the intent chooser pops up, but should immediately start the app and open the deeplink. 

## How to reproduce

* setup a campaign with deeplink using scheme android-app
 * e.g. https://app.adjust.com/fooBar?deep_link=android-app://my.package.app/http/www.example.de/list.html
* clicking the link redirects to the Play store
* after install and opening the app the intent chooser appears
![screenshot_2015-11-26-13-05-29]
(https://cloud.githubusercontent.com/assets/11941290/11534487/3e50ed58-990f-11e5-89e4-1b006c289b5d.png)

## Suggested solution
* the package name should also be specified in the map intent to start the app immediately
 * add **mapIntent.setPackage(adjustConfig.context.getPackageName());** like in the code section below

          private void launchDeeplinkMain(String deeplink) {
            if (deeplink == null) return;

            Uri location = Uri.parse(deeplink);
            Intent mapIntent = new Intent(Intent.ACTION_VIEW, location);
            mapIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);

            mapIntent.setPackage(adjustConfig.context.getPackageName());

            // Verify it resolves
            PackageManager packageManager = adjustConfig.context.getPackageManager();
            List<ResolveInfo> activities = packageManager.queryIntentActivities(mapIntent, 0);
            boolean isIntentSafe = activities.size() > 0;

            // Start an activity if it's safe
            if (!isIntentSafe) {
                logger.error("Unable to open deep link (%s)", deeplink);
                return;
            }

            logger.info("Open deep link (%s)", deeplink);
            adjustConfig.context.startActivity(mapIntent);
          }

**Comment by uerceg** [comment]
@trebouillon Thank you very much for reporting this. We'll check it out and include to next Android SDK update.

**Comment by uerceg** [comment]
Added to our new release. Thank you once more for your helpful feedback.

Pull request: https://github.com/adjust/android_sdk/pull/162
SDK release: https://github.com/adjust/android_sdk/releases/tag/v4.2.0
