### ISSUE TITLE
ActivityHandler should explicitly name the recipient of the intent.

### ISSUE THREAD

**Issue by georgiev-martin** [adjust/android_sdk#158]
Explicitly naming the recipient of an intent is better than leaving it implicit. The ActivityHandler at https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/ActivityHandler.java#L703 could use this API: http://developer.android.com/reference/android/content/Intent.html#Intent(java.lang.String, android.net.Uri, android.content.Context, java.lang.Class<?>)

**Comment by nonelse** [comment]
Thanks for the suggestion, we will look into this in the next release.

**Comment by nonelse** [comment]
Upon reading about this, I'm not sure we can use this in our SDK. It expects an activity class that we don't have access, but the app has.
One possible way would be to add a parameter that accepts this class, but wouldn't the solution present [here](https://github.com/adjust/android_sdk/issues/157) be enough to explicitly open the correct Activity, as long it's correctly configured in the app?

**Comment by georgiev-martin** [comment]
A parameter that accepts the class would be fine.

Explicitly naming the recipient is the preferred way, as it would prevent Intent spoofing.

**Comment by MarioBoehmer** [comment]
The solution presented in https://github.com/adjust/android_sdk/issues/157 is actually enough to make this work.

**Comment by uerceg** [comment]
Added to the latest update.

Pull request: https://github.com/adjust/android_sdk/pull/162
SDK release: https://github.com/adjust/android_sdk/releases/tag/v4.2.0
