### ISSUE TITLE
Instant event sending not working even setEventBufferingEnabled set to disabled

### ISSUE THREAD

**Issue by onderezdi** [adjust/android_sdk#164]

**Comment by uerceg** [comment]
Hi @onderezdi.

Any additional info maybe that you have to share with us or is the title of an issue everything?

If so, it would be helpful for us if you could send us the logs when you try to track some event (set your environment to `sandbox` and log level to `verbose`).

Cheers

**Comment by onderezdi** [comment]
We are using Criteo plugin to send events. As the title say, in sandbox or production, it is randomly stacking events before sending. I will be sent you our old log via email.

**Comment by uerceg** [comment]
@onderezdi Are you still facing this issue?

**Comment by onderezdi** [comment]
it can be closed
