### ISSUE TITLE
README step 4. is not clear

### ISSUE THREAD

**Issue by jczerski** [adjust/android_sdk#165]
Dear Sir or Madam, 

at begin I would like to thank you for the great sdk for users with Android devices. 

I would like to ask you about README which is not clear for me. In step **4. Add Google Play Services** which Google Play Services should I import? Ads part, Analytics part or both?

Thank you for the answer in advance. 

Best regards,
Jack

**Comment by uerceg** [comment]
Hi @jczerski

Indeed, it is a typo in our README. `-analytics` part is just enough for our SDK to be able to read Google Play Services ID. Thank you very much for the observation and we'll update the README as soon as possible.

Cheers
