### ISSUE TITLE
Conflicting intent-filters

### ISSUE THREAD

**Issue by theneutronchef** [adjust/android_sdk#166]
Hi,

I'm trying to add another plugin which requires MAIN and LAUNCHER in the intent-filter:

```
<intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
 </intent-filter>
```

Would Adjust still work normally after removing those from com.unity3d.player.UnityPlayerNativeActivity?
Thanks!

**Comment by nonelse** [comment]
The `MAIN` and `LAUNCHER` in the intent-filter are not from our sdk, but part of the default android manifest. What our sdk requires from the manifest is:
1 - [permission for Internet access](https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Android/AdjustAndroidManifest.xml#L36)
2 - [A broadcast receiver for install intents](https://github.com/adjust/unity_sdk/blob/master/Assets/Adjust/Android/AdjustAndroidManifest.xml#L20)
3 - If not releasing to Google Play Store and not using Google Play Services, access to information about Wi-Fi networks

**Comment by Obaied** [comment]
Closed due to inactivity.
