### ISSUE TITLE
Can we disable the 20 minute timeout on sandbox?

### ISSUE THREAD

**Issue by TedHoward** [adjust/android_sdk#168]
Developer productivity is often limited by the iteration cycle of compile, link, launch. With adjust's attribution APIs this becomes compile, link, wait 20 minutes, launch. The reason is that if you skip that 20 minutes adjust won't call your attribution callback.

The result is that adding support for attribution takes hours when it could take minutes. In our latest bug we had a simple logic issue parsing the attribution results. Since I had to fix then debug to test 3 times this took almost a day (because I didn't just stare at a screen for 3x 20 minutes, I task switched). The end result was 2 lines of code changed. Those 2 lines took almost a day *entirely* because of that 20 minute timeout.

I understand why it exists and should continue to exist in production. Can we disable it for sandbox?

**Comment by uerceg** [comment]
Hi @TedHoward 

We are currently preparing official docs of how to handle these kind of situation. In the meantime, please write us a short email to support@adjust.com and reference this GitHub issue. We'll guide you thru possible solution which will hopefully be applicable to your scenarios.

Cheers

**Comment by TedHoward** [comment]
Thanks for the offer, but I think all our bugs have been worked out. This was just a feature request to help improve your service for future developers.

Another such feature request would be to use event names instead of token strings in your API calls. We have a C++ compiled for winrt, winphone, google, and ios. Because we have separate apps in Adjust for these we have to have code that translates our "purchase" event into things like "a87d63" and "23k4n66" depending on which platform we're compiling for. Again, we've implemented that code already but it's a nasty problem. It was also a source of bugs where we were tracking the wrong events sometimes because tokens have no meaning for humans.
