### ISSUE TITLE
Add Consumer Proguard Configuration

### ISSUE THREAD

**Issue by vanniktech** [adjust/android_sdk#171]
Can be done like this:

``` groovy
android {
    defaultConfig {
        consumerProguardFiles 'proguard-rules.txt'
    }
}
```

And in the text file just simply put the lines that are currently in the README. The only requirement for `consumerProguardFiles` is that the library would need to be shipped as an AAR. I've looked it up on Sonatype and currently the library is shipped as an Jar.

Any reason for not moving forward to AAR and making the set up process a bit easier? (with already providing the proguard rules)

**Comment by nonelse** [comment]
The last time we got the suggestion of using `consumerProguardFiles`, it wasn't a final version that we could depend on. We will look into it and at least add it as an option if it works.
Thanks for the help!

**Comment by vanniktech** [comment]
The flag seems to be in the Android Gradle Build Tools starting with 0.5.7 [according to this](http://tools.android.com/tech-docs/new-build-system).

I'm using it wherever I can since it's saves a lot of time on the end consumer of the library. So far I've also never had problems with it.

Another advantage is that with let's say with the new version 5 some rules change you simply update the rules and ship it instantly with version 5 of the library. No Proguard change on the consumer site is necessary.

**Comment by vanniktech** [comment]
@nonelse any update on this one?

**Comment by nonelse** [comment]
I think this is a breaking change that would be only possible with a new major version of the SDK. So, there is currently no timeline for a v5 of the SDK
