### ISSUE TITLE
No documentation for INSTAL_REFERRER broadcast testing

### ISSUE THREAD

**Issue by AlexBonel** [adjust/android_sdk#176]
That would be great if sdk provides any documentaiton about how to be sure that appropriate receiver correctly handles ```INSTAL_REFERRER``` broadcast, with parameters which Adjust is sensitive to and which could be delivered to application via ```adb shell am broadcast``` command.

**Comment by uerceg** [comment]
Hi @AlexBonel 

Thanks for the advice, it would be useful to provide this info in README, I agree. Will be added to the docs soon.

Cheers

**Comment by uerceg** [comment]
Merged https://github.com/adjust/android_sdk/pull/180.
