### ISSUE TITLE
Session number is 3-4 times more than average after adding adjust sdk with the Criteo plugin

### ISSUE THREAD

**Issue by NammariMarkavip** [adjust/android_sdk#178]
After integrating criteo for android . we started to see 3-4 times more session than our daily average .

**Comment by uerceg** [comment]
Hi @NammariMarkavip

Can you please write a short email and reference this issue in it to support@adjust.com and let us know in there your app token so that we can investigate this issue?

Thank you in advance. 

Cheers

**Comment by NammariMarkavip** [comment]
@uerceg i did sent an email .

**Comment by uerceg** [comment]
@NammariMarkavip Thank you for the update, our AMs will forward it to me as soon as they can. I'll ping you as soon as I find something out.

Cheers

**Comment by uerceg** [comment]
Solved. Not an SDK related issue.
