### ISSUE TITLE
Implement a Deeplink Listener

### ISSUE THREAD

**Issue by mbruggmann** [adjust/android_sdk#182]
We'd like to have a callback listener for deeplinks. That would give our app more control over how to handle deeplinks, e.g. respond differently during a signup flow than when the user already has an account.

The API could look something like this:
```java
final AdjustConfig config = ...
config.setOnDeeplinkReceivedListener(new OnDeeplinkReceivedListener() {
    private static final boolean LAUNCH_INTENT = true;

    @Override
    public boolean onDeeplinkReceived(final Uri deeplink) {
        if (canHandleDeeplink(deeplink)) {
          ...
          return !LAUNCH_INTENT;
        }
        return LAUNCH_INTENT;
    }
});
```

This could be implemented from the `launchDeeplink` method in `ActivityHandler.java`.

**Comment by nonelse** [comment]
Just to clarify: this callback would be triggered when the sdk receives a deferred deeplink and the boolean returned from `onDeeplinkReceived` would decide if the adjust sdk launches the deeplink or not?

**Comment by mbruggmann** [comment]
Correct. Not that I have thought about it a lot, but that would solve our use case at least.

**Comment by nonelse** [comment]
This is not something that we had though about it before.
Thank you for the feedback, we will discuss what to do.

**Comment by uerceg** [comment]
Added in `v4.7.0` release: https://github.com/adjust/android_sdk/releases/tag/v4.7.0
For reference: https://github.com/adjust/android_sdk/pull/186/commits/9e3d8a5dd4bcfc6e345ca66146065a4b4f55fd9b
