### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by haipingguo** [adjust/android_sdk#187]
java.lang.StackOverflowError
java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:1744)
java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1656)
java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:683)
java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1806)
java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
java.io.ObjectInputStream.readObject(ObjectInputStream.java:2006)
java.io.ObjectInputStream.readObject(ObjectInputStream.java:1963)
com.adjust.sdk.Util.java.lang.Object readObject(android.content.Context,java.lang.String,java.lang.String)(Util.java:108)
com.adjust.sdk.ActivityHandler.void readActivityState()(ActivityHandler.java:765)
com.adjust.sdk.ActivityHandler.void initInternal()(ActivityHandler.java:416)
com.adjust.sdk.ActivityHandler.void access$0(com.adjust.sdk.ActivityHandler)(ActivityHandler.java:372)
com.adjust.sdk.ActivityHandler$SessionHandler.void handleMessage(android.os.Message)(ActivityHandler.java:338)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:194)
android.os.HandlerThread.run(HandlerThread.java:60)

This is my problem,hope to solve it.Thank you very much.

**Comment by uerceg** [comment]
@haipingguo Can you please tell me which SDK version are you using?

**Comment by haipingguo** [comment]
My version number is 4.0.8，i need update?

**Comment by haipingguo** [comment]
My version number is 4.0.8,thanks.
From: Uglješa Erceg
Date: 2016-04-18 14:44
To: adjust/android_sdk
CC: haipingguo
Subject: Re: [adjust/android_sdk] java.lang.StackOverflowError (#187)
@haipingguo Can you please tell me which SDK version are you using?

**Comment by uerceg** [comment]
@haipingguo Yes, update to newest SDK version is always strongly recommended by us.

Are you able to reproduce this crash scenario in your app with SDK v4.0.8?

**Comment by haipingguo** [comment]
I can't reproduce it, and there are some problems.

java.lang.ClassCastException
com.a.a.i cannot be cast to java.util.List
com.adjust.sdk.PackageHandler.void readPackageQueue()(PackageHandler.java:202)
com.adjust.sdk.PackageHandler.void initInternal()(PackageHandler.java:165)
com.adjust.sdk.PackageHandler.void access$0(com.adjust.sdk.PackageHandler)(PackageHandler.java:160)
com.adjust.sdk.PackageHandler$InternalHandler.void handleMessage(android.os.Message)(PackageHandler.java:142)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:136)
android.os.HandlerThread.run(HandlerThread.java:61)

These problems hava been repaired?

**Comment by uerceg** [comment]
Yes, that is repaired. Was already reported from time to time in v4.0.8 and also, people were unable to reproduce it. For the reference: https://github.com/adjust/android_sdk/issues/160

No issue of this kind reported ever since, I would advise you to update your SDK version.

**Comment by haipingguo** [comment]
Ow, thank you!

**Comment by uerceg** [comment]
No problemo. 👍 

Please, reopen the issue if you encounter the same problem with newest SDK version.

Cheers

**Comment by uerceg** [comment]
@haipingguo Just to double check some situations, would it be possible for you to send me your ProGuard settings file? If it's not something you want to share publicly in here, you can send us an email to support@adjust.com and reference this issue.

Thanks in advance.

Cheers
