### ISSUE TITLE
Secure Broadcast Receiver

### ISSUE THREAD

**Issue by katiehutch** [adjust/android_sdk#191]
@nonelse 

**Reference:** https://github.com/adjust/android_sdk/blob/24c3b0bd2d57d0cbf70a01171d82900710cabf24/Adjust/example/src/main/AndroidManifest.xml 

* This shows the use of com.android.vending.INSTALL_REFERRER intent filter, and the com.adjust.sdk.AdjustReferrerReceiver Broadcast receiver
* In this implementation example, the Broadcast receiver is not properly secured allowing any application to call the Broadcast receiver, thus allowing a malicious application to skew numbers reported by Adjust
* It is generally recommended to secure the Broadcast receiver with a permission and level of signatureOrSystem to only allow system calls (e.g. play store installs) to call the receiver

**Comment by nonelse** [comment]
moved to internal issues
