### ISSUE TITLE
Deeplinking and Attribution

### ISSUE THREAD

**Issue by marlonbosse** [adjust/android_sdk#193]
hey, I've got some trouble regarding the deeplink functionality and reattribution. I try my best to describe it as narrow as possible:

I got a deeplink like this: 
`http://app.adjust.com/f0ob4r?deep_link=myapp://`

to this point everything works as expected, my app opens and displays the desired activity.
I also set the Logger to VERBOSE to keep track of what exactly happens.

this is the output when the deeplink comes in (obfuscated internals)

```
ClientSdk: android4.7.0
Parameters:
android_id       *string*
app_token        *right app token*
click_time       2016-06-14T16:23:26.152Z+0200
created_at       2016-06-14T16:23:26.152Z+0200
deeplink         *deeplink schema with adjust_reftag=*
environment      sandbox
event_buffering_enabled 0
gps_adid         *string*
needs_response_details 1
reftag           *reftag id*
source           deeplink
tracking_enabled 1
```

in the onCreate() of the activity I added:

```
Intent intent = getIntent();
Uri data = intent.getData();
Adjust.appWillOpenUrl(data);
```

in the end, the following tracked event is added only to the "Organic" tracker though.

I'll get this response:

```
Response: {"attribution":{"tracker_token":"*token*","tracker_name":"Organic","network":"Organic"},"app_token":"*correct token","adid":"*an id*","timestamp":"2016-06-14T14:38:00.101Z+0000","message":"Event tracked '*correct event id*'"}
```

I also tried to add another query-parameter to the deeplink and read this one and set `Adjust.setReferrer(String)` but no success aswell.

Am I missing something fundamentally? Appreciate any help.

**Comment by uerceg** [comment]
Hi @marlonbosse 

Skip using `Adjust.setReferrer` method, because it is meant to be used by users who have distributed their apps maybe outside of Play Store and at some point of time, they want to assign it to some custom referrer. That's not the thing you need for this.

Lemme get your desired use case clear: You have the app installed and it was probably attributed as an organic install. Now you want to click on your tracker URL which has `deep_link` parameter like you have wrote it above, open the app and reattribute it to this new `f0ob4r` tracker?

**Comment by marlonbosse** [comment]
@uerceg Exactly, I tried the `Adjust.setReferrer` only after the other way didn't worked.

Exactly thats my usecase. It is an organic install because its the development version. the `f0ob4r` tracker is just a sample, I pass an actual tracker id of course.

**Comment by Obaied** [comment]
Closed due to inactivity.

**Comment by Obaied** [comment]
Hey @marlonbosse 

Are you still facing this issue after updating to the newest SDK? Please update us with the progress

**Comment by hearbeathorror** [comment]
@Obaied - is this true that a fix for this was made in Adjust 4.10.4 ? or rather higher versions than 4.7.0 ?

**Comment by uerceg** [comment]
@hearbeathorror This pretty much looks like testing flow described in your issue (https://github.com/adjust/android_sdk/issues/244) should be checked.

This flow (reattribution with the deep links) is unchanged throughout versions 4.7.0 - 4.11.0 and should work with any of them.

**Comment by Obaied** [comment]
@hearbeathorror Do you still face the same issue? Please update us on the progress.

**Comment by Obaied** [comment]
@hearbeathorror I'll close the issue for now due to inactivity. Feel free to reopen if the situation resurfaced.
