### ISSUE TITLE
New Version does not sync event to Adjust dashboard 

### ISSUE THREAD

**Issue by NammariMarkavip** [adjust/android_sdk#195]
I updated the adjust library old version was 4.2.3 and the updated one is 4.7.0 . 
i didn't see any change logs on library from your side . 
now our app  does not send events , if i revert back to old version it works fine  (4.2.3) .

**Comment by nonelse** [comment]
Sorry for the late reply.
Is that something that you can replicate in a test device with logs activated?

**Comment by uerceg** [comment]
Hi @NammariMarkavip 

Any update on this issue?

Cheers

**Comment by Obaied** [comment]
Closed due to inactivity.
