### ISSUE TITLE
Should AdjustReferrerReceiver have exported="false"?

### ISSUE THREAD

**Issue by gwilli** [adjust/android_sdk#196]
I'm seeing this lint warning in my AndroidManifest.xml file when I add the receiver they way it is specified in your README.

> Exported receivers (receivers which either set exported=true or contain an intent-filter and do not specify exported=false) should define a permission that an entity must have in order to launch the receiver or bind to it. Without this, any application can use this receiver.

Is the README correct or should the referrer receiver be set to `exported="false"`?

**Comment by uerceg** [comment]
Hi @gwilli 

Here's explanation of `exported` field:

```
android:exported

Whether or not the broadcast receiver can receive messages from sources 
outside its application — "true" if it can, and "false" if not. If "false", the only 
messages the broadcast receiver can receive are those sent by components 
of the same application or applications with the same user ID.

The default value depends on whether the broadcast receiver contains intent 
filters. The absence of any filters means that it can be invoked only by Intent 
objects that specify its exact class name. This implies that the receiver is 
intended only for application-internal use (since others would not normally know 
the class name). So in this case, the default value is "false". On the other hand, 
the presence of at least one filter implies that the broadcast receiver is intended 
to receive intents broadcast by the system or other applications, so the default 
value is "true".

This attribute is not the only way to limit a broadcast receiver's external exposure. 
You can also use a permission to limit the external entities that can send it 
messages (see the permission attribute).
```

So this sentence: 

```On the other hand, the presence of at least one filter implies that the broadcast 
receiver is intended to receive intents broadcast by the system or other applications, 
so the default value is "true".
```

says that if we want to receive intents from the Android system (which is exact thing what our broadcast receiver does), it needs to be set to `true`.

**Comment by gwilli** [comment]
Hmm... I wonder why Android Studio has that lint check then. Seems like based on the description and all other documentation I see about implementing a receiver with a `com.android.vending.INSTALL_REFERRER`, that you're correct and it should have `exported="true"`. 

Thanks for your response!

**Comment by falconxunit** [comment]
Yes its true but the epost i had it but it say open in pdf but i dont se it
are we ,us ...

**Comment by Obaied** [comment]
Closed due to inactivity.

**Comment by Obaied** [comment]
Hey @falconxunit 

Are you still facing troubles with this issue?

**Comment by Obaied** [comment]
I'll close this issue for now. Please feel free to reopen if necessary.
