### ISSUE TITLE
http://app.getresponse.com/click.html?x=a62b&lc=ufRYi&mc=ll&s=rNxq25&u=BKnS&y=O&

### ISSUE THREAD

**Issue by falconxunit** [adjust/android_sdk#198]
?

**Comment by falconxunit** [comment]
http://app.getresponse.com/click.html?x=a62b&lc=ufRYi&mc=ll&s=rNxq25&u=BKnS&y=O&

**Comment by uerceg** [comment]
@falconxunit 

What is your question?

**Comment by Obaied** [comment]
Closed due to inactivity, please feel free to reopen the issue if it still persists with latest SDK version.

**Comment by suiody** [comment]
اريد فتح النشاط
