### ISSUE TITLE
Attribution doesn't update.

### ISSUE THREAD

**Issue by phienkaka** [adjust/android_sdk#199]
I have a deeplink like this one
http://app.adjust.com/{tracker}?deep_link=my_app://{app_url}/?adjust_tracker={tracker}&adjust_campaign=campaign&adjust_adgroup=adgroup&adjust_creative=creative

After using this deeplink I see that request was sent to adjust

```
POST /sdk_click HTTP/1.1
Client-SDK: android4.1.5
Content-Type: application/x-www-form-urlencoded
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-N910C Build/MMB29K)
Host: app.adjust.com
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 376

campaign=campaign&source=deeplink&tracker={tracker}&click_time=2016-07-06T17%3A15%3A04.347Z%2B0700&creative=creative&needs_attribution_data=1&gps_adid={adid}&adgroup=adgroup&app_token={token}&environment=production&created_at=2016-07-06T17%3A15%3A04.348Z%2B0700&tracking_enabled=1&sent_at=2016-07-06T17%3A15%3A45.484Z%2B0700
```

And I get response

```
HTTP/1.1 200 OK
Date: Wed, 06 Jul 2016 10:16:06 GMT
Content-Length: 70
Content-Type: text/plain; charset=utf-8
Connection: close

{"app_token":"TOKEN","adid":"ADID"}
```

So, now each time I sent an event to Adjust I got the response with Adjust attribution

```
{"attribution":{"tracker_token":"TRACKER_TOKEN","tracker_name":"ID_AND_KomliEC::ID_AND_Komli_EC","network":"ID_AND_KomliEC","campaign":"ID_AND_Komli_EC"},"app_token":"APP_TOKEN","adid":"ADID"}
```

You can see that the request attribution and response attribution doesn't matching, and moreover I can not get the call back on OnAttributionChangeListener() Listener.

So, how can I fix it?

**Comment by uerceg** [comment]
Hi @phienkaka 

Just to check first, the `deep_link` parameter in your URL is encoded right? If not, this part:
```
my_app://{app_url}/?adjust_tracker={tracker}&adjust_campaign=campaign&adjust_adgroup=adgroup&adjust_creative=creative
```
should be URL encoded.

If that's fine, there's another thing that you should have in mind while testing. If you have already installed your app, it has some initial attribution (if you just installed it directly from Android Studio, it's probably an organic install). Now, if you want to do the reattribution with deep link (which seems to me like you're trying to do based on your tracker URL), click on this link will change the attribution of that particular install only if two conditions are satisfied:

1. Once you click the URL and open your app, new session should be triggered (that pretty much means 30+ minutes of your app not being in foreground).
2. You are not clicking the link in this interval: `installation time` + `reattribution window` (which you are setting in your dashboard).

So, if those two conditions are satisfied, your app will get reattributed.

If you don't have your app released and if you have the freedom to do this (but be careful with it), you can make the organic installation of your app in sandbox mode, put the app in background and wait for 30+ minutes and once that time has elapsed, quickly change the reattribution window to 0 on the dashboard, click on the tracker URL to launch your app and it should be reattributed. After that, change the reattribution window to its original value.

However, **PLEASE have in mind that dealing with reattribution window affects all installations of your app and think well if this is something you want to do.**

`OnAttributionChangeListener()` will always get triggered once attribution changes. It will be triggered when you install the app for the first time ever on your device (once your app receives initial attribution) and when ever attribution changes in the future.

If you have any other questions or concerns, feel free to ask.

Cheers

**Comment by phienkaka** [comment]
Thank you, you are right, I need to wait 30 minutes for getting the change.
I think we can close this issue.
