### ISSUE TITLE
AdvertisingID fallback broken on build tools 24 + play services 9.2

### ISSUE THREAD

**Issue by n-belokopytov** [adjust/android_sdk#200]
After updating to build tools 24 and getting the latest version of play services, we've noticed that our install attribution is broken. Investigation of the issue showed that "OnAttributionChangedListener" does not get called at all. After providing the Advertising ID the listener started get called again.

**Comment by nonelse** [comment]
Sorry for the late reply.
I just tested the current version with an app with build tools 24 and the latest version of play services and did not had an issue with the attribution changed callback. Can you replicate it in a test device?
 Also, what do you mean by `After providing the Advertising ID the listener started get called again`?

**Comment by Obaied** [comment]
Hey @n-belokopytov 
Can you please let us know What's the status of this issue?

Cheers :)

**Comment by n-belokopytov** [comment]
@nonelse @Obaied providing the Advertising ID = adding 
com.google.android.gms:play-services-analytics:9.6.1
to the project.

Apparently cannot reproduce on 4.10.2

**Comment by uerceg** [comment]
👍 Can we close this issue then? Feel free to reopen it if this issue still persist.

**Comment by n-belokopytov** [comment]
@uerceg sure, thanks!
