### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by rrbrambley** [adjust/android_sdk#214]
> If you are already using a different broadcast receiver for the INSTALL_REFERRER intent, follow [these instructions](https://github.com/adjust/android_sdk/blob/master/doc/referrer.md) to add the Adjust broadcast receiver.

That URL – https://github.com/adjust/android_sdk/blob/master/doc/referrer.md – leads nowhere. Please fix.

**Comment by Obaied** [comment]
Link is fixed in the README. For future reference, please follow this link for English version: https://github.com/adjust/android_sdk/blob/master/doc/english/referrer.md
