### ISSUE TITLE
Adjust tracking issue after adding Appboy

### ISSUE THREAD

**Issue by Arash-gm** [adjust/android_sdk#219]
recently i have some reports from marketing team that from a specific date till now , adjust tracking wont work properly , in that time i've just setting up appboy sdk to the project. after that reports i've testet adjust config initialization and it logs ( suspicious one ) that "Attribution file not found". i wanted to know that is any instructions that i should follow to integrate both adjust and appboy to the app or not?

**Comment by nonelse** [comment]
Hi @Arash-gm 
Sorry for the delayed reply.
`Attribution file not found` is a normal log message, if you check the log level, you'll see that is a debug message, not an error.
It indicates that the attribution file was not yet created, which is normal when the sdk first launches, or is not configured to give attribution information.
Regarding the adjust tracking, I would advise to follow the guide at https://github.com/adjust/android_sdk. 
Issues not regarding the sdk should be asked at support@adjust.com
Thanks

**Comment by uerceg** [comment]
Hi @Arash-gm 

Anything else we might assist you with this issue?

**Comment by Obaied** [comment]
Closed due to inactivity, please feel free to reopen the issue if it still persists with latest SDK version.
