### ISSUE TITLE
Using the MacAddress  is violating  Google Play policies.

### ISSUE THREAD

**Issue by Rahulrsannidhi** [adjust/android_sdk#220]
In Adjust SDK found that using the user MAC Address inside MacAddressUtil class in the  plugin package.So from understanding its violation of the Google play policies  "Usage of Android Advertising ID".can you please suggest on this.
https://play.google.com/about/monetization-ads/ads/ad-id/

**Comment by uerceg** [comment]
Hi @Rahulrsannidhi 

We are **never reading MAC address when Google Play Services Ad Id is read**, which is exactly what Google is saying that it shouldn't be done.

```
The advertising identifier must not be connected to personally-identifiable information 
or associated with any persistent device identifier (for example: SSAID, MAC address, 
IMEI, etc.) without explicit consent of the user.
```

If user does not integrate Google Play Services into his app and disables the Google Ad Id reading, then we fallback to MAC address, but we **never gather those two values at same time**.

**Comment by uerceg** [comment]
Hi @Rahulrsannidhi 

For the reference: https://developer.android.com/training/articles/user-data-ids.html

Did I give you the answer you were looking for?

Cheers

**Comment by Obaied** [comment]
Closed due to inactivity, please feel free to reopen the issue if it still persists with latest SDK version.
