### ISSUE TITLE
Wrong maven path

### ISSUE THREAD

**Issue by TillSimon** [adjust/android_sdk#223]
[Here](https://github.com/adjust/android_sdk#sdk-add) you mention to insert the maven dependency

`compile 'com.adjust.sdk:adjust-android:4.10.0'`

The currently published version on maven is `4.7.0` though

**Comment by uerceg** [comment]
Hi @TillSimon 

Yeah, we just merged changes from 4.10.0 in master and Maven build is still being uploaded to the repository. Should be available in there shortly.

Cheers

**Comment by uerceg** [comment]
@TillSimon 

Should be live now.

**Comment by TillSimon** [comment]
Ah, alright, what a timing. Thanks for the notice.

**Comment by uerceg** [comment]
Can we close the issue?

**Comment by TillSimon** [comment]
Haven't tested, but I mean it makes sense that it didn't work - so, sure.
