### ISSUE TITLE
Get Adjust Tracker Token and Tracker Name synchronously

### ISSUE THREAD

**Issue by apo1981** [adjust/android_sdk#230]
Hi,

I am developing an Android app and I have integrated Adjust SDK on it using the following code in onResume method to get the Adjust Tracker Token and Adjust Tracker Name after installing and running the app for the first time. Below code perfectly working.

@Override
public void onResume() {
    Adjust.onResume(this);
    Adjust.setOnFinishedListener(new OnFinishedListener() {
        public void onFinishedTracking(ResponseData responseData) {
           String adjustTrackerName = responseData.getTrackerName();
           String adjustTrackerToken = responseData.getTrackerToken();
        }
    });
}

However, I am wondering how I can retrieve these two parameters if the callback onFinishedTracking is not trigger for any reason (i.e. before the callback is triggered the user killed the app) when app is installed and already run for the first time. 

Thank you,
Antonio

**Comment by nonelse** [comment]
Hi Antonio and thanks for the message.
This is something that we considered to add before and we will see if it will be released on a future version of the sdk

**Comment by apo1981** [comment]
Thank you for you reply

Hope to see this feature in future releases
