### ISSUE TITLE
Events not displayed in Adjust dashboard

### ISSUE THREAD

**Issue by apo1981** [adjust/android_sdk#232]
Hi again,

We have created different events in our Adjust app, and those token events are used in our Android/iOS app to track those events.

We are using sandbox mode, but when these events are sent, we are not able to display them on App Adjust Dashboard, so is there any way to check in adjust site if an event has been received and when?

We are trying to debug the reason behind that because the app token id used in the Android/iOs app is the correct one, and even the event token ids.

Thks

**Comment by uerceg** [comment]
Hi @apo1981 

Are you checking the sandbox traffic on your dashboard?

**Comment by apo1981** [comment]
do you mean the statistics dashboard? If you do, then yes I do, and the events are not counted
On contrary, what do you exactly mean abt checking the sandbox traffic on my dashboard? How can I do it?

**Comment by uerceg** [comment]
When you go to your app's statistics page in the dashboard, there's an option to check the **sandbox mode** check box and so you can see all the traffic which you did with your app while in sandbox mode.

<img width="311" alt="screen shot 2016-09-22 at 12 29 23" src="https://cloud.githubusercontent.com/assets/1741635/18744917/3f788ba2-80c0-11e6-9ba8-df4578188417.png">

**Comment by apo1981** [comment]
Yes, we are configuring the dashboard on that way, and we even selects the right events in the Column Selection section.

**Comment by avinz** [comment]
Faced the same issue. Configured SDK in sandbox mode. When launching event - I see "I/Adjust: Event tracked '****'" in console. But nothing in dashboard.

**Comment by uerceg** [comment]
@apo1981 

I saw this particular event in our backend logs and also, in your dashboard.

Please, try to go to your dashboard and check statistics for your app. Select `SANDBOX MODE`, hit `APPLY` and after that, select your event name from KPI drop down menu. You will be able to see that event happened on 22nd of September.

**Comment by uerceg** [comment]
@apo1981 Can we close this one? I suppose this is now solved?

**Comment by Obaied** [comment]
Closed due to inactivity, please feel free to reopen the issue if it still persists with latest SDK version.

**Comment by bintu1234** [comment]
HI @afjoseph I'm facing same issue , unable to track the events 

`ADJEvent *event = [ADJEvent eventWithEventToken:kEventToken1];
    [Adjust trackEvent:event];`

above code I'm using for track my event but showing below error message in console
` Malformed Event Token 'hvt4b41'
[Adjust]e: Event not initialized correctly`
and session and install events working fine with "Organic" Name i haven't created that , but  i followed same thing in Docs for my own events. can you please help me out thanks you.

**Comment by uerceg** [comment]
@bintu1234 

Seems like your event token contains 7 characters (`hvt4b41`). Each event token created in Adjust dashboard should be 6 characters long. Double check if you have properly assigned value to `kEventToken1` variable in your code.

Cheers

**Comment by bintu1234** [comment]
Hi @uerceg  Thanks for the replay, 
![screen shot 2018-12-12 at 4 49 52 pm](https://user-images.githubusercontent.com/15229187/49866510-ff006700-fe2d-11e8-9f36-b7fc368adad7.png)
Please find attachment i think token correct only and `kEventToken1` also checked everything is fine.

**Comment by bintu1234** [comment]
Hi @uerceg ,

Thank you very much for pointing me.

**Comment by rominapower** [comment]
Hii @uerceg ,

I am unable to get the  count on a particular event, even I hit successfully event.

 Event success data: Event Success msg:Event tracked 'f0ycrl' time:2020-05-03T14:11:51.576Z+0000 adid:261d2a1f9d02455913388fa257111eb0 event:f0ycrl cid:null json:{"app_token":"*********","adid":"261d2a1f9d02455913388fa257111eb0","timestamp":"2020-05-03T14:11:51.576Z+0000","message":"Event tracked 'f0ycrl'"}

 Will you please help me out this problem.

**Comment by uerceg** [comment]
@rominapower Are you referring to event count in dashboard? If yes, are you checking sandbox traffic?

**Comment by Shahid-Chawdhary** [comment]
Can anyone help me?

**Comment by shantibhatt768** [comment]
I am facing same issue, events are showing successfully in Testing console, But when I am checking Statstics, Count is not updating for those events.

Can anyone help me, If I am missing something

**Comment by uerceg** [comment]
Are you tracking the event with the SDK environment being set to sandbox or production and are you checking the same data in the dashboard?

**Comment by shantibhatt768** [comment]
Thanks for the quick response

I am checking events in Sandbox environment. It is not updating there.

**Comment by shantibhatt768** [comment]
This is a bit important for us, We need to pass reports to our marketing team,

Appreciate your quick help on this

Thanks & Regards
Shanti Bhatt

**Comment by uerceg** [comment]
Hi @shantibhatt768,

Sorry for a bit of delay. I would suggest your to reach out to support@adjust.com or your dedicated account manager in case you have one and ask them about this. You'll be in touch then with our support team which can help you in investigating about this case.
