### ISSUE TITLE
Does Adjust Forward Referrer url parameters?

### ISSUE THREAD

**Issue by jbrick** [adjust/android_sdk#235]
Hey, I was wondering if there was an adjust link like:

https://app.adjust.com/<campaign>?deep_link=<deeplink>&referrer=<referrer>

Does that referrer get forwarded to the play store or is it just replaced with the referrer adjust uses to track installs? I was wondering, if there was a way to use referrer to do instantaneous deferred deep-links on Android, without waiting for the Adjust callback to return the deep-link parameter.

**Comment by Obaied** [comment]
Hey @jbrick!

We're more than happy to answer your inquiry, but we would appreciate it if you can forward this inquiry to integration@adjust.com since this issue is not related to the `android_sdk`

**Comment by Obaied** [comment]
I'll close the issue for now. Feel free to reopen it if necessary
