### ISSUE TITLE
Can AdjustEvent be reused?

### ISSUE THREAD

**Issue by marwinxxii** [adjust/android_sdk#238]
Hi everyone,

I have events, which use only eventToken without other parameters.
Can I instantiate these events only once and then pass them to `Adjust.trackEvent(..)`?

For example:

```
public class AdjustEventReporter {
  private static final AdjustEvent phoneShowEvent = new AdjustEvent("someToken");

  public void phoneShow() {
    Adjust.trackEvent(phoneShowEvent);
  }
}
```

**Comment by uerceg** [comment]
Hi @marwinxxii 

Sure you can if that's what you want. I mean, lifecycle of `AdjustEvent` object instance is something which is fully up to you how you want to handle it. Static instance which exists somewhere or maybe you want to initialise `AdjustEvent` object instance shortly before tracking it (which is I guess the most common case), feel free to do it how ever you want.

This scenario you've described above in probably most common use case would look like this:

```java
public class AdjustEventReporter {
    public void phoneShow() {
        AdjustEvent phoneShowEvent = new AdjustEvent("someToken");
        Adjust.trackEvent(phoneShowEvent);
    }
}
```

**Comment by Obaied** [comment]
Hey @marwinxxii
Please let us know if there is anything else we can help you with. Otherwise, I think its best to close the issue.

**Comment by marwinxxii** [comment]
Thanks, I want to reuse events, to avoid allocating same objects every time.

**Comment by uerceg** [comment]
Just have in mind that if you are, let say reusing only one event object, if you set callback and/or partner parameters on it, you won't be able to delete them and they will be sent with each `Adjust.trackEvent`.

Cheers

**Comment by marwinxxii** [comment]
Yes, I understand that, I'm not setting any other parameters, only token in
constructor.

15 нояб. 2016 г. 7:35 ПП пользователь "Uglješa Erceg" <
notifications@github.com> написал:

**Comment by uerceg** [comment]
Ah, right, you're actually recreating it completely. All good. 👍
