### ISSUE TITLE
java.io.InvalidClassException messages in log

### ISSUE THREAD

**Issue by marwinxxii** [adjust/android_sdk#247]
Hi everyone, I see a lot of following messages in log:

`Failed to open Activity state for writing (java.io.InvalidClassException: com.adjust.sdk.v doesn't have a serializable field askingAttribution of type boolean)`

`Failed to open Package queue for writing (java.io.InvalidClassException: com.adjust.sdk.u doesn't have a serializable field activityKind of type class com.adjust.sdk.ActivityKind)`

Is this a normal situation? Or could it be some problem with proguard config?

I have following rules:

```
-keep class * extends java.lang.Enum { *; }
-keep enum * { *; }


#google play services (from adjust integration doc)
-keep class com.google.android.gms.common.ConnectionResult {
    int SUCCESS;
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient {
    com.google.android.gms.ads.identifier.AdvertisingIdClient$Info getAdvertisingIdInfo(android.content.Context);
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info {
    java.lang.String getId();
    boolean isLimitAdTrackingEnabled();
}
##

#adjust
-keep class com.adjust.sdk.plugin.MacAddressUtil {
    java.lang.String getMacAddress(android.content.Context);
}
-keep class com.adjust.sdk.plugin.AndroidIdUtil {
    java.lang.String getAndroidId(android.content.Context);
}
##
```

**Comment by nonelse** [comment]
Hi @marwinxxii. The serialization should not be related with the proguard configuration.
Are you by chance migrating from an older version of the adjust sdk? If so, which one?

**Comment by marwinxxii** [comment]
No, it's first time sdk was integrated.
May guess was that, these fields may have been renamed by proguard.

**Comment by nonelse** [comment]
that is a possibility, but it is strange that only two of the various fields of [ActivityState](https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/ActivityState.java#L23) would be affected.
Can you provide more information, like which Android version are you testing on, and if you can reproduce the issue consistently?

**Comment by Obaied** [comment]
@marwinxxii Can you please update us with more info?

**Comment by uerceg** [comment]
@marwinxxii We have updated `Proguard settings` chapter in our README (https://github.com/adjust/android_sdk#sdk-proguard). Please check it out, use those rules and this issue shouldn't appear anymore. If it still persists even with these rules, please let us know.

Cheers

**Comment by Obaied** [comment]
@marwinxxii we'll close the issue for now. Please feel free to reopen it if the issue occurs.
