### ISSUE TITLE
Manually appending attribution data to a deep link but the reattribution is not triggered.

### ISSUE THREAD

**Issue by pqtuan86** [adjust/android_sdk#259]
Hi folks,

The issue i'm facing with is quite same with the #193, but i used myapp://prod_view?adjust_tracker=tracker123&adjust_campaign=campaign01&adjust_adgroup=adgroup01&adjust_creative=creative01.
I use Charles to monitor the request and can see the sdk_click value, its values are correct. But all the subsequent event response values are pointing to Organic tracker ( the default one - i think).  

![sdk_click](https://cloud.githubusercontent.com/assets/6815196/21605741/a8fecf8c-d1dd-11e6-8d52-8e7804770978.png)

![subsequent_event](https://cloud.githubusercontent.com/assets/6815196/21605758/b8d7c404-d1dd-11e6-9543-f7a928e21443.png)

Reattribution Settings:
Inactive days: 0
Attribution window: 7
I waited at least 30 mins for testing the reattribution.

I read through the end of #193 but still could not find a solution for my issue.
Please help.
Thanks a lot!

P/s: I'm using: com.adjust.sdk:adjust-android-criteo:4.11.0

**Comment by uerceg** [comment]
Hi @pqtuan86 

Is this sequence of all packages which is being sent when you do the testing? When `sdk_click` gets fired, there should be `session` package being sent if you tested it after 30 minutes.

So, flow should be:

1. You use the app with some attribution value and close it / put it to background.
2. Wait for 30++ minutes.
3. Then hit the link.

In this moment `sdk_click` and `session` packages should be sent.

Is that not the case for you?

**Comment by pqtuan86** [comment]
Hi @uerceg

Thanks for your response.

Updating the SDK to the latest one and wait for 1 hour, now it's working properly!
