### ISSUE TITLE
When should session callback parameters be sent so that they're attached to the installation event?

### ISSUE THREAD

**Issue by maltzj** [adjust/android_sdk#264]
We're interested in attaching metadata to Adjust's installation event so that we can pass that information to one of our callbacks.

In order to do that, should we call `Adjust.addSessionCallbackParameter` before or after we call `Adjust.onCreate()`?

**Comment by nonelse** [comment]
if it has to be sent with the install package, it must be done before `Adjust.onCreate()` is called. Can you get the information at start time?

**Comment by Obaied** [comment]
@maltzj Can you please update us on your progress? Are you still facing the same issue?

**Comment by maltzj** [comment]
Sorry for the delay! We can get that info on Application.onCreate, so we should be good to go!  Than you for your help!
