### ISSUE TITLE
API doesn't seem to forget session as expected

### ISSUE THREAD

**Issue by oizo** [adjust/android_sdk#269]
I've been testing your deferred deeplinking, using the `OnDeeplinkResponseListener` interface. 

But when i try to 'forget' my device as described here `https://github.com/adjust/android_sdk/#ts-session-failed` only the method using `{gps_adidValue}` seems to work. From what I understand from the docs, calling any of the three endpoints should 'forget' my device. Is this expected behavior?

**Comment by oizo** [comment]
I also created a small bash script to perform the test for me:

```bash

APP_TOKEN="your-adjust-app-token"
ADID="your-adid"
ANDROID_ID="your-android-id"
GPS_ADID="your-gps-adid"
PACKAGE="your-package-name"
RECEIEVER="your-install-referrer-broadcast-receiever"
ACTIVITY="your-activity"
DEEPLINK="your-deferred-deeplink"

echo "Force stop app"
adb shell am force-stop "${PACKAGE}"

echo "Clear data"
adb shell pm clear "${PACKAGE}"

ADJUST_FORGET_ANDROID_ID="http://app.adjust.com/forget_device?app_token=${APP_TOKEN}&android_id=${ANDROID_ID}"
echo "Forget device (android_id), status: $(curl -s "${ADJUST_FORGET_ANDROID_ID}")"
ADJUST_FORGET_GPS_ADID="http://app.adjust.com/forget_device?app_token=${APP_TOKEN}&gps_adid=${GPS_ADID}"
echo "Forget device (gps_adid), status: $(curl -s "${ADJUST_FORGET_GPS_ADID}")"
ADJUST_FORGET_ADID="http://app.adjust.com/forget_device?app_token=${APP_TOKEN}&adid=&{ADID}"
echo "Forget device (adid), status: $(curl -s "${ADJUST_FORGET_ADID}")"

# faking an android useragent, to get the expected response
ADJUST_DEEPLINK="https://app.adjust.com/fyzrwo?deep_link=${DEEPLINK}"
ANDROID_USERAGENT="Mozilla/5.0 (Linux; Android 6.0; Nexus 5X Build AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36e Gecko)"
curl -A "${ANDROID_USERAGENT}" "${ADJUST_DEEPLINK}"
read -p "Copy/paste the adjust_reftag from above (e.g.: cyT0lnN3YKA8c): " REFTAG

REFERRER="adjust_reftag%3D${REFTAG}"
adb shell am broadcast -a com.android.vending.INSTALL_REFERRER -n "${PACKAGE}"/"${RECEIEVER}" --es "referrer" "${REFERRER}"

adb shell am start -n "${PACKAGE}"/"${ACTIVITY}"
```

**Comment by uerceg** [comment]
Hi @oizo 

Hm. That should not be the case. All three described methods should work, you should just make 100% sure that you are creating URLs with correct IDs.

When you track a session or event, check verbose logs for (in that moment) current values of `android_id` and `adid` that is our backend generating for you and providing it in the response to each tracked package and it should work.

**Comment by oizo** [comment]
OK, so I just setup a fresh emulator, and set the Adjust loglevet to `LogLevel.VERBOSE`. And got this in LogCat:

```
V/Adjust: Path:      /session
          ClientSdk: android4.11.0
          Parameters:
          	android_uuid     408ca151-e800-4c6b-bf60-e0ba90d88ff6
          	api_level        25
          	app_token        <our-adjust-app-token>
          	app_version      4.3.19-debug
          	attribution_deeplink 1
          	country          US
          	cpu_type         x86
          	created_at       2017-03-06T21:28:19.623Z+0100
          	device_manufacturer unknown
          	device_name      Android SDK built for x86
          	device_type      phone
          	display_height   1776
          	display_width    1080
          	environment      sandbox
          	event_buffering_enabled 0
          	gps_adid         58b092d8-9c3b-469b-a952-2d5c1f5137a7
          	hardware_name    sdk_google_phone_x86-userdebug 7.1 NPF26K 3479480 test-keys
          	language         en
          	needs_response_details 1
          	os_build         NPF26K
          	os_name          android
          	os_version       7.1
          	package_name     com.shopgun.android.shopgun.debug
          	screen_density   high
          	screen_format    normal
          	screen_size      normal
          	session_count    1
          	tracking_enabled 1
          	vm_isa           x86
```
and

```
D/Adjust: Read Attribution: tt:hnqb7a tn:Organic net:Organic cam:null adg:null cre:null cl:null adid:d8b7be81ef1a575578b8c2e073042f9a
```
I created this little bash script to do some testing of the deferred deeplink flow in Adjust [adjust-deferred-deeplink-test.sh](https://gist.github.com/oizo/a6336adb67e1195b86bae53983870f84), when run i get the following output (for both my Huawei Nexus 6P, and the emulator):

```
Dannys-MacBook-Pro:shopgun oizo$ bash adjust-deferred-deeplink-test.sh
Force stop app
Clear data
Success
Forget device (android_id), status: Device not found
Forget device (adid), status: Device not found
Forget device (gps_adid), status: Forgot device
<a href="intent://catalogs/c3824dq?adjust_reftag=cwDnus2Xtvi7h#Intent;scheme=sgn;package=com.shopgun.android.shopgun;end">Found</a>.

Copy/paste the adjust_reftag from above (e.g.: cyT0lnN3YKA8c): cwDnus2Xtvi7h
Broadcasting: Intent { act=com.android.vending.INSTALL_REFERRER cmp=com.shopgun.android.shopgun.debug/com.shopgun.android.shopgun.receiver.SgnInstallReceiver (has extras) }
Broadcast completed: result=0
Starting: Intent { cmp=com.shopgun.android.shopgun.debug/com.shopgun.android.shopgun.MainActivity }
Dannys-MacBook-Pro:shopgun oizo$ 
```

If your docs are correct i would expect the first 'forget-url' to output `Forgot device` and the subsequent calls to 'forget-urls' to output `Device not found` - no matter the order of the url's. But neither the `android_id` nor `adid` url's seems to be able to forget a device, only the `gps_adid` url.

**Comment by Obaied** [comment]
Hey @oizo. I believe there is a tiny syntax error in your BASH code here: https://gist.github.com/oizo/a6336adb67e1195b86bae53983870f84#file-adjust-deferred-deeplink-test-sh-L20

`&{ADID}` should be `${ADID}`. Please try to run it again and let us know how it goes.

**Comment by Obaied** [comment]
That is a really cool script you created there! We might use it for internal testing even :D

**Comment by oizo** [comment]
Ok, so i figured what I've been doing wrong. First, I thought this line: `android_uuid     408ca151-e800-4c6b-bf60-e0ba90d88ff6` from the log output represented what was referred to as `android_id`, partly because it has different spelling in the docs (`androidIDValue`), so it seemed resonable to me. And second is that if Google Play services is available, the `android_id` won't be set/used in `DeviceInfo`. When taking this into account (and the syntax error ;-) ) the script and 'forget-urls' work as expected.

**Comment by oizo** [comment]
I've updated the script to test the deferred deeplink, it's actually automated now, though still working if there is only one device connected:
https://gist.github.com/oizo/59e23e119862f49a10fb4c525866d00c
