### ISSUE TITLE
 Does ANDROID_ID handling change for Android O?

### ISSUE THREAD

**Issue by uechoco** [adjust/android_sdk#274]
https://developer.android.com/preview/behavior-changes.html

The specification of ANDROID_ID is changed in Android O.
The Adjust Android SDK is collecting ANDROID_ID now.
Does ANDROID_ID handling of Adjust SDK change for Android O?
Or can I continue using the current SDK?

**Comment by uerceg** [comment]
Hi @uechoco 

This upcoming change is already handled by our system out of the box. If there is any need for SDK update in order to support Android O, will be announced.

Cheers

**Comment by uechoco** [comment]
Thanks!

**Comment by Obaied** [comment]
@uechoco Could you please close the issue?
