### ISSUE TITLE
Not Getting the Clicks count in adjust Deliverable tab

### ISSUE THREAD

**Issue by gowthamidommeti** [adjust/android_sdk#281]
Hi

Iam using adjust for my project. it displays the installs count from organic and facebook installs.But it not displaying the clicks count "0".Please help me to how to increase the clicks count.

**Comment by uerceg** [comment]
Hi @gowthamidommeti 

In here we're answering only to the SDK related issues and this is something that our account managers would be able to give you the answer to.

Please, feel free to contact them by sending this issue description in email to support@adjust.com.

Cheers

**Comment by uerceg** [comment]
Hi @gowthamidommeti 

In here we're answering only to the SDK related issues and this is something that our account managers would be able to give you the answer to.

Please, feel free to contact them by sending this issue description in email to support@adjust.com.

Cheers
