### ISSUE TITLE
Problem with custom artibutes

### ISSUE THREAD

**Issue by humanooos** [adjust/android_sdk#283]
Hello I am trying to implement deep link but add an extra parameter.
This is the link that I am trying to use:
`https://app.adjust.com/{trackerId}?deep_link=myApp://&GO_TO=somewhere`

Unfortunatelly I get this data:
`myApp://?adjust_tracker={trackerId}&adjust_reftag=cxXqVSMgqKhxo`

As you can see I can't find the GO_TO parameter anywhere.
Am I doing something wrong?

**Comment by uerceg** [comment]
@humanooos This is something that you should definitely ask you dedicated account manager to help you with to be sure that you have build your tracking URLs properly. The thing I will advise you might work, but like I said, please double check with our support team if tracking URL is the right one for your use case.

From what I can see, I would maybe advise trying to URL encode content of `deep_link` parameter. Maybe try something like this: 

```https://app.adjust.com/{trackerId}?deep_link=myApp%3a%2f%2f%26GO_TO%3dsomewhere```

**Comment by Obaied** [comment]
Hey @humanooos If your problem is solved, please close this issue.
