### ISSUE TITLE
Issue with latest Android studio 2.3.3

### ISSUE THREAD

**Issue by iPhoneyDev** [adjust/android_sdk#292]
When I run the follwoing gradle command 

 **./gradlew -q dependencies app:dependencies --configuration compile --stacktrace**

I got the following error 

**org.gradle.api.GradleScriptException: A problem occurred evaluating project ':adjust'**

There is a version mismatch in com.google.android.gms services. Can any one help me on this.

Thanks

**Comment by uerceg** [comment]
@iPhoneyDev 

Are you running that command inside of your application folder? How did you add Adjust SDK to your app? Can you give us the whole output from the command you are running?

`com.google.android.gms` is not required by our SDK and shouldn't be automatically imported, this is something you are adding to your app on your own to `build.gradle` configuration file in case you are publishing your app to Google Play Store (like for example in our example app: https://github.com/adjust/android_sdk/blob/master/Adjust/example/build.gradle#L25).

**Comment by uerceg** [comment]
@iPhoneyDev 

Any update on this one?

**Comment by uerceg** [comment]
Closing the issue due to inactivity. Feel free to reopen it if the issue is still occurring.

Cheers
