### ISSUE TITLE
Lint warning: Exported receiver does not require permission

### ISSUE THREAD

**Issue by jozuasijsling** [adjust/android_sdk#296]
Example code from Adjust's `README.md` does not specify a permission.
```xml
<receiver
    android:name="com.adjust.sdk.AdjustReferrerReceiver"
    android:exported="true" >
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
    </intent-filter>
</receiver>
```

**Lint warning**
> Exported receivers (receivers which either set `exported=true` or contain an intent-filter and do not specify `exported=false`) should define a permission that an entity must have in order to launch the receiver or bind to it. Without this, any application can use this receiver.

**Solution?**

Google Tag Manager SDK's [InstallReferrerReceiver.java](https://developers.google.com/android/reference/com/google/android/gms/tagmanager/InstallReferrerReceiver) documentation suggests using `android.permission.INSTALL_PACKAGES` as the permission. Would be great if someone could confirm that this works for Adjust SDK.

**Comment by Obaied** [comment]
Thanks @jozuasijsling for the great suggestion. We're definitely looking into this.

**Comment by jozuasijsling** [comment]
@Obaied Have you had a chance to test this?

**Comment by Obaied** [comment]
@jozuasijsling Yep. We tested it. It works without issues. We will update the README accordingly. Much, much appreciate the advice.

**Comment by Obaied** [comment]
I'll drop a link here when we release the latest version for reference purposes.

**Comment by uerceg** [comment]
@jozuasijsling Done with https://github.com/adjust/android_sdk/pull/312.

Thank you one more time for the advice and sorry for a bit of delay! 🍺

**Comment by seth-gravy** [comment]
I came here looking to solve a similar issue with AppsFlyer:
```xml
<receiver
    android:name="com.appsflyer.SingleInstallBroadcastReceiver"
    android:exported="true">
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER"/>
    </intent-filter>
</receiver>
```

Hopefully by adding this, someone else can get helped through this lint issue!

**Comment by uerceg** [comment]
Hi @seth-gravy,

Well, seems like AF’s broadcast receiver definition you shared looks exactly like ours that was the reason for opening this issue at first place (without permission). 

And also, I don’t think that INSTALL_REFERRER receiver from other SDK(s) will serve the purpose for Adjust SDK.

So your solution might be way to go for people who use AF, but in lights of previous discussion on this issue, might be good for them to include mentioned permission as well. 

Cheers

**Comment by seth-gravy** [comment]
@uerceg I edited my comment to be clearer. The mentioned permission _is_ required. I was initially adding the problematic code, since that is what people would likely be searching for.

**Comment by uerceg** [comment]
@seth-gravy

Now with edited comment, seems well. Never the less, mentioning that AF’s receiver won’t work with our SDK to avoid copy paste confusion. 

Our instructions are updated a while ago as well, so following the README should prevent this issue from happening. 

Thanks for your input!

Cheers

**Comment by cesards** [comment]
After looking closer to this issue and fixing the problem by not exporting the Receiver, I just to let you know guys what documentation says about using that permission:
```

<!-- @SystemApi Allows an application to install packages.
--
  | <p>Not for use by third-party applications. -->
  | <permission android:name="android.permission.INSTALL_PACKAGES"
  | android:protectionLevel="signature\|privileged" />

```
*Not for use by third-party applications* 

I'm not really sure the implications of using it but it seems like a potential issue for your clients to use it.

Good luck!
