### ISSUE TITLE
Using SDK without play-services-analytics

### ISSUE THREAD

**Issue by pocmo** [adjust/android_sdk#297]
We are using the Adjust SDK in open source applications. Having a dependency on the closed source library 'play-services-analytics' is problematic. Is it possible to use Adjust without this dependency or would it be possible to replace this functionality with an open solution?

**Comment by pocmo** [comment]
This issue is about this part of the SDK setup:

![screenshot-2017-9-21 adjust android_sdk](https://user-images.githubusercontent.com/89638/30694968-95753106-9ed6-11e7-9112-8b439bc757d7.png)

**Comment by nonelse** [comment]
Hello @pocmo 

Like mentioned in the screenshot and in the link about [Google Advertising Id](https://support.google.com/googleplay/android-developer/answer/6048248?hl=en), this limitation is from Google regarding apps in their Play Store, not from the adjust SDK.

The adjust SDK still works properly without the Play Services library, but it will collect device identifiers that break the Google Play Developer Program Policy. This might be ok if you release the app in a non-Google Play Store, but it's probably not ok for Google Play Store.

**Comment by pocmo** [comment]
@nonelse And I assume there are no other ways to obtain the advertising id?

Compiling against "analytics" lets a lot of folks assume we'd actually use Google Analytics in the app. In addition to that adding this closed source dependency prevents us from creating an app that is completely open-source (and can lead to license incompatibilities).

**Comment by nonelse** [comment]
We understand your concerns, however, as per Google's policy, all apps that use attribution tracking which are published in the Play Store require the play services dependency, otherwise, they could be rejected from the store.

As the Google Play Services Advertising ID is the main identifier that all parties are allowed to use for tracking and retargeting, most marketing activities do require it. If you would like to track campaigns with the important networks in the market you either have the option to include this dependency or all of the marketing partners' SDKs in your app.

We're happy to discuss this further. Please get in touch with us directly via support@adjust.com and include this Github issue in your email.

**Comment by eldk** [comment]
Hello,

Reading this, I think there is some misunderstanding.

>The Google Play Developer Program Policy requires that all updates and new apps uploaded to the Play Store use the advertising ID (when available on a device) in place of any other device identifiers for any advertising purposes. You're responsible for ensuring your apps are in compliance with policies regarding its usage, as well as all Play policies.

- advertising ID, if available
- in place of any other device identifiers for any advertising purposes.

So, if you are not advertising, you will have not any consequences.

I have one app on playstore that don't use advertising ID, but don't display ads.

You should look at this app :  https://play.google.com/store/apps/details?id=eu.thedarken.sdm

Thanks,

Eric


Thanks,

Eric

**Comment by justandrea** [comment]
Hi,
You are completely right, if you don’t want to run any advertising or do attribution tracking, then the google play services are not needed.
Let me know if you still have any questions!
Thanks,
Andrea

**Comment by uerceg** [comment]
Hi @pocmo 

Are there any other concerns maybe which we didn't address in this issue?

Cheers

**Comment by uerceg** [comment]
I will assume that all the questions have been answered in this issue and close the issue. Feel free to reopen it if needed.
