### ISSUE TITLE
Not an issue just a suggestion

### ISSUE THREAD

**Issue by danerduo87** [adjust/android_sdk#298]
It's opensource and gradle based, so why not publish it to Jcenter.

**Comment by uerceg** [comment]
Hi @danerduo87 

Thanks for the suggestion, we are planning to start distributing SDK via Jcenter as well and will do this most probably starting with some of the upcoming releases.

Cheers

**Comment by danerduo87** [comment]
@uerceg Thanks for your reply, it's Greate!
