### ISSUE TITLE
Typo in ProGuard config: `LocaledList`

### ISSUE THREAD

**Issue by orrc** [adjust/android_sdk#300]
This project's README misspells the Android class name [`LocaleList`][0] as `LocaledList`, which [a few people][1] have then copy-pasted into their projects.

https://github.com/adjust/android_sdk/blob/00bf23e947c14a14dff34dc4740e10f4dc189ed5/README.md#L167-L173

Does this mean that this part of the ProGuard configuration isn't actually required?

[0]:https://developer.android.com/reference/android/os/LocaleList.html
[1]:https://github.com/search?q=LocaledList&type=Code&utf8=%E2%9C%93

**Comment by nonelse** [comment]
Hi @orrc and thanks for spotting the typo. We will updated it shortly.
Regarding why does it still work, it could be that it's using the deprecated version, or proguard ignores the return value in the method signature, or something else, like version specific proguard and/or android OS quirks.
The reason to have the rule in the proguard file still makes sense and it's safer to keep it

**Comment by uerceg** [comment]
Hi @orrc 

README has been updated (https://github.com/adjust/android_sdk/pull/311).

Thank you one more time for spotting this. 🍺
