### ISSUE TITLE
Integrating with Google Tag Manager and Firebase

### ISSUE THREAD

**Issue by jintoga** [adjust/android_sdk#302]
Hello, Is there any documentation of how to integrate Adjust with GTM? I tried to find it myself but can't find anything. Can you please provide some resources or information?

**Comment by uerceg** [comment]
Hi @jintoga 

This is most probably question for our integration team. Feel free to drop them an email with this question to support@adjust.com and someone will reach you out about this thing.

Cheers!

**Comment by jintoga** [comment]
Thanks!
