### ISSUE TITLE
Typings for AdjustBridge javascript code

### ISSUE THREAD

**Issue by indrek-rajamets** [adjust/android_sdk#303]
Please provide Typescript interfaces and types for the `AdjustConfig`, `Adjust` and `AdjustEvent`

**Comment by uerceg** [comment]
Hi @indrek-rajamets,

Sorry for, well, quite a delay in replying to this one. We never really got any request about this until this ticket was opened. Is this still relevant to you?

Cheers

**Comment by indrek-rajamets** [comment]
Hi, it is not relevant for me personally, since I no longer work with this project, but I think other developers could still benefit from these typings since typescript is gaining a lot of popularity.

**Comment by uerceg** [comment]
We are going to take a look at the topic and see if this is something we can add to current SDK version or the upcoming major version update. Thank you very much for the feedback.

**Comment by uerceg** [comment]
Unfortunately, still no plans on doing this on our end. We have added this to our backlog with reference to this issue and if there's any progress on this in the future, we'll make sure to update you in here. Thank you one more time for the advice. Cheers.
