### ISSUE TITLE
Does trackEvent automatically retry on network failure?

### ISSUE THREAD

**Issue by jngbng** [adjust/android_sdk#307]
I have a question on the internal behavior of Adjust.trackEvent.
On temporary network failure situation, does the sdk retry sending event by itself?
Or do I have to handle it using OnEventTrackingFailedListener?

**Comment by uerceg** [comment]
@jngbng

This is automatically done by SDK, no need to do it on your own.

**Comment by uerceg** [comment]
@jngbng 

Do you have any further questions or can we close this issue?

Cheers

**Comment by jngbng** [comment]
Of course, yes. Thanks a lot.

2018. 1. 6. 오전 5:01에 "Uglješa Erceg" <notifications@github.com>님이 작성:
