### ISSUE TITLE
Null context when calling setSendingReferrersAsNotsent, version 4.12.1

### ISSUE THREAD

**Issue by Jhonnybsg** [adjust/android_sdk#314]
Im having trouble trying to get the version 4.12.1 to work.
It always breaks when calling the following method, from the AdjustInstance class:

private void setSendingReferrersAsNotSent(final Context context) {
        Runnable command = new Runnable() {
            public void run() {
                SharedPreferencesManager sharedPreferencesManager = new SharedPreferencesManager(context); // **this context is always null**
                sharedPreferencesManager.setSendingReferrersAsNotSent();
            }
        };
        Util.runInBackground(command);
    }

I've followed all the instructions in the wiki page. The version before works normally. It only happens when I switch to that one. I've tried configuring the dependency in the Gradle, also import the .jar file. Both fails at run time. Please help \o/

**Comment by uerceg** [comment]
Hi @Jhonnybsg 

Can you reproduce this issue while testing? If yes, can you give us the steps you take to reproduce it?

**Comment by Jhonnybsg** [comment]
The error happens right after I call **Adjust.onCreate(adjustConfig)** .
While debugging it, after that call, the setSendingReferrersNotSent is called and the context is null. Then it crashes showing that error:

 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object

Should that context be the same as the one passed on the initialization of adjustConfig ?

AdjustConfig adjustConfig = new AdjustConfig(**this**, Const.ADJUST_APP_TOKEN, environment);

**Comment by uerceg** [comment]
Thanks for the info. Can you tell us where do you create `AdjustConfig` object and where do you invoke `Adjust.onCreate` method - is it inside of `Application` class `onCreate` method?

**Comment by Jhonnybsg** [comment]
Well, my App class extends **MuiltiDexApplication** . And I call the methods in the onCreate of the class.

**Comment by uerceg** [comment]
Hm. Out of curiosity, if you pass `getApplicationContext()` instead of `this` in `AdjustConfig` constructor, do you still see the same error?

**Comment by Jhonnybsg** [comment]
Yes, it happens. Exact same error.

**Comment by uerceg** [comment]
Can you reproduce this error in new empty app project? We are investigating, but currently unable to reproduce issue with application(s) that use either `Application` or `MultiDexApplication` classes.

**Comment by uerceg** [comment]
@Jhonnybsg 

Also, can you check if you app token and environment have been properly set before you pass them to `AdjustConfig` constructor?

**Comment by Jhonnybsg** [comment]
Ok, I will do it and return with a feedback as soon as I can.

**Comment by Jhonnybsg** [comment]
So I made a test on a new Project and a got the same error. Actually it also shows the following error message before the one I mentioned before: Malformed App Token ...
I don't know why but the app with the 4.11.1 version doesn't crash, just show that error message. But when I switch it to 4.12.1 it crashes and shows the error mentioned before, with null context.

I've checked and we are using the right App Token. Do we need to encode or do something else with the token before passing it to the AdjustConfig or it's ok to pass the raw token String?

**Comment by uerceg** [comment]
@jhonnybsg

Malformed app token means that you did not pass proper token to the AdjustConfig constructor. Since this now touches a bit sensitive parts of your data (app token), can you please send email to support@adjust.com or contact your dedicated AM and reference this issue in email and we can continue further investigation per email?

**Comment by Jhonnybsg** [comment]
Alright. Thanks.

**Comment by Jhonnybsg** [comment]
It's working now. Problem was the App Key was wrong, with one more character. Silly I know. 
We were using version 4.11.1, and the app didn't crash with the wrong token. It only showed a single line with the malformed message, and it was lost among all other Android log messages, and we didn't know it. 

Switching to version 4.12.1, the app started crashing, and that's when we actually noticed something was wrong, and now we know it was the mistyping in the token. 

We can close this issue now. Thanks for taking a time to help.

**Comment by uerceg** [comment]
Yep, thanks for noticing this though. Never the less, we'll handle this use case nicely as of next Android SDK update.

Cheers!
