### ISSUE TITLE
Adjust didn't send viewhome event when user install android application 

### ISSUE THREAD

**Issue by khaledsoft** [adjust/android_sdk#316]
Hi guys,

I integrated the adjust in my android application. I have a problem to track event viewhome. this event tracked when user open the home screen of the application, so should I create event and name it "viewhome" in the dashboard or there is an event by default send when user open the home screen?

Thank you in advance.

**Comment by uerceg** [comment]
Hi @khaledsoft 

When it comes to event tracking, there are no default events, but rather you need to do exactly what you said in your comment above - go to Adjust dashboard, create event you're interested in (name it how ever you feel like) and then inside of your app, simply follow this chapter https://github.com/adjust/android_sdk#event-tracking on the place where you think that event should be tracked and that's it.

If you have any other question, feel free to ping.

**Comment by khaledsoft** [comment]
I will create new event.
Thanks a lot.
