### ISSUE TITLE
The viewHome event isn't automatically sent once Criteo has been activated on the app. 

### ISSUE THREAD

**Issue by khaledsoft** [adjust/android_sdk#317]
hi guys,

I just integrated adjust in android application and criteo. The viewHome event is automatically sent once Criteo has been activated on the app. It is triggered for each new user session, but it didn't work. 
I setup the criteo as the following:
1- add dependencies   compile 'com.adjust.sdk:adjust-android-criteo:4.12.1'
2- I called for example to track "viewProduct" => "AdjustCriteo.injectViewListingIntoEvent(event, value)

It's work track event viewProduct, but why viewHome event didn't automatically sent once Criteo has been activated on the app. Did I miss anything during setup?

Thanks in advance.

**Comment by Pfennigbaum** [comment]
Don't you have to trigger the viewHome event by yourself?

**Comment by khaledsoft** [comment]
yes, but a member in criteo team told me that there is an event "viewHome" didn't trigger. When I changed the mode of adjust to production, he told me that the event worked. The problem is solved when the application in live not in debug mode.

Thank you.
