### ISSUE TITLE
Event failed

### ISSUE THREAD

**Issue by shadabunique** [adjust/android_sdk#322]
Hi,
I recently started getting this error whenever I try to track an event which already exists-

**E/Adjust: Event failed (Ignoring event subsequent to an event supposed to be unique (first occurred 2017-08-09 22:16:05 +0000 UTC)) (app_token: <token>, adid: <ad_id>)**

However I see below  log for new events -
**Event tracked '<event_id>'**

I already followed all the steps mentioned in the docs.
It was working fine before but I don';t when it stopped working.
I am using **adjust SDK  4.11.4** 

Can somebody please help?

**Comment by uerceg** [comment]
Hi @shadabunique

Is your event marked in the dashboard as unique?

**Comment by shadabunique** [comment]
No they are not unique.

**Comment by uerceg** [comment]
That means that you are expecting this event to be tracked only once per device. So if your user triggered an action that guided to this event being tracked, even will be successfully tracked only for the first time. Every subsequent attempt to track that event will result in tracking failure.

**Comment by shadabunique** [comment]
Ok Got it! 
And can you please tell me that how log does it takes for an event to get the tracking updated on Adjust dashboard.

**Comment by uerceg** [comment]
For that question I think it's the best if you ping your dedicated AM or if you don't have one, simply send the email with the question to support@adjust.com, since out account management team is probably best place to get the answer to this question.

**Comment by shadabunique** [comment]
Alright thanks.
