### ISSUE TITLE
Key of query parameter for deep link should be `deeplink` or `deep_link`?

### ISSUE THREAD

**Issue by mickamy** [adjust/android_sdk#324]
[Doc in this repository](https://github.com/adjust/android_sdk#standard-deep-linking-scenario) says `deep_link`, but [adjust web console](https://dash.adjust.com/#/) gives me `deeplink`.
So which one is correct?

**Comment by uerceg** [comment]
Hi @mickamy 

You can use any of those two, they should both work.

Cheers.

**Comment by mickamy** [comment]
Thanks, but it is very confusing.
