### ISSUE TITLE
Proguard exclusions perhaps too broad #2

### ISSUE THREAD

**Issue by legarspol** [adjust/android_sdk#332]
Could we narrow down this exclusion to only what is needed?
```
-keep public class com.adjust.sdk.** { *; }
```

We've run the app without it for 8 months and it seemed fine.

**Comment by uerceg** [comment]
@legarspol 

We used to have more narrowed rules, but saw lots of people not paying any attention what so ever to README when integrating SDK, so went with this approach in hope that it will minimise integration issues. Feel free to narrow them down. 👍

**Comment by legarspol** [comment]
Do you mean that you are aware of some logic within this package which does require not to be Proguard-ed? 
If the problem is that over update some people don't check the new Proguard rules then https://github.com/adjust/android_sdk/issues/147 could definitely help. On the other hand I hope we don't include a too broad wildcard in the Proguard file bundled within the library.

**Comment by uerceg** [comment]
No, there are some classes which would be good not to be ProGuarded, this is what we used to have in our README a while ago. For example: https://github.com/adjust/android_sdk/tree/v4.11.0#sdk-proguard

We were always maintaining this list in case SDK gets something added which should be left outside of ProGuard, but problem with this approach is following:

- People have integrated version X.Y.Z of our SDK, they checked README and saw which rules need to be added to their ProGuard file.
- We release X.Y.Z+1 version and maybe add a class that needs to be excluded from ProGuard as well and update the README and we hope that this will be noticed by the client who updates to that version as well.
- But that's unfortunately not the case. They just increase SDK version in their Gradle file, update to new version and miss the newly added rules.

Thus the general approach when it comes to ProGuard exclusion. #147 is definitely issue that would solve this and it is in our roadmap (I'd say we're probably get to it quite soon), but until that's not bundled into AAR which we're gonna start distributing, this is the approach we have in README to avoid potential integration issues. It is not probably the nicest approach, I fully agree, but until we start to bundle the rules into the library distributed on the Maven, it's probably easiest way to go.

**Comment by legarspol** [comment]
Alright seems fair. 👍
Maybe some reflection calls can be avoided. If a user wants to remove a logic to check the mac or android ID he will need to checkout this library and remove the file manually. At that point he could remove an entry in a class instead of a file read through reflection. This would avoid some reflection overhead for everyone and make the code stronger against such Proguard rule missing.
The other question I have is why do we check Android public attrs using reflections? the ones about ABIs and locales?

**Comment by uerceg** [comment]
Reason for reflection calls within SDK to certain APIs is that we kinda want our SDK to be independent from anything outside of standard Android library in terms of dependencies. If we are trying to make calls to certain APIs for which user needs to add some additional dependency to his app (for example in order to make calls to read whether user has enabled or disabled tracking or to read Google Play Advertising ID, user needs to add Google Play Services library dependency), we're always trying to do those calls via reflection since we don't want to enforce users to add anything into their app which they might not want to add (for example in some app stores in Asia, they don't care about Google Play Advertising Id since their devices don't even have Google Play Services library installed, so they don't want to add that dependency and increase method count in their apps simply because of the fact that some 3rd party SDK contains direct reference to it for the feature that is in their case useless). With reflection calls we are trying to avoid this and we always have fallback mechanism in handling where needed in case we fail to read these values.

For your second question, I'll will need to check with more experienced Android devs and will keep you posted in here.

**Comment by uerceg** [comment]
Just to double check, question about android public attributes (ABIs and Locales) is refering to content of ProGuard rules section from the link I shared above (https://github.com/adjust/android_sdk/tree/v4.11.0#sdk-proguard)?

**Comment by legarspol** [comment]
The reflections call I see we could avoid are:

- The one used for this plugin approach as described in my last message
- The ones used for checking Configurations attributes in https://github.com/adjust/android_sdk/blob/master/Adjust/adjust/src/main/java/com/adjust/sdk/Reflection.java

**Comment by uerceg** [comment]
👍 Thanks for the advice, adding this to our internal issue tracking system and will try to address it into our future SDK update.

**Comment by uerceg** [comment]
Hi @legarspol 

We have addressed as much as we could at this moment in our current SDK v4.15.0. If you check README, they are currently narrowed to:

```
-keep public class com.adjust.sdk.** { *; }
-keep class com.google.android.gms.common.ConnectionResult {
    int SUCCESS;
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient {
    com.google.android.gms.ads.identifier.AdvertisingIdClient$Info getAdvertisingIdInfo(android.content.Context);
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info {
    java.lang.String getId();
    boolean isLimitAdTrackingEnabled();
}
-keep public class com.android.installreferrer.** { *; }
```

It might happen that in future we decide that depending on Google Play Services and install referrer libraries should be treated as hard dependency. If that happens, then all the rules expect ones from `com.adjust.sdk.*` package will be gone. But for now, we still didn't decide to add hard dependency to these two libraries.

I hope this solves some of the things brought up in this issue. If you think it's okay to close it, feel free to. If not and you would like to have it opened until we add hard dependencies to two mentioned libraries, also fine with us, but like said, this is something that still needs to be discussed and question is are we gonna go that road or not.

Feel free to ping in here in case you have any other questions.

Cheers

**Comment by legarspol** [comment]
Sure I assume this issue can be closed.
It would be great to make sure that the few things we raised do not get lost in the meantime.
