### ISSUE TITLE
Will criteo be disabled when using Adjust.setEnabled(false)?

### ISSUE THREAD

**Issue by kihaki** [adjust/android_sdk#333]
This question is about GDPR compliance. 

When disabling Adjust by user preference via Adjust.setEnabled(false), will criteo also be disabled or do we have to take special care about criteo?

**Comment by uerceg** [comment]
@kihaki 

Yes. Criteo plugin is nothing but a wrapper class that nicely bundles in some Criteo specific parameters into event parameters list before that event is tracked by our SDK.

When SDK is disabled, no tracking is happening even though code paths for event tracking are executed inside of your app. Disable choice is persisted inside of your app and will remain in that state until explicitly toggled next time.

**Comment by kihaki** [comment]
@uerceg Thanks a lot for a swift and precise answer!

**Comment by uerceg** [comment]
No problem. Will close the issue and in case you have any other questions related to this topic, feel free to reopen the issue. Cheers. 🍺
