### ISSUE TITLE
Callback not received at all

### ISSUE THREAD

**Issue by Rohan-Amit** [adjust/android_sdk#334]
I am trying to track a purchase (Without revenue info) event in my application, the below snippet represents the tracking function, but on the AdjustConfig callbacks never called, what possibly could be the issue!

AdjustEvent event = new AdjustEvent("Event Token");
Adjust.trackEvent(event);

the blow methods never called,

setOnEventTrackingSucceededListener
setOnEventTrackingFailedListener
setOnSessionTrackingSucceededListener
setOnSessionTrackingFailedListener

any help would be much appreciated.

**Comment by uerceg** [comment]
@Rohan-Amit

Which SDK version are you using? Are you trying to track event after you have initialised SDK (created config object and called Adjust.onCreate with it)? Can you share in here SDK initialisation code you use (of course, feel free to use dummy values for sensitive data such as app token and anything else you might think of as sensitive)?

**Comment by Rohan-Amit** [comment]
@uerceg 

Thank you for your response, I am using version 4.12.4,  and yes sure I already applied the initialization of the SDK in Application extended class.  one thing I want to highlight before leaving you with my code snippet which is other events reported successfully on Adjust dashboard and the (onFinishedEventTrackingSucceeded) callback received as expected.


`String appToken = "APP-TOKEN";
  String environment = AdjustConfig.ENVIRONMENT_PRODUCTION;
  AdjustConfig config = new AdjustConfig(this, appToken, environment);
  // Set event success tracking delegate.
   config.setOnEventTrackingSucceededListener(new OnEventTrackingSucceededListener() {
            @Override
            public void onFinishedEventTrackingSucceeded(AdjustEventSuccess 
            eventSuccessResponseData) {
                Log.v("Adjust", "onFinishedEventTrackingSucceeded");
            }
        });

        // Set event failure tracking delegate.
        config.setOnEventTrackingFailedListener(new OnEventTrackingFailedListener() {
            @Override
            public void onFinishedEventTrackingFailed(AdjustEventFailure eventFailureResponseData) {
                Log.v("Adjust", "onFinishedEventTrackingFailed");
            }
        });

        // Set session success tracking delegate.
        config.setOnSessionTrackingSucceededListener(new OnSessionTrackingSucceededListener() {
            @Override
            public void onFinishedSessionTrackingSucceeded(AdjustSessionSuccess 
             sessionSuccessResponseData) {
                Log.v("Adjust", "onFinishedSessionTrackingSucceeded");
            }
        });

        // Set session failure tracking delegate.
        config.setOnSessionTrackingFailedListener(new OnSessionTrackingFailedListener() {
            @Override
            public void onFinishedSessionTrackingFailed(AdjustSessionFailure sessionFailureResponseData) 
           {
                Log.v("Adjust", "onFinishedSessionTrackingFailed");
            }
        });

        Adjust.onCreate(config);
       Adjust.setOfflineMode(false);
       registerActivityLifecycleCallbacks(new AdjustLifecycleCallbacks());`

**Comment by uerceg** [comment]
When you say other events were tracked successfully and callback for them was triggered as well, does that there is (are) certain event(s) which when you try to track it (them) callbacks are not getting triggered but for others they work well?

**Comment by Rohan-Amit** [comment]
Logs:
E/Adjust: Malformed Event Token ''
E/Adjust: Event not initialized correctly

This is mean that the token sent as an empty string ?? this strange!

**Comment by uerceg** [comment]
Yep. That can be the only reason why nothing happened. You need to make sure that your event token when creating `AdjustEvent` object is six characters string. Once that is set, it should work, but if token is malformed no event tracking is even attempted, thus resulting in behaviour you're seeing.

**Comment by Rohan-Amit** [comment]
Thank you @uerceg the issue solved. thank you for your support.
