### ISSUE TITLE
AdvertisingIdClient: Error while reading from SharedPreferences java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

### ISSUE THREAD

**Issue by umutkina** [adjust/android_sdk#342]
I want to integrate adjust SDK on my project but I got this error

AdvertisingIdClient: Error while reading from SharedPreferences java.lang.SecurityException: MODE_WORLD_READABLE no longer supported

but I didn't use MODE_WORLD_READABLE anywhere

here my code

`    String appToken = getString(R.string.adjust_token);
    String environment = AdjustConfig.ENVIRONMENT_PRODUCTION;
    AdjustConfig config = new AdjustConfig(this, appToken, environment);
    config.setLogLevel(LogLevel.VERBOSE);
    Adjust.onCreate(config);
    registerActivityLifecycleCallbacks(new AdjustLifecycleCallbacks());`

here my gradle

`  compile 'com.adjust.sdk:adjust-android:4.14.0'
compile 'com.android.installreferrer:installreferrer:1.0'`

**Comment by uerceg** [comment]
Hi @umutkina 

How does the line where you're adding Google Play Services dependency in your Gradle file look like?

**Comment by umutkina** [comment]
@uerceg 
`    compile 'com.google.android.gms:play-services:10.2.1'
`

**Comment by umutkina** [comment]
hi @uerceg 
I updated 10.2.1 to 11.4.0
and there is no warning
Thank you for support.
