### ISSUE TITLE
Reattribution via deep links

### ISSUE THREAD

**Issue by kkrol2** [adjust/android_sdk#343]
We are using 4.14.0 sdk version. "Reattribution" setting in "Attribution Settings" in adjust's console is turned on. We are trying to reattribute user via deep link but unfortunately new campaign data is ignored. Here is scenario
1. User installs app. You assign "Organic" tracker for this user. We can check this in adjust's testing console.
2. User opens deep link with campaign data. 
Example of a link: https://app.adjust.com/fdsfdsf?campaign=and_campaign&adgroup=and_ad_group&creative=and_creative&deeplink=company%3A%2F%2Fsearch
3. Deep link is correctly handled by the app and  Adjust.appWillOpenUrl(uriData, context) is called.
Result
**Expected**
User's attribution data is updated and is representing data from campaign connected to the deeplink.
**Actual result**
User's attribution data isn't updated. Tracker is still "Organic".

**Comment by uerceg** [comment]
@kkrol2 

Just to be sure - when testing and when `Adjust.appWillOpenUrl(uriData, context)` was invoked, did you see in the verbose logs that `sdk_click` package was successfully sent to backend from the SDK?

**Comment by kkrol2** [comment]
@uerceg Yes.

**Comment by uerceg** [comment]
@kkrol2

Okay, one more thing you need to make sure is that Inactivity period setting in your dashboard is set to 0. With that set, rearttributuon should happen in your test case. 

You need to be careful with that setting, though. When you set Inactivity period to 0, it would affect your currently running campaigns as well, if you have any running.

**Comment by kkrol2** [comment]
@uerceg That would explain why this feature wasn't working for us. Is there a way to change Inactivity period just for sandbox?

**Comment by uerceg** [comment]
@kkrol2

At this moment, I think not, but my advice would be to either ping your dedicated account manager or ask this by sending email at support@adjust.com, since there you will definitely get right answer to this question.

**Comment by kkrol2** [comment]
@uerceg

Ok, thanks. I think you can close this issue for now.
