### ISSUE TITLE
Adjust sdk with firebase analytics

### ISSUE THREAD

**Issue by thomsontomy** [adjust/android_sdk#346]
We have firebase analytics integrated in the app which adds `AppMeasurementInstallReferrerReceiver` automatically (firebase-analytics:16.0.0). 
As per the documentation, only one receiver can receive the `com.android.vending.INSTALL_REFERRER` event.
How do we deal with this scenario?
I found this https://github.com/adjust/android_sdk/blob/master/doc/english/referrer.md documentation. But it is not clear whether we need to manually disable the automatically added `receiver` and handle it as per the documentation.

**Comment by uerceg** [comment]
Hi @thomsontomy 

In case you have your own receiver that captures `com.android.vending.INSTALL_REFERRER`, that is the only one you need to have declared in your `AndroidManifest.xml` file. Just make sure to add a call to `AdjustReferrerReceiver` in it's `onReceive` method like stated in that document you found. There is no need for `AdjustReferrerReceiver` to be declared in your `AndroidManifest.xml` file in that case.

Cheers
