### ISSUE TITLE
No way to listen for sdk_click events

### ISSUE THREAD

**Issue by dlew** [adjust/android_sdk#355]
There's an `OnEventTrackingSucceededListener`, `OnEventTrackingFailedListener`, etc. that you can set on `AdjustConfig` in order to evaluate how tracking is going. However, there is no way to detect if sdk_click tracks are working or not.

**Comment by uerceg** [comment]
Correct, there's no way. `sdk_click` packages in general are packages which are potential carriers of new attribution information for user. In case of Android SDK, they are being fired when SDK receives referrer information either via Google install referrer library or via listening to `INSTALL_REFERRER` intent or when deep link has opened your app (when `appWillOpenUrl` method is invoked with content of the link that opened an app). We never actually saw any particular value in adding callback of such things nor anyone has ever asked for this callback. We will discuss it internally and let you know if we'll proceed with implementation or not.

Just for the record, is there any reason you need this info other than simple fact to know if `sdk_click` was tracked or not?

**Comment by dlew** [comment]
The main reason was to maybe figure out a way to implement a cap on retries as a workaround for #356.

**Comment by uerceg** [comment]
Hi @dlew, wanted to update you on this one. We will not proceed with adding these callbacks for `sdk_click` packages.
