### ISSUE TITLE
Where can I get the pushNotificationsToken?

### ISSUE THREAD

**Issue by zubinxiong** [adjust/android_sdk#364]
I'm trying to tracking app uninstalls and reinstalls on android. The FCM already work, but I hava some trouble about following method 

`Adjust.setPushToken(pushNotificationsToken, context);`

I hava no idea about the pushNotificationToken, where can I get it?  I'm trying to do this like the flowing codes, but int the example I found it register in GlobalApplication with comment. so can you help me where should I get the pushNotificationsToken?

```
public class MyFirebaseMessagingService extends FirebaseMessagingService {

    private static final String TAG = "MyFirebaseMsgService";

    @Override
    public void onNewToken(String s) {
        super.onNewToken(s);
        Adjust.setPushToken(s, this);
    }
}
```

**Comment by uerceg** [comment]
Hi @zubinxiong 

And sorry for a bit delayed reply. Correct, that is the place in which you should pass token to Adjust SDK. 👍 Maybe you can just in case pass `getApplicationContext()` instead of `this`, but shouldn't make any difference.

**Comment by zubinxiong** [comment]
thanks, maybe the example-app-java code need some update, it's a little bit outdated
