### ISSUE TITLE
Not tracking installs on Android despite log showing Adjust running

### ISSUE THREAD

**Issue by zallanx** [adjust/android_sdk#368]
I am not sure whether I have configured Android for correctly. Here is what's happening:

- when setting the mode to "sandbox", the install successfully shows up in sandbox
- when setting the mode to "production", I get the following log message `PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to 'sandbox' if you want to test your app!` twice in the logs
- however, NO Android installs show up in the dashboard.

What I am doing incorrectly?

**Comment by uerceg** [comment]
Hi @zallanx.

You're probably doing nothing incorrectly. Production environment should be used for traffic from your app which is released in the store, just not to mix it with the traffic you're generating while testing your app/SDK and checking if things work.

Reason why you might not be seeing stuff in dashboard - are you checking sandbox traffic for installs/traffic incoming from sandbox environment and production traffic for production environment setting?

**Comment by uerceg** [comment]
Hm. This would require us to check logs on our side from any incoming traffic from your app and for that, I'd advise you either to ping your dedicated account manager directly or to write an email to support@adjust.com, reference this issue in there and our account management team will check what is happening.
