### ISSUE TITLE
Deeplink Issue

### ISSUE THREAD

**Issue by ManzzBaria** [adjust/android_sdk#375]
Hello Support,
I am trying your deep link and I have followed the step that you have provided on the doc.
 Also, I have tried below sample code 
Link: https://github.com/hendych/deferred-deeplink-adjust

But not able to read deep link and custom params that I am passing on a deep link.

What I want is: 
New User
1) By click on deep link user should be redirected on the app link (on the store or somewhere at APK path)
2) After install, I want to read params on the app that I have added on deep link

Old user (Already Installed app user)
1) By click on the  deep link, it should open app directly
2) The app should be able to read params that have in the deep link

That's it.

Please provide me help on above.

I have tried too many deeplink but not able to read params
Below is my deep link test :
Deeplink: https://app.adjust.com/n9com9j?deeplink=mydiet%3A%2F%2Fneokor%3Fwidgetid%3D6&redirect=https%3A%2F%2Fs3.amazonaws.com%2Fapps-logo%2Fapks%2Fmydiet.apk

Thanks & Regards.

**Comment by uerceg** [comment]
Hi @ManzzBaria 

From what I see in your app, seems like your tracker URL is not properly made. You have assigned your `MainActivity` to handle `kurio` scheme: https://github.com/hendych/deferred-deeplink-adjust/blob/master/app/src/main/AndroidManifest.xml#L32

Which means that your `deeplink` parameter in URL needs to state that scheme, and your scheme in URL is `mydiet`.

**Comment by ManzzBaria** [comment]
Yes, But I have changed that on my source code mydiet in place of kurio .

**Comment by uerceg** [comment]
Can you point me to that place?

**Comment by ManzzBaria** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.tutorial.deferred">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>

    <application
        android:name=".App"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">


        <activity
            android:name=".MainActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="mydiet" />
            </intent-filter>

        </activity>

        <receiver
            android:name="com.adjust.sdk.AdjustReferrerReceiver"
            android:permission="android.permission.INSTALL_PACKAGES"
            android:exported="true" >
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>

    </application>

</manifest>

**Comment by uerceg** [comment]
Okay, didn't know that since the source in your repo showed other thing. Will update it in your app I downloaded and give it a shot. Will keep you posted.

**Comment by ManzzBaria** [comment]
here is my  source code
[deferred-deeplink-adjust-master 2.zip](https://github.com/adjust/android_sdk/files/2983261/deferred-deeplink-adjust-master.2.zip)

**Comment by uerceg** [comment]
Thanks, I removed your attachment since I saw your app token in it. Will give this version a shot.

**Comment by uerceg** [comment]
Ah. Now I see what's up. Fingerprinting for attributing click to install is nowdays OFF by default - if you wanna use it you need to opt in (https://www.adjust.com/blog/why-were-making-fingerprinting-opt-in/).

With fingerprinting OFF and without some device identifier in the tracker URL, no matching will be done. So you should either make sure that tracker URL which is being clicked from device is containing that device's identifier or that you turn fingerprinting ON (make sure that you check if you should be turning that on with who ever might be in charge of those decisions in your company since it does affect to attribution decisions quite a bit).

In case you have any further questions on this topic, feel free to ping in here.

Cheers

**Comment by ManzzBaria** [comment]
> Ah. Now I see what's up. Fingerprinting for attributing click to install is nowdays OFF by default - if you wanna use it you need to opt in (https://www.adjust.com/blog/why-were-making-fingerprinting-opt-in/).
> 
> With fingerprinting OFF and without some device identifier in the tracker URL, no matching will be done. So you should either make sure that tracker URL which is being clicked from device is containing that device's identifier or that you turn fingerprinting ON (make sure that you check if you should be turning that on with who ever might be in charge of those decisions in your company since it does affect to attribution decisions quite a bit).
> 
> In case you have any further questions on this topic, feel free to ping in here.
> 
> Cheers

It works now, but if an app is already installed and clicking on a deep link it is redirected to me on app link, but I want to open the app if the app already installed. Is this possible?

**Comment by ManzzBaria** [comment]
Hello, I have tried here it worked with normal deeplink to store, but when we try with deeplink in facebook it doesn't work. can you please help me here?

**Comment by sletthaug** [comment]
Hi there

Please send me an email with the details to integration@adjust.com and I will help you look into this issue.

**Comment by ManzzBaria** [comment]
> Hi there
> 
> Please send me an email with the details to [integration@adjust.com](mailto:integration@adjust.com) and I will help you look into this issue.

Email sent
