### ISSUE TITLE
Adjust.gdprForgetMe

### ISSUE THREAD

**Issue by ptychan** [adjust/android_sdk#378]
Hello,

Is there any way to tell if a user has already called Adjust.gdprForgetMe so we can control the visibility of our UI to show/hide the option?

**Comment by uerceg** [comment]
Hi @ptychan,

Currently not really direct way. GDPR forget action is the most destructive one which causes SDK kill itself after tracking that package without a chance to ever start again (unless of course app is reinstalled and SDK for a bit looses locally stored information that user is GDPR forgotten).

In current setup the only possible way which might indicate to you that user is forgotten is if you try to enable SDK (trying to enable it if already enabled won't cause any harm) and check afterwards if SDK is enabled or not. If not - enabling action failed and it can only fail if user is GDPR forgotten.

This might indicate to you that user is in that state. It is a bit hacky though and working  around current state of things, but might work.

**Comment by ptychan** [comment]
Hello @uerceg,

Thanks for your response. We have tried your approach with using the enabled status. However, it seems to always return true regardless of whether gdprForgetMe was called.

It is unfortunately to know that there isn't a direct way at the moment. We will likely update our UI messages or cache our own state to hide the UI for users who have opt out.

Thanks again.
