### ISSUE TITLE
Hack Adjust's clients applications if no Facebook app installed

### ISSUE THREAD

**Issue by StanKocken** [adjust/android_sdk#384]
This is a very serious issue, that can allow a hacker to take control of your client's applications.

The Adjust SDK is trying to get the Facebook ID as part of the Device Info: 
https://github.com/adjust/android_sdk/blob/bae29af9dd6006fecea7bc933ac150365b0c8cdb/Adjust/sdk-core/src/main/java/com/adjust/sdk/DeviceInfo.java#L295

This is not checking if only the legit Facebook App is installed. So if a user doesn't have Facebook installed an hacker can put a fake application with the `ContentProvider` `com.facebook.katana.provider.AttributionIdProvider`, then it will notify whenever a user start the app (so start a fishing login page for example) and be able to tigger execution of code within the caller process.

The solution would be to verify if the legit Facebook application is installed on the device before calling this `ContentProvider`.

**Comment by nonelse** [comment]
Hi,
I'm trying to understand the attack vector. 
I get it that it would notify the fake app of the app start containing the sdk and even be able to return an arbitrary value back to the sdk.
Besides providing a fake value, which it's not even used as a main source of truth for device identification, what I don't see immediately, is how it would jump to start a fishing login page and be able to trigger execution of code. The value returned is not interpreted as code and it's parsed.

**Comment by StanKocken** [comment]
Because the hacker's application is aware the user started the application (because it receives some instruction within its ContentProvider), then it can start his own `Activity` to show a fishing login page.

**Comment by afjoseph** [comment]
@StanKocken 

> ...and be able to tigger execution of code within the caller process.

Based on what you said in the last reply, that's not true. You just mentioned that the "hacker's application" would trigger a fishing login page, **not from the host application**, but from a hacker's application

The "hacker application", in that case, doesn't really need to wait for a `ContentProvider` to be queried, but it can do that within a timed delay from when `PACKAGE_ADDED` broadcast is launched regarding a static set of application package names or by running `ps` and seeing if application X is running. I don't think that a fishing login page could be prevented if the "hacker application" was already installed on the device.

> The solution would be to verify if the legit Facebook application is installed on the device before calling this ContentProvider.

In your scenario, what's stopping the attacker from naming their application `com.facebook.katana`? There's no application certificate fingerprint checks that would prevent me from naming my "hacker application" to anything I want.

> ...because it receives some instruction within its ContentProvider

Assuming the above is a real attack vector, you're saying that a `ContentProvider` can have an observer that would tell it when it was queried? Pardon me but I'm not aware of such a mechanism. Would be really cool to mention how. My knowledge extends to [`ContentObserver`](https://developer.android.com/reference/android/database/ContentObserver) which would `Receives call backs for changes to content`, not `Receives call backs for queries to content`. Maybe it has that mechanism as well?

**Comment by StanKocken** [comment]
Here is a demo of what I mean.
I click on "Adjust Example" (which is the demo app from your repository), with my "hacker" application installed:

![demo_hack 2019-08-20 10_16_19](https://user-images.githubusercontent.com/2204411/63330137-9316bc80-c333-11e9-898e-a182c9f08894.gif)

As you can see, as soon as I start this application, the hacker application is notified, and able to start his own Actvity, so for example a fishing login page.
It's not only when we install the application like `PACKAGE_ADDED` would do. And this  `PACKAGE_ADDED` is now very limited (starting with Android O), but yes you could start the fake application with this. 

To do this, in my hacker application I just register a provider in my Manifest:

        <provider
            android:name=".FakeProvider"
            android:authorities="com.facebook.katana.provider.AttributionIdProvider"
            android:enabled="true"
            android:exported="true" />

And I start the Activity on query:

```
class FakeProvider : ContentProvider() {
    override fun query(p0: Uri, p1: Array<out String>?, p2: String?, p3: Array<out String>?, p4: String?): Cursor? {
        val context = context!!
        val intent = Intent(context, MainActivity::class.java)
        intent.addFlags(FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(intent)
        return null
    }
...
}
```

> not from the host application, but from a hacker's application

Yes, but this application can look like the host application, to create a fishing login page.

> In your scenario, what's stopping the attacker from naming their application com.facebook.katana? There's no application certificate fingerprint checks that would prevent me from naming my "hacker application" to anything I want.

1. on the PlayStore you cannot upload an application "com.facebook.katana", like on most stores, because it's already taken by Facebook
2. you can check the application certificate from the PackageManager, that you compare to an embeed known signature for this application. This known signature is public, and even declared on the Facebook.com website: https://facebook.com/.well-known/assetlinks.json

```
{
	"package_name": "com.facebook.katana",
	"sha256_cert_fingerprints": [
		"E3:F9:E1:E0:CF:99:D0:E5:6A:05:5B:A6:5E:24:1B:33:99:F7:CE:A5:24:32:6B:0C:DD:6E:C1:32:7E:D0:FD:C1"
	]
}
```
```
val apkSignatures = try {
    context.packageManager.getPackageInfo("com.facebook.katana", PackageManager.GET_SIGNATURES).signatures
} catch (e: PackageManager.NameNotFoundException) {
    null
}
```

I will open a PR on your repository with my suggested fix.

**Comment by afjoseph** [comment]
Many thanks! This clears up all my questions. My colleague has already opened up an internal issue to deal with this. Your PR is most welcomed!

**Comment by uerceg** [comment]
Hey @StanKocken,

We have just released [v4.18.1](https://github.com/adjust/android_sdk/releases/tag/v4.18.1) which addresses this issue.

Thank you for reporting this, constructive discussion and your contribution.

Cheers! 🍺

**Comment by StanKocken** [comment]
Thanks for the quick merge/release!

**Comment by tp** [comment]
Sorry to comment on a merged PR here, but I thought this is the best place to put the question / information.

What is was wondering is this: After this PR the Facebook app now gets validated, but then afterwards the `AttributionIdProvider` content provider is requested with another string.

https://github.com/adjust/android_sdk/blob/8e3e327e24b0fd789bf1efce8146d772e89b1ab8/Adjust/sdk-core/src/main/java/com/adjust/sdk/DeviceInfo.java#L320:L334

Is there anything that ensures that the content provider is in fact provided by the app that was just verified? Or could any app create that content provider? (I wasn't able to find any docs that the app ID had to be a prefix of the content provider – and even that might leave open holes.)

An alternative verification implementation I have seen is this, which specifically resolves the content provider:

```java
private void verifyProvider() {
    ProviderInfo pi = getContext().getPackageManager().
            resolveContentProvider("com.facebook.katana.provider.AttributionIdProvider", PackageManager.GET_META_DATA);
    if (pi != null) {
        try {
            Signature[] signatures = getContext().getPackageManager().
                    getPackageInfo(pi.packageName, PackageManager.GET_SIGNATURES).signatures;
            X509Certificate cert = (X509Certificate) CertificateFactory.getInstance("X.509").generateCertificate(
                    new ByteArrayInputStream(signatures[0].toByteArray()));
            Log.d(TAG, "Provider:s digest is " + getSHA256HexFingerprint(cert.getEncoded()) + " check " +
                    (FINGERPRINT.equalsIgnoreCase(getSHA256HexFingerprint(cert.getEncoded())) ? "Passed":"Failed"));
        } catch (Exception ex) {
        }
    }
}

private static String getSHA256HexFingerprint(byte[] bytes) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        md.update(bytes);
        return String.format("%064X", new Object[]{new BigInteger(1, md.digest())});
    } catch (NoSuchAlgorithmException e) {
        return null;
    }
}
```

Would be nice if someone could either state why this isn't an issue, or whether you would like to switch to the more specific validation.

**Comment by shashanksu** [comment]
Hey @tp,

Thanks for putting up your question with detailed explanation and alternative solution.  

Let me first state how current change is taking care of validation.  So as we know in Android system, two or more apps with same content provider (same content uri) can't co-exist.  So when we validate that legit facebook app do exist, then its implicit that content provider can only be from this app. Yes, there is a possibility that facebook app discontinue this content provider in future, but it is less likely.  

Ofcourse the change you have suggested is explicit and better, which we will definitely consider in the future release.

Thank you again for reporting this!
