### ISSUE TITLE
4.18.2 jar empty?

### ISSUE THREAD

**Issue by calvarez-ov** [adjust/android_sdk#392]
Looks like the 4.18.2 release jar (`adjust-android-4.18.2.jar`) is empty. It only contains `META-INF/MANIFEST.MF`

**Comment by uerceg** [comment]
Hi @calvarez-ov 

Huh, thanks for reporting, that's weird, we're on it, will ping you with update soon.

**Comment by uerceg** [comment]
@calvarez-ov 

4.18.3 coming up soon. Will keep you posted.

**Comment by uerceg** [comment]
Just to follow up, sorry for delay, `oss.sonatype.com` is down and unreachable so we're still unable to push the update.

**Comment by uerceg** [comment]
Hi @calvarez-ov 

We have just released 4.18.3 release which should hopefully be live in Maven as well. Thanks for reporting this and in case you encounter any other issues, feel free to ping cheers.

Cheers!

**Comment by calvarez-ov** [comment]
Thanks! 😄
