### ISSUE TITLE
Install referrer is missing timestamp

### ISSUE THREAD

**Issue by aubertdavy** [adjust/android_sdk#395]
Hi,

I'm trying to send to Adjust's dashboard INSTALL information with install-referrer. 
I've got this message : Install referrer is missing timestamp

An idea ?

Thanks

**Comment by uerceg** [comment]
Hi @aubertdavy

I am not sure what do you refer to when saying to send this information to Adjust dashboard. 

Can you explain me how does your test looks like, what are the steps you're performing and what do you expect to happen? Also where do you see this timestamp message?

**Comment by aubertdavy** [comment]
@uerceg Hello.

The goal is to track down how they arrived on the android store of our application (by clicking on a link from an email, web page etc ..).

For this, i try to use INSTALL-REFERRER (maybe is not the same thing or the good solution).

My manifest : 
`
<receiver
            android:name="com.adjust.sdk.AdjustReferrerReceiver"
            android:exported="true" >
            <intent-filter>
                <action android:name="com.android.vending.INSTALL_REFERRER" />
            </intent-filter>
        </receiver>
`

I've got a button click with : 
` Intent intent = new Intent("com.android.vending.INSTALL_REFERRER");
        intent.setPackage("com.delarte.dev");
        intent.putExtra("referrer", "utm_source=adjust_preinstall&adjust_tracker=2z0c57j");
        sendBroadcast(intent);`

In the logs I have as a result : 
Install referrer is missing timestamp

**Comment by uerceg** [comment]
@aubertdavy 

Sorry for delay in replying to this one. Is this still an issue for you? Asking also because I see that you're trying to do the test with `INSTALL_REFERRER` intent way of getting referrer information which Google will stop to support as of March 2020.

**Comment by uerceg** [comment]
Feel free to comment/reopen the issue if there's still need for that. Cheers.
