### ISSUE TITLE
Adjust Standard deep linking scenario not working as expected

### ISSUE THREAD

**Issue by HRCJ7** [adjust/android_sdk#405]
This is my AndroidManifest.xml

```
       <activity
            android:name=".SplashActivity"
            android:configChanges="orientation|keyboardHidden"
            android:screenOrientation="portrait"
            android:theme="@style/address_search_by_map">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>

                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="scheme_deli" />
            </intent-filter>
        </activity>
```
SplasgActivity.java

```
 @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        Uri data = intent.getData();
        if(data != null)
            Log.d("data value",data.toString());
    }
```
I'm using below Adjust url to for deeplinking test

**https://app.adjust.com/*****?deep_link=scheme_deli://storelist**

What I did is copy above url to my mobile browser and load it but Did not see any tiger in onNewIntent method. What kind of wrong thing that I have done in here? Did I miss anything to add?

Thank you for your time !

**Comment by uerceg** [comment]
Hi @HRCJ7 

Few things in here.

First, you need to make sure that your URL is properly formatted - value of `deep_link` parameter needs to be URL encoded. So URL should look something like this: https://app.adjust.com/******?deep_link=scheme_deli%3A%2F%2Fstorelist.

Second, you should not just paste this link into browser's URL bar and try to load it from there. Put this link somewhere where you can click onto. I for example use neocities.org web site where I have my custom free subdomain where I just dump links I wanna click onto to do the tests. So try putting it at some place which you're gonna load from browser and click on that link from it.

And third,  `onNewIntent` is the place where content of deep link should be delivered if activity in charge for handling you scheme is singleton instance (for example, you have set it to be of type `singleTask`). In way how you defined you activity in the manifest, seems to me that `onCreate` method of the `SplashActivity` should be the place where you should look for deep link content. Something like this:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    Intent intent = getIntent();
    Uri data = intent.getData();
    Adjust.appWillOpenUrl(data, getApplicationContext());
}
```

Let us know if it worked for you.

Cheers

**Comment by HRCJ7** [comment]
@uerceg Thank you very much for the detailed solution. But still, I could not open my app when I click my web site URL. I have created a new web site using neocities.org and added an adjust link to that page. Now I can click that link. The current behavior is when I click that link it open browser and load a page. I'm using STG environment and its points to Adjust sandbox for testing do I need to create a link in Adjust sandbox?

**Comment by uerceg** [comment]
Awesome, thanks for letting us know. In case any other issue pops up on this topic, feel free to reopen the issue.

Cheers!
