### ISSUE TITLE
Request for documentation clarification for disableThirdPartySharing

### ISSUE THREAD

**Issue by calvarez-ov** [adjust/android_sdk#408]
The documentation currently states:
> You can now notify Adjust when a user has exercised their right to stop sharing their data with partners for marketing **partners**, but has allowed it to be shared for statistics purposes.

I think perhaps "for marketing **partners**" was supposed to be "for marketing **purposes**", no?

The documentation indicates that the following will happen after calling `disableThirdPartySharing`:
> Upon receiving this information, Adjust will block the sharing of that specific user's data to partners and the Adjust SDK will continue to work as usual.

But I didn't see any documentation on how to cancel this. I didn't see any `enableThirdPartySharing` or any other way to reset this.  Is this an irreversible api? Any plans to allow a way to reset the behavior in the future?

Many thanks.

**Comment by UlviyyaB** [comment]
Hi @calvarez-ov! Thank you for pointing out, our team is taking care of the typo right now! 

Also, we're considering to add `enableThirdPartySharing` in the future, though this needs some further internal discussions on our side. We'll keep you updated!

**Comment by calvarez-ov** [comment]
Thanks for the quick reply. Do you confirm that, without any `enableThirdPartySharing` api, the `disableThirdPartySharing` api is currently irreversible? Not even removing the call to `disableThirdPartySharing` and then clearing settings or uninstalling/reinstalling an app using the adjust sdk will re-establish the data sharing with partners, for a given user?

**Comment by uerceg** [comment]
That is correct. User for us is nothing but a combination of device identifiers we manage to read so in flow you described if Google Advertising Identifier remained the same for the user, we'll know that it's the same one who disabled third party sharing and will continue to block data sharing. If device identifiers change as well next to your scenario described above, we'll count first incoming session from SDK as an install and user as a new user who still never disabled third party sharing.

**Comment by calvarez-ov** [comment]
@uerceg Awesome, really appreciate the detailed reply!

**Comment by uerceg** [comment]
In case issue needs to be reopened and any further assistance is needed, feel free to do it. Closing this one.

Cheers!
