### ISSUE TITLE
Play Store will no longer broadcast the "install_referrer" in March 2020

### ISSUE THREAD

**Issue by hide1202** [adjust/android_sdk#410]
> We recently announced that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before March 1, 2020. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.

Google Play Store app will no longer broadcast the install_referrer intent after app installs. But you wrote a following sentence in https://github.com/adjust/android_sdk/issues/406#issuecomment-564442032

> And just to mention that `AdjustReferrerReceiver` can also be used for tracking preinstall campaigns, so if you're using it for this purpose in your apps, then don't remove it, of course. 

If play store will no longer broadcast 'install_referrer', what does `AdjustReferrerReceiver` mean?
It may be confusing to users, so i prefer to remove or deprecate the `AdjustReferrerReceiver` from the guide.

**Comment by uerceg** [comment]
Hi @hide1202 

`AdjustReferrerReceiver` is custom built class of ours which we intended for users to assign as broadcast receiver for `INSTALL_REFERRER` intent in case clients don't already have their own custom receiver for that intent defined in their apps.

For quite some time, both mechanisms (`INSTALL_REFERRER` intent and Google Referrer API) worked in parallel (they still do, until March 2020) thus we had both ways described in our README as a way to go with it. I guess things just remained in README as they always have been when it comes to this topic, but I agree with you that it probably needs a bit of clarification and we'll update README.

I am still not sure are we gonna remove the `INSTALL_REFERRER` way completely or maybe just put big warning next to it that it should not be used anymore and that it will stop working as of March 1st 2020, but one of those two ways will be update we're gonna make to README.

In our next SDK major release, we're gonna completely remove that class from SDK and install referrer API will be the only way SDK will be able to handle referrer information.

README update ticket is added to our backlog and you can expect it to be updated in first few working days of 2020.

Cheers and enjoy the holidays.

**Comment by hide1202** [comment]
@uerceg Actually, we use both of `AdjustReferrerReceiver` and `Referrer API` (I don't know why 😓 ).

We received mail from Google about deprecation of `INSTALL_REFERRER`. We want to use just `Referrer API` so we will just remove `AdjustReferrerReceiver`. Then is there any problem collecting whether users installed or not.

**Comment by uerceg** [comment]
@hide1202 

Everything should be just fine if you remove it. To double check if everything works fine for you with just install referrer API added, you can do following test:

- Uninstall app from your test device.
- Set SDK to sandbox and log level to verbose.
- Launch your app which starts Adjust SDK.

Check the logs and in there, you should see package called **sdk_click** being sent with parameter in its payload saying `source=install_referrer`. If that's the case, install referrer API is properly set in your app and our SDK is talking with it in order to get referrer information and pass it to our backend.

**Comment by uerceg** [comment]
Note added in [here](https://github.com/adjust/android_sdk/pull/412).

**Comment by hide1202** [comment]
@uerceg Thanks!!!! 😄
