### ISSUE TITLE
Deferred deep linking scenario- Can not check the scenario after application second time installation.

### ISSUE THREAD

**Issue by HRCJ7** [adjust/android_sdk#418]
I need to test deferred scenario for different cases. My standard deep linking scenario works perfectly. But when I'm started to test deferred scenario I could see correct behavior only one time.I tried several times after application uninstalls but could not see expected behavior. Any thing that I have done wrong. I set the below code also.

```
        AdjustConfig adjustConfig = new AdjustConfig(this, AppConfig.ADJUST_APP_TOKEN, environment);
        adjustConfig.setOnDeeplinkResponseListener(new OnDeeplinkResponseListener() {
            @Override
            public boolean launchReceivedDeeplink(Uri deeplink) {
                return true;
            }
        });
        Adjust.onCreate(adjustConfig);
```

**Comment by uerceg** [comment]
@HRCJ7 

Sorry for a bit delayed reply. Did you try forgetting the device you're testing with in Adjust Testing Console prior to newly installing your app?

**Comment by HRCJ7** [comment]
@uerceg Thank you very much for the reply. I solved that issue.
