### ISSUE TITLE
Can Adjust work on Huawei Devices without Google Play Services?

### ISSUE THREAD

**Issue by mahmutyetisir** [adjust/android_sdk#419]
New Huawei Devices has not contains Google Play Services. Adjust is already using Google Advertising Id but New Huawei Devices do not obtain it. How can I use Adjust on Huawei Devices without Google Play Services. How can I add OAID from Huawei Ads Kit to Adjust?

Huawei Ads Kit OAID obtaining example = https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/3030304

**Comment by nonelse** [comment]
We already do support OAID, the instructions are [here](https://github.com/adjust/android_sdk/blob/master/doc/english/plugins/oaid.md). They probably should be linked from the main readme

**Comment by mahmutyetisir** [comment]
I can not find link from the main readme but I will try OAID. Thank you.
