### ISSUE TITLE
Is it possible to transfer platform value (Android, iOS) to partner? Partner is Amplitude

### ISSUE THREAD

**Issue by oxied** [adjust/android_sdk#420]
Hello,

I need to transfer a user property with an event to amplitude. This property is Platform, it's about from what device's platform the event was sent. For instance, it could be an android and ios.
This property is necessary to sort events in Amplitude by the platform.

How to achieve this?

As you see, adjust send a lot of additional data to amplitude:
![Screenshot 2020-01-29 19 39 17](https://user-images.githubusercontent.com/1070647/73378163-3996be80-42d1-11ea-813b-3a402a66cfaa.png)

But for some reason, not a platform...
![Screenshot 2020-01-29 19 38 58](https://user-images.githubusercontent.com/1070647/73378209-4a473480-42d1-11ea-8ba4-bcbf1be4280b.png)

**Comment by nonelse** [comment]
Hi @oxied, thanks for the question, but this seems to be more related with our product as a whole, than with the sdk in particular. 
Please send your question to your dedicated account manager, in case you have none, please email it to support@adjust.com
