### ISSUE TITLE
New install referrer, how to use?

### ISSUE THREAD

**Issue by abbath0767** [adjust/android_sdk#422]
I see in your project pocket `com.adjust.sdk.play` with class `InstallReferrer` which uses the "new" method of logging installations instead of the old. But when I tried to find places to use it, I didn't find anything, nor did I find a way to use it in the documentation.

Please tell us how you can safely switch to the new method? Even if I copy and use the code of the above class I will need to disable the old one somehow.

**Comment by abbath0767** [comment]
I found `package com.adjust.sdk.InstallReferrer` with reflection creation instance of `com.android.installreferrer.api.InstallReferrerClient`. I debug, test and all works fine. Sorry for thrash issue

**Comment by mina-zaki** [comment]
@abbath0767 
I am also missing a way how to test it. Can you please clarify how to test that it is working as expected

**Comment by uerceg** [comment]
Hi @mina-zaki 

You can find simple instructions how to check if integration is fine in this [comment](https://github.com/adjust/android_sdk/issues/410#issuecomment-570557920).

Let us know if you have any further doubts.

Cheers
