### ISSUE TITLE
`android.permission.INSTALL_PACKAGES` is required?

### ISSUE THREAD

**Issue by sakebook** [adjust/android_sdk#424]
I am confused.
In the [SDK documentation](https://github.com/adjust/android_sdk#google-play-store-intent), `android.permission.INSTALL_PACKAGES` is required, but in the [Android documentation](https://developer.android.com/reference/android/Manifest.permission#INSTALL_PACKAGES), it is `Not for use by third-party applications`.

Is it OK to use `android.permission.INSTALL_PACKAGES`?

**Comment by shashanksu** [comment]
If you are still using old Google Play Store `INSTALL_REFERRER` intent with a broadcast receiver (which is not advisable now), then **only** it is required to have that permission.  But as mentioned in the [SDK documentation note](https://github.com/adjust/android_sdk#google-play-store-intent) it is going to deprecate.  

So now you should use [Google Play Referrer API](https://github.com/adjust/android_sdk#google-play-referrer-api) and where you **don't require** the declaration of receiver and its permission `android.permission.INSTALL_PACKAGES`.

**Comment by sakebook** [comment]
Thank you for quick reply!

I understood. I will use Google Play Referrer API and delete receiver in my app :)
