### ISSUE TITLE
Deep link redirect navigation blocked by browser

### ISSUE THREAD

**Issue by tobi512** [adjust/android_sdk#427]
Hi there, 
we experience a strange problem with deep link redirects from Adjust that are blocked by the browser (especially Chrome and Chromium-based browsers) on the device. Console log: `Navigation is blocked: intent://ourDeepLink/someId?adjust_reftag=<reftag>#Intent;scheme=ourAppScheme;S.market_referrer=adjust_reftag;end`

Right now, deep links only work correctly when the browser is open in the background on the device, otherwise we get the `navigation is blocked` and nothing happens, which basically makes deep links useless for our needs. Now, there are a lot of threads/issues about this problem in other contexts (e.g. authorization via OAuth2 and redirect back to app) but we haven't found any for the redirect of deep links. 

Since the redirect happens on your server side (https://eqjg.adj.st/ourDeepLink etc.) we have no way to fix anything on our side here, so could you please have a look at the problem (if necessary also together with your backend team)?

Additional information: problem occurs with current Chrome (v80.x) and doesn't occur with current Samsung Browser (v10.x) with is based on an older version of Chromium.

Thanks in advance!

**Comment by sletthaug** [comment]
Hi there

Thank you for bringing this to our attention, we are investigating on our end.

**Comment by jozefchutka** [comment]
subscribed, I have the same issue with chrome 81 on android

**Comment by sletthaug** [comment]
Hi @jozefchutka, can you provide some more details on when you are seeing this? What exactly is being clicked in this case?

**Comment by jozefchutka** [comment]
Hi @sletthaug its being validated, but seems the issue is on chrome side, more details here https://bugs.chromium.org/p/chromium/issues/detail?id=1088090

**Comment by sletthaug** [comment]
@jozefchutka 
So to be clear, it is not an Adjust tracker URL that is being clicked in this case, but it rather seems to be across the board when using intent in Chromium 81?

**Comment by jozefchutka** [comment]
most likely yes

**Comment by WorkmaiEric** [comment]
Subscribed, same issue here.

**Comment by sletthaug** [comment]
Hey @WorkmaiEric, as per the link @jozefchutka posted above, it seems like this happens because there are more than one app which can handle the content which is being clicked.

When I try to reproduce this using our own Adjust Insights app, everything works as expected. 
I click a multiplatform universal link from Slack, choose to open the link with Chrome, and am taken into the Android app. This is without having Chrome open in the background already.

Can you please walk me through exactly how to reproduce the issue as you see it?

**Comment by WorkmaiEric** [comment]
Hey @sletthaug the way I reproduce this issue is input the URL directly inside chrome and try to visit the URL. I have made sure on the device there is only one of this app that is installed. The page will just be blank for me without any redirecting

If I clicking the link in Facebook/Messager or in another chatting app, the jumping and redirecting works as intended. Just when trying to access the URL directly in chrome

**Comment by sletthaug** [comment]
@WorkmaiEric , this is actually not the same issue as described by the others in this thread. Please reach out to your company's Adjust Technical Account Manager in order to have them help you with this issue. It will then be escalated to me as required by the Technical Account Manager.

**Comment by rajib-coder** [comment]
> Hi there,
> we experience a strange problem with deep link redirects from Adjust that are blocked by the browser (especially Chrome and Chromium-based browsers) on the device. Console log: `Navigation is blocked: intent://ourDeepLink/someId?adjust_reftag=<reftag>#Intent;scheme=ourAppScheme;S.market_referrer=adjust_reftag;end`
> 
> Right now, deep links only work correctly when the browser is open in the background on the device, otherwise we get the `navigation is blocked` and nothing happens, which basically makes deep links useless for our needs. Now, there are a lot of threads/issues about this problem in other contexts (e.g. authorization via OAuth2 and redirect back to app) but we haven't found any for the redirect of deep links.
> 
> Since the redirect happens on your server side (https://eqjg.adj.st/ourDeepLink etc.) we have no way to fix anything on our side here, so could you please have a look at the problem (if necessary also together with your backend team)?
> 
> Additional information: problem occurs with current Chrome (v80.x) and doesn't occur with current Samsung Browser (v10.x) with is based on an older version of Chromium.
> 
> Thanks in advance!

**Comment by rajib-coder** [comment]
He

**Comment by uerceg** [comment]
In case any assistance is still need, feel free to comment/reopen or send email to support@adjust.com referencing this issue. Cheers.
