### ISSUE TITLE
Migration guide link broken in release 4.20.0

### ISSUE THREAD

**Issue by vashisthg** [adjust/android_sdk#429]
Migration guide link in release 4.20.0 https://github.com/adjust/android_sdk/releases/tag/v4.20.0 is broken. Link -> https://github.com/adjust/android_sdk/blob/master/doc/english/migrate.md

**Comment by uerceg** [comment]
Hey @vashisthg 

Nice catch, thanks for reporting! It's fixed now.

Cheers!
