### ISSUE TITLE
ReferenceError: AdjustBridge is not defined

### ISSUE THREAD

**Issue by oldman-kim** [adjust/android_sdk#433]
I applied adjust sdk on the app and webpages to track event.

But when the function that tracks adjust events is called I get this error
ReferenceError: AdjustBridge is not defined

I copied three js files to the web server and it looks successfully imported  : 
adjust_event.js
adjust_config.js
adjust.js

I cannot find any reference for AdjustBridge in those js files.

How can I fix this error?

**Comment by uerceg** [comment]
Hi @oldman-kim 

Did you complete the steps from [README](https://github.com/adjust/android_sdk#qs-basic-setup-web) in order to set up the bridge inside of your native part of the app?

**Comment by oldman-kim** [comment]
Hi @uerceg 
I found reference of AdjustBridge at opener.AdjustBridge. 

So I’m gonna close this issue.
Thanks.
