### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void com.adjust.sdk.OnAttributionChangedListener.onAttributionChanged(com.adjust.sdk.AdjustAttribution)"

### ISSUE THREAD

**Issue by littlelittlefox** [adjust/android_sdk#437]
java.lang.AbstractMethodError: abstract method "void com.adjust.sdk.OnAttributionChangedListener.onAttributionChanged(com.adjust.sdk.AdjustAttribution)"
        at com.adjust.sdk.ActivityHandler$39.run(ActivityHandler.java:1263)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:167)
        at android.app.ActivityThread.main(ActivityThread.java:7145)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

my app crashed unexpectedly, and logcat shows the exception, any help would be great

**Comment by littlelittlefox** [comment]
this only happens when the app is launched for the first  time

**Comment by uerceg** [comment]
Hi @littlelittlefox

Which SDK version are you using? Are you building native Android app or maybe with some non native platform?

**Comment by littlelittlefox** [comment]
Hi @uerceg I use the version 4.18.3, I import the SDK to Unity and build with it

**Comment by uerceg** [comment]
Are you adding Unity SDK from [releases](https://github.com/adjust/unity_sdk/releases) page as `.unitypackage`? Can you give latest SDK version a shot and check if you are facing the same issue?

**Comment by littlelittlefox** [comment]
The third-party SDK I use uses adjust, and the SDK didn't init adjust before use it, which lead to this exception.
`AdjustConfig config = new AdjustConfig(this, appToken, environment);
         Adjust.onCreate(config);`

**Comment by uerceg** [comment]
@littlelittlefox Thanks for the update. If it's okay with you to share information, what's that 3rd party SDK you use which uses Adjust SDK?

**Comment by littlelittlefox** [comment]
it's an undisclosed SDK for third-party login.
