### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.eventToken = eventToken'

### ISSUE THREAD

**Issue by mateusgomesti** [adjust/android_sdk#442]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/35661150/81433809-8a714b00-913b-11ea-8a3f-42caa5595b44.png">

I am running in debug mode on the iOS emulated, I have already reinstalled the app, installed pod install, reinstalled dependencies and got no results.

can anybody help me? I recently closed the contract.

Steps:
1. install dependence with: yarn add react-native-adjust --save
2. Add line in Podfile:   pod 'react-native-adjust', :path => '../node_modules/react-native-adjust'
3. Entrypoint.js file in my project add: 
`import { Adjust, AdjustConfig } from 'react-native-adjust';`

and

```
const adjustConfig = new AdjustConfig('{multiplataformKey}', AdjustConfig.EnvironmentSandbox);
    Adjust.create(adjustConfig);

```

```
  componentWillUnmount() { // C
    Adjust.componentWillUnmount();
  }
```

4. LoginView.js add:
```
import { AdjustEvent } from 'react-native-adjust';
```

```
  renderFacebookLogin = () => (
    <Icon.Button
      onPress={() => {
        AdjustEvent(
          'kmii48'
        )
        this.fbLogin
      }}
 >
```

"react-native-adjust": "^4.21.0",
"react": "16.9.0",
"react-native": "0.61.2",

**Comment by uerceg** [comment]
Replaced by https://github.com/adjust/react_native_sdk/issues/87.
