### ISSUE TITLE
Deferred has problem in google play

### ISSUE THREAD

**Issue by msoltanian** [adjust/android_sdk#446]
hi,
I use adjust referrer and when my application is installed ,adjust deep link works correct.
but when application in not installed and i open adjust deep link ,it redirect to google play and when the application is installed  i click on open button and app opened but deep link does not work.
have you idea to fix that issue?

**Comment by RahulTalabat** [comment]
Hi, am also facing the same issue previously it was working fine. now after installing the app from the google play the differed deep link callback is not triggering config.setOnDeeplinkResponseListener { 
}
only config.setOnAttributionChangedListener callback is triggering.even we deleted the gps_aid form the adjust console. someone can help on this.

**Comment by ugi** [comment]
Hey guys,

Can you do your test with debug build of your app which has SDK set to sandbox mode and log level to verbose and send over the logs to check what's happening? Feel free to omit any sensitive information from the logs.

Cheers

**Comment by erdincozden** [comment]
Hi,
I'm dealing with the same problem. For test; I am clicking link and open google play. Then install app but setOnDeeplinkResponseListener not triggered. Best,

**Comment by uerceg** [comment]
Hey guys. Sorry for delay on this one. @erdincozden pretty much what I mentioned in comment from above - is there any chance to get verbose logs from your test run?

Also, make sure that before you run your test you:

1. Uninstall app from your test device.
2. Forget your device from testing console in Adjust dashboard.

Cheers

**Comment by uerceg** [comment]
In case this is still an issue for you and you have additional questions, feel free to comment/reopen. Cheers.
