### ISSUE TITLE
Confirm support for install referrer library 2.0

### ISSUE THREAD

**Issue by dlew** [adjust/android_sdk#447]
Android's install referrer lib got updated to 2.0 recently: https://developer.android.com/google/play/installreferrer/release-notes#2_0

Before updating that dependency, I wanted to make sure that Adjust wouldn't have any issues with it. (I don't have any evidence of it failing atm, but I'd rather be cautious about this.)

**Comment by uerceg** [comment]
Hi @dlew 

That's actually interesting information (that you are not facing any issue) since we got [report](https://github.com/adjust/android_sdk/issues/402#issuecomment-654024088) that some users do. 

We also managed to reproduce this on our end and are in touch with Google to see what's up. 

For now, I would advise against updating until we clear things up and see what's happening. 

Will keep you posted.

Cheers

**Comment by dlew** [comment]
Oh, let me clarify - I hadn't even tried it yet. It would not surprise me if it fails, I just wanted to double-check here before I even launched it.

**Comment by uerceg** [comment]
Ah, okay. 👍 Yeah, just hold up for a bit until we clarify the situation and then we'll all know how to proceed.

**Comment by tmtrademarked** [comment]
And because nothing is ever simple - it looks like Google may have released 2.1 yesterday. Not sure if that changes the story here, but worth pointing out. :-)

**Comment by uerceg** [comment]
Yeah, I think they will come up with a patch version which fixes the issue. @tmtrademarked where did you see the 2.1 update?

**Comment by uerceg** [comment]
Ah, spotted on our end as well. Yeah, we can confirm that 2.1 version fixes the issue and feel free to use that version (not 2.0).

In case you have any further questions, feel free to comment/reopen.

Cheers

**Comment by calvarez-ov** [comment]
Would it be possible to update the README to refer to version 2.1 of the install referrer?

**Comment by uerceg** [comment]
Sure thing. We are in theory agnostic towards version being used at this moment (except versions which did cause issues and got fixed which I think are 1.1 and 2.0), but we'll update the README to state the last version of install referrer library. :+1: Will ping you in here once updated.

**Comment by uerceg** [comment]
@calvarez-ov Done.
