### ISSUE TITLE
How to get the campaign name when click to the deeplink generated by Deeplink Generator?

### ISSUE THREAD

**Issue by tqnst** [adjust/android_sdk#451]
Hi,

I have generated a deeplink by Deeplink Generator as below:
https://app.adjust.com/abcxyz?deep_link=myschema%3A%2F%2F%2Fmypath%3Febcampaignid%3D1132&campaign=JustForTest
After share this link to Twitter, open the Twitter app and click to this link => It opened my app => On my app,  I received the deeplink data by calling getIntent().getData()
But I have no idea to get the campaign=JustForTest attribute.
How to get this campaign name?
Is it possible on Android native app?

Thank in advance

**Comment by uerceg** [comment]
Hi @tqnst 

Sorry for a big delay in replying to this one. Unfortunately, this questions is a bit out of the scope for us who are replying in here. Our support team should definitely be able to provide you with answer to this question. So I'd advise to either ping your dedicated account manager if you have one, or if not, feel free to send email to support@adjust.com and reference this issue in the email.

Cheers
