### ISSUE TITLE
Deferred Deeplink not working, Standard deeplink case not working with Brave Browser.

### ISSUE THREAD

**Issue by luiscurini** [adjust/android_sdk#456]
Hi! 

I'm using the latest sdk version 4.24.1 and I encounter 2 problems while using deep links. 

1. Deferred deep link not working. I used the deep link generator in the dashboard to point to a different screen in the app than the main screen, If I don't have the app installed I get successfully redirected to the playstore. However once I click open the app, the sdk doesn't seem to get the deep link and does't do anything. I added some logging by using:

`setOnDeeplinkResponseListener { deeplink ->
                Timber.e("launchReceivedDeeplink: $deeplink")
                true
            }`

but it never gets called. I attach here the logcat of the app in Sandbox mode and Verbose logging. 
[Logcat.txt](https://github.com/adjust/android_sdk/files/5402324/Logcat.txt)

If I test the  deep link while having the app installed, it works without problems. 

2. Cannot open a deep link while having Brave Browser as the default browser. With the app installed and the browser set to Brave, when one clicks on the deep link, it opens the playstore and the app page. After clicking on open, nothing happens.

**Comment by uerceg** [comment]
Hi @luiscurini 

From logs I see that you're not performing actual install of the app (what Adjust platforms defines as an install). You need to:

1. Uninstall your app.
2. Forget your app from testing console.
3. Re-run your testing scenario.

After forgetting device, session which SDK tracks will actually be treated as install and in this scenario, backend will deliver deferred deep link into the SDK (if found any).

Let us know if it worked and feel free to ping in case you have any other questions.

Cheers

**Comment by luiscurini** [comment]
Hi,

I was performing an install and I thought the device was already forgotten. This works, thanks!
