### ISSUE TITLE
Unique event tracking not working

### ISSUE THREAD

**Issue by GorG1993** [adjust/android_sdk#457]
Hi there. I have defined an Event inside the Adjust Dashboard and marked it as Unique. 
Inside the code I build my Event as such: 

val adjustSubscriptionEvent = AdjustEvent(ADJUST_GOOGLE_SUBSCRIPTION_SALE_SUCCESSFUL.id).apply {
            setOrderId("{$orderId}")
            setRevenue(amount, currency)
            addPartnerParameter(PRODUCT_PARAMETER_KEY, ProductType.SUBSCRIPTION.toString())
            addPartnerParameter(PRODUCT_DURATION_PARAMETER_KEY, duration.toString())
        }
        Adjust.trackEvent(adjustSubscriptionEvent)

orderId is an unique string coming from Google Pay. No matter what value I'm setting as the orderId
I get the following error in the console

'Event request failed (Ignoring event, earlier unique event tracked)'

I'm using version 4.24.1 of the Adjust Android SDK.

**Comment by XTJX21X** [comment]
Event/track/not/working/tracking/bug

**Comment by uerceg** [comment]
Hi @GorG1993 

In this setup you're having, there are two things which can cause event not to be tracked:

1. Uniqueness of the event which you have set in dashboard.
2. Fact that you are setting order ID on the event.

If event is marked as unique, then event with that token can only be tracked once per install. In case you wanna track that event again, you need to make new install of your app and if you plan to do that on device where you already installed your app, you need to perform following:

1. Remove app from the device.
2. Forget your device from Adjust testing console.
3. Reinstall your app and track unique event which should be successfully tracked at this moment.

You are also setting order ID on your event which is used for feature called [revenue deduplication](https://github.com/adjust/android_sdk#et-revenue-deduplication). Whenever you set order ID on even which is being tracked, our SDK will internally keep track of these order IDs and will keep list of last 10 order IDs. If you ever attempt to track an event with order ID which our SDK recognises from list of last 10 it knows of, even tracking will never happen.

In code snippet from above, if you are setting order ID always to be the same string (`"{$orderId}"`), then SDK will track just first even with that order ID and the subsequent events with same order ID value will not be tracked.

In case you have any further question(s) on the topic, feel free to ping.

Cheers

**Comment by uerceg** [comment]
In case you still have some question(s) about this, feel free to comment/reopen. Cheers.
