### ISSUE TITLE
Deferred not working in Adjust Product Environment 

### ISSUE THREAD

**Issue by wangjianpeng** [adjust/android_sdk#459]
Hi,
  I test with adjust sandbox environment , deferred deeplink works well, but When I set it to adjust Product environment , The deferred deeplink does not work. Please help me how to solve this problem ?

**Comment by uerceg** [comment]
HI @wangjianpeng 

Deferred deep linking as a mechanism has absolutely nothing to do with SDK environment you are testing it with. Did you try to uninstall an app and forget it from testing console prior to running test in production?

**Comment by wangjianpeng** [comment]
Hi,
       Sorry to reply later.
       The problem was solved now,  "Anonymous IP" fraud filter was enabled in the dashboard ,so can’t receive deferred deep linking  through VPN network.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Uglješa Erceg<mailto:notifications@github.com>
发送时间: 2020年12月10日 16:53
收件人: adjust/android_sdk<mailto:android_sdk@noreply.github.com>
抄送: penney<mailto:wjpdeveloper@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [adjust/android_sdk] Deferred not working in Adjust Product Environment (#459)


HI @wangjianpeng<https://github.com/wangjianpeng>

Deferred deep linking as a mechanism has absolutely nothing to do with SDK environment you are testing it with. Did you try to uninstall an app and forget it from testing console prior to running test in production?
