### ISSUE TITLE
No events can be seen in the dashboard

### ISSUE THREAD

**Issue by overpas** [adjust/android_sdk#460]
Hello.
I'm using Adjust SDK v4.24.1, install referrer v2.1, Google ads identifier v17.0.0, my app is targeting api level 30. I've followed the guide in readme, but couldn't manage to see any sandbox environment events in the dashboard (see image)
![image](https://user-images.githubusercontent.com/31508068/99373656-b895cb80-28d2-11eb-9e43-b7bfa3ab6e05.png)
Could you please help me to fix this issue?

**Comment by uerceg** [comment]
HI @overpas 

And sorry for delay in responding. Can you share logs with us when you run SDK in sandbox environment and have log level set to verbose? Just to make sure that SDK is sending traffic properly to our backend first.

**Comment by uerceg** [comment]
In case issue is still present, feel free to reopen/comment. Cheers.
