### ISSUE TITLE
4.26.2 is not available on maven

### ISSUE THREAD

**Issue by dawidhyzy-ifolor** [adjust/android_sdk#479]
After updating the version to 4.26.2 I get: `Failed to resolve: com.adjust.sdk:adjust-android:4.26.2`
It's not shown here as well: https://mvnrepository.com/artifact/com.adjust.sdk/adjust-android.

**Comment by uerceg** [comment]
Hi @dawidhyzy-ifolor 

Oh wow. Thanks for reporting. Not sure how this actually didn't end up being released on Maven. 😱 Should be live now, can you re-check?

Cheers

**Comment by dawidhyzy-ifolor** [comment]
Yes, it works now :-) Thanks!
