### ISSUE TITLE
Background location access:

### ISSUE THREAD

**Issue by prady32** [adjust/android_sdk#484]
Hi Our Application has been rejected for Background location access by play store.
We currently use Adjust SDK 4.24.1 in our application.
Does Adjust use Background location ? We have verified in our project and found no other sdk is using Background location. Can you please confirm from your end

Thanks,
Pradeep

**Comment by uerceg** [comment]
HI @prady32 

Adjust SDK doesn't use location services at all, neither in foreground nor background.

Cheers
