### ISSUE TITLE
Adjust SDK fails to track session (Connection reset)

### ISSUE THREAD

**Issue by code-schreiber** [adjust/android_sdk#497]
I'm having an issue where the app is having no internet problems, the browser on the device is also not having internet problems, but the Adjust SDK is unable to start because of a connection problem that is usually a sign of a device being offline. 
Any hints on where to look closer?

```
    	api_level        30
    	device_name      sdk_gphone_x86_arm
    	device_type      phone
    	environment      sandbox
    	event_buffering_enabled 0
    	gps_adid_src     service
    	headers_id       3
    	initiated_by     sdk

...

E/Adjust: Failed to read response. (Connection reset)
E/Adjust: Failed to get attribution (Connection reset)
E/Adjust: Failed to track session. (Request failed: java.net.SocketException: Connection reset) Will retry later
```

**Comment by uerceg** [comment]
Hi @code-schreiber,

Is there any chance that you might behind some firewall or proxy on the network your device / emulator is connected to? Can you retry same test on physical device connected on mobile internet to double check if you are experiencing the same issue?

**Comment by code-schreiber** [comment]
Thanks for your response, this is a problem that happens both on an emulator and also on a device, but they are both on the same network so a firewall/proxy could we're not aware of could explain the issue.

Any other places you would recommend looking at?

**Comment by uerceg** [comment]
@code-schreiber 

Sorry for delay in replying. Hm. Is there any chance for you to test with real device using mobile internet? Just to double check is that scenario actually making things work well.

**Comment by uerceg** [comment]
In case this is still an issue for you, feel free to comment/reopen.
