### ISSUE TITLE
Adjust Sdk Util TelephonyManager getNetworkType() error on Api level 30

### ISSUE THREAD

**Issue by umitrsm** [adjust/android_sdk#498]
This method was deprecated in API level 30.
use getDataNetworkType() instead of getNetworkType() in Util.java file.

Source : https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkType()

**Comment by uerceg** [comment]
Hi @umitrsm,

Thanks for reporting this, we'll look into addressing this in our next releases. Will keep you posted.

**Comment by shashanksu** [comment]
Hi @umitrsm,

We are already using [getDataNetworkType()](https://github.com/adjust/android_sdk/blob/5bf71ebf18f3e92d52225df87eb0ed1656e1a038/Adjust/sdk-core/src/main/java/com/adjust/sdk/Util.java#L665) for API level 30 & above.  

Is this not enough or you mean something else?  Feel free to point out exact line in the code, thanks.

**Comment by uerceg** [comment]
@umitrsm In case you have any further questions or comments on this topic, feel free to comment /reopen. Cheers.
