### ISSUE TITLE
Deferred deeplink doesn't work on my device

### ISSUE THREAD

**Issue by ajacquelin** [adjust/android_sdk#506]
Hello,
following the steps described here: https://github.com/adjust/android_sdk/issues/360#issuecomment-439354884

the deferred doesn't work on one of my phones. But it works on emulator and the other devices.
Do you know why ? Is it because my device was refurbished?

**Comment by uerceg** [comment]
👋 Hi @ajacquelin 

Did you also check [this setting](https://github.com/adjust/android_sdk/issues/360#issuecomment-605427603) for tracker you're using when testing?

Your device being refurbished shouldn't really have anything to do with this.

**Comment by uerceg** [comment]
In case assistance is still needed, feel free to comment / reopen.
