### ISSUE TITLE
Adjust dashboard is not showing triggered event for android 

### ISSUE THREAD

**Issue by aemonjawaid-10p** [adjust/android_sdk#507]
Hi,

We have created different events in Adjust app and used those events in Android app to track them.

These events are shown on Android Studio logs when triggered but are not appearing on App Adjust Dashboard. While iOS events are appearing on App Adjust Dashboard.

We are using Sandbox mode and checked App token id and event id are correct.

**Comment by uerceg** [comment]
Hi @aemonjawaid-10p 

Just to double check - are you checking sandbox traffic on dashboard (default view shows production traffic) for both of your apps?

**Comment by aemonjawaid-10p** [comment]
By selecting sandbox mode , its working. Thank you
