### ISSUE TITLE
LogLevel.SUPRESS doesn't avoid log messages from the Android Adjust SDK 

### ISSUE THREAD

**Issue by code-schreiber** [adjust/android_sdk#517]
While trying to get more focused logs, I've seen that the Android Adjust SDK still prints logs event when explicitly trying to suppress them like this:

```kotlin
import com.adjust.sdk.Adjust
import com.adjust.sdk.AdjustConfig
import com.adjust.sdk.LogLevel

val environment = AdjustConfig.ENVIRONMENT_SANDBOX
val adjustConfig = AdjustConfig(context, appToken, environment).apply {
    setLogLevel(LogLevel.SUPRESS)
}
Adjust.onCreate(adjustConfig)
```

Sadly, I still see these warnings in Logcat, what am I forgeting? 🤔 
```
com.example.android W/Adjust-pool-6-t: type=1400 audit(0.0:2558): avc: denied { read } for name="tcp" dev="proc" ino=4026532053 scontext=u:r:untrusted_app:s0:c127,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.example.android
com.example.android W/Adjust-pool-6-t: type=1400 audit(0.0:2559): avc: denied { read } for name="drivers" dev="proc" ino=4026531852 scontext=u:r:untrusted_app:s0:c127,c256,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=0 app=com.example.android
com.example.android W/Adjust-pool-6-t: type=1400 audit(0.0:2561): avc: denied { read } for name="tcp" dev="proc" ino=4026532053 scontext=u:r:untrusted_app:s0:c127,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.example.android
com.example.android W/Adjust-pool-6-t: type=1400 audit(0.0:2562): avc: denied { read } for name="drivers" dev="proc" ino=4026531852 scontext=u:r:untrusted_app:s0:c127,c256,c512,c768 tcontext=u:object_r:proc_tty_drivers:s0 tclass=file permissive=0 app=com.example.android
com.example.android W/Adjust-pool-6-t: type=1400 audit(0.0:2564): avc: denied { read } for name="tcp" dev="proc" ino=4026532053 scontext=u:r:untrusted_app:s0:c127,c256,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=com.example.android
...and many more similar logs...
```

**Comment by uerceg** [comment]
Hi @code-schreiber,

Sorry for pretty massive delay on this one. Thank you for reporting this. Are you maybe using Adjust signature library as well next to the Adjust SDK?

**Comment by code-schreiber** [comment]
> Hi @code-schreiber,
> 
> Sorry for pretty massive delay on this one. Thank you for reporting this. Are you maybe using Adjust signature library as well next to the Adjust SDK?

Yes, I believe that was the case. But it has been 2 years since I reported it so my confidence levels are not high.

---

For reference, this was the response we got internally from Adjust:

Hi, Thanks for your reply!   
I wouldn't expect a fast resolution on this, since the logs are not produced by our SDK, but rather by a 3-d party service in responce to an interaction attept with our SDK, but we'll make sure to update the thread on Github once there is one.
Thank you!   

Best,  
Alex Tomenko
Technical Account Manager

**Comment by uerceg** [comment]
Tank you for getting back to us nonetheless. 🙏

Yes, I think that this in particular should not be related to the logic inside of the SDK, but inside of the signature library. In case this is still something that annoys you (or anyone else who might be reading this conversation), feel free to discuss further in here and reopen if needed. I'll close it for now.

Thank you one more for the follow up and have a great holidays season ahead. 🎄
