### ISSUE TITLE
Failure to read Huawei Install Referrer

### ISSUE THREAD

**Issue by aovcharov** [adjust/android_sdk#518]
When installing our app on a Huawei device with Huawei Mobile Services and App Gallery, Adjust SDK produces the following in the logs:
`InstallReferrerHuawei fail to read referrer for package [our package name] and content uri [content://com.huawei.appmarket.commondata/item/5]`
and sdk_click event data has no line `source install_referrer` in it.

If the device has Google Services installed, Adjust seems to track installation correctly, logging `source install_referrer` in sdk_click and printing these lines:
```
installReferrer: utm_source=google-play&utm_medium=organic, clickTime: 0, installBeginTime: 0
installVersion: null, clickTimeServer: 0, installBeginServer: 0, googlePlayInstant: false
Install Referrer read successfully. Closing connection
```

Tested this on two Huawei devices, one equipped only with Huawei Services, the other with both Huawei and Google. In both cases Adjust warned that it failed to read Huawei referrer.
We are currently using Adjust SDK 4.28.2 in production, but with the latest version 4.28.6 the issue still persists.

**Comment by shashanksu** [comment]
Hello @aovcharov,

The error says, there is no referrer available for the given package.  Did you install the app from Huawei AppGallery v10.4+ or it was just a debug build install case?  If otherwise, the behaviour is as expected.  Also, since referrer is not available, hence no corresponding sdk_click.

Let us know if you have any further issues/doubts, thanks.

**Comment by aovcharov** [comment]
Hi @shashanksu,

Thank you for your quick reply. Indeed, I tested this with a debug build, as we disable logging in release builds. The reason we started investigating is that, according to our data, at least some AppGallery installations weren't tracked by Adjust.

Again, thanks for your help! Feel free to close the issue.
