### ISSUE TITLE
AdjustPlayStoreSubscription accept only integer price

### ISSUE THREAD

**Issue by LouisYubo** [adjust/android_sdk#522]
I want to setup subscription tracking (https://github.com/adjust/android_sdk#subscription-tracking) but only integers are accepted as price. Why doesn't the constructor accept double?  like AdjustEvent#setRevenue ? 

```
public AdjustPlayStoreSubscription(final long price,
                                       final String currency,
                                       final String sku,
                                       final String orderId,
                                       final String signature,
                                       final String purchaseToken)
```

**Comment by uerceg** [comment]
Hi @LouisYubo 

If you check that chapter in the README, price is linked with Android API where you should be able to get the price of the purchased item in micros (long value). Is there something preventing you from passing value of that parameter when creating subscription object?

**Comment by LouisYubo** [comment]
Hi,
Thanks for you answer, I misread

**Comment by uerceg** [comment]
All good. In case you have any other questions on this topic, feel free to comment / reopen. Cheers.
