### ISSUE TITLE
[Question] Multiple sources push token handling

### ISSUE THREAD

**Issue by imort** [adjust/android_sdk#524]
As [documentation](https://github.com/adjust/android_sdk#af-push-token) says, we have the method to update push token.
Imagine universal application distributed in multiple app stores with several implementations of Push SDKs. Is that correct to set first available token when we fetched many of them through SDKs? What happens if we set another token (from totally different push service) after first one was expired or disabled by user?

**Comment by imort** [comment]
Yep, it totally answers it. Thanks for the quick response

**Comment by uerceg** [comment]
In case you have any other questions, feel free to comment / reopen. Cheers.
