### ISSUE TITLE
Android 12 + Deep Links doesn't work

### ISSUE THREAD

**Issue by michaelrigadev** [adjust/android_sdk#525]
Hello! We faced with problem on android 12 with deep links, app doesn't open, each time open only browser. According google documentation we [need verify links](https://developer.android.com/training/app-links/verify-site-associations). If I don't mistake we need add https://domain.name/.well-known/assetlinks.json but how
Could you help with this problem please.

**Comment by uerceg** [comment]
Hi @michaelrigadev,

Sorry for delay in replying. In theory, making app links to work with your app and domain should be done by you, nothing really we can do on our end to make that happen. Google docs you referenced are pretty detailed a bit later on the page on how one should generate association file, verify it and where exactly on your domain that file should be hosted. Did you follow that guide to upload file to suggested location on your website?

**Comment by k-farhan** [comment]
Hey @michaelrigadev, did you resolve this issue? If yes can you share how you did that?

**Comment by uerceg** [comment]
Since the topic seems not related to Adjust SDK directly, I will close this ticket. Would also be curious to hear the answer to question from above. Feel free to comment / reopen if needed.

**Comment by muxbert** [comment]
Hey @uerceg

Below is the error message from google, is there a way to customize this domain that Adjust generates, where do we upload the assetLinks.json file?

![Screen Shot 2022-12-26 at 9 35 11 AM](https://user-images.githubusercontent.com/60647004/209512811-cfa208fa-7bc8-4d1f-a667-f77e5005d71c.png)

**Comment by uerceg** [comment]
Hi @muxbert,

It is not currently supported to use Adjust iOS short universal links as app links in Android.

Cheers
