### ISSUE TITLE
Problem with Android 4.4 (API 19) using TLS1.0 by default

### ISSUE THREAD

**Issue by joaolucas95** [adjust/android_sdk#546]
Hi,

I'm having trouble setting up the Adjust SDK in an Android 4.4 device.

By default the device uses TLS1.0 so I get the following error:
`Failed to track session. (Certificate failed: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x63685108: Failure in SSL library, usually a protocol error`

I've tried forcing the usage of TLS1.2 by using a custom SSLSocketFactory but I get the error that the SDK is unsupported:
`
Response string: {"timestamp":"2022-07-27T15:25:23.527Z+0000","message":"Session failed (unsupported sdk)","error":"Session failed (unsupported sdk)"}`

Is there any way to configure this so that it works for API 19?

**Comment by uerceg** [comment]
Hi @joaolucas95,

Sorry for delay in responding. When it comes to TLS protocol, you did the right thing, since TLS1.0 is not supported by our backend at all. And when it comes to error message you are seeing, it should be because you are using unsupported Adjust SDK version (most probably SDK v3.X.Y). Which SDK version are you using?

**Comment by joaolucas95** [comment]
I'm already using v4.26.0

**Comment by uerceg** [comment]
Thank you for that info. And you are seeing the same error with 4.26.0 as well? If yes, would it be possible to reinstall your app with Adjust SDK being set to sandbox environment and log level to verbose, launch it and send over the SDK verbose logs (`Adjust` tag). Feel free to remove any sensitive data from logs.

**Comment by uerceg** [comment]
In case any further assistance is needed on this one, feel free to comment / reopen. Cheers.
