### ISSUE TITLE
Lacking documentation around setting up the Google Play Referrer API

### ISSUE THREAD

**Issue by Amokrane** [adjust/android_sdk#552]
Hello,

After following [the steps to setup the Google Play Referrer API](https://help.adjust.com/en/article/get-started-android-sdk), I noticed that the broadcast receiver [was still not capturing the referrer info](https://help.adjust.com/en/article/faqs-android-sdk). Then, I noticed that the [AdjustReferrerReceiver](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-core/src/main/java/com/adjust/sdk/AdjustReferrerReceiver.java) `BroadcastReceiver` wasn't declared  in the SDK's manifest file, but instead in the host applications (as shown [in the example apps](https://github.com/adjust/android_sdk/blob/859af505601f9a397afcd875c275d4bcc71cc25d/Adjust/example-app-java/src/main/AndroidManifest.xml#L20)). After declaring this `receiver` in our app's manifest file, it finally worked as expected.

Is there any reason why this step isn't documented at all? Or, is the broadcast receiver supposed to be registered programmatically? (though I don't see any reference to `registerReceiver` in the SDK).

Thank you.

**Comment by uerceg** [comment]
Hi @Amokrane,

Capturing install referrer information via broadcast receiver for `INSTALL_REFERRER` intent is deprecated by Google for several years already. I assume it still might be working, but that's not really suggest approach one should be using nowadays for accessing install referrer information. You should be following Google Play Referrer API path from the [docs](https://help.adjust.com/en/article/get-started-android-sdk#set-up-install-referrer). By using that approach, SDK will automatically obtain install referrer information upon initial launch and pass it to our backend. You can see this in verbose SDK logs when you run it in sandbox - SDK will send package named `sdk_click` with `source=install_referrer` and among other parameters, you'll also see the value of the install referrer under as a value of `referrer` parameter in that package.

Broadcast receiver for `INSTALL_REFERRER` intent is intended to be registered programmatically by you in case you want to use it (as described in [`INSTALL_REFERRER` intent](https://help.adjust.com/en/article/get-started-android-sdk#set-up-install-referrer) part). But like said, this approach has been deprecated for several years now and will probably be removed from our SDK in next major release.

In case you have any other questions, feel free to ask.

Cheers

**Comment by Amokrane** [comment]
@uerceg Thanks for your clear and quick response. In fact, we are using the latest Google Play Referrer API, and for some reasons I wrongly assumed that we would still need the `INSTALL_REFERRER` receiver for this to work.

So, I confirm that we have everything set-up for the Google Play Referrer API to work correctly. 

>. You can see this in verbose SDK logs when you run it in sandbox - SDK will send package named sdk_click with source=install_referrer and among other parameters, you'll also see the value of the install referrer under as a value of referrer parameter in that package.

How can I test a referrer flow in sandbox though? I know how to do it in production (by installing the app from this URL: `https://play.google.com/store/apps/details?id=<pkg>&referrer=utm_source%3Dtest_source%26utm_medium%3Dtest_mediuml%26utm_term%3Dtest_term%26utm_content%3Dtest_content%26utm_campaign%3Dtest_name`), however I am not sure how to test that flow with our debug build (sandbox environment), as it's not installable from the Play Store.

Any help would be appreciated.

Thanks :)

**Comment by hellosagar** [comment]
> Any help would be appreciated.

Steps to test on your debug build is
- Click on the link, which navigates to the play store ( but don't install the app from play store)
- Now, install the debug app from the android studio (Assusimg that SDK is running in  Sandbox environment)
- Check the logs

Lme know if it works.

**Comment by hellosagar** [comment]
> @uerceg Thanks for your clear and quick response. In fact, we are using the latest Google Play Referrer API, and for some reasons I wrongly assumed that we would still need the `INSTALL_REFERRER` receiver for this to work.
> 
> So, I confirm that we have everything set-up for the Google Play Referrer API to work correctly.
> 
> > You can see this in verbose SDK logs when you run it in sandbox - SDK will send package named sdk_click with source=install_referrer and among other parameters, you'll also see the value of the install referrer under as a value of referrer parameter in that package.
> 
> How can I test a referrer flow in sandbox though? I know how to do it in production (by installing the app from this URL: `https://play.google.com/store/apps/details?id=<pkg>&referrer=utm_source%3Dtest_source%26utm_medium%3Dtest_mediuml%26utm_term%3Dtest_term%26utm_content%3Dtest_content%26utm_campaign%3Dtest_name`), however I am not sure how to test that flow with our debug build (sandbox environment), as it's not installable from the Play Store.
> 
> Any help would be appreciated.
> 
> Thanks :)

Steps to test on your debug build is
- Click on the `referrer link`, which navigates to the play store ( but don’t install the app from the play store)
- Now, install the debug app from the android studio (Assusimg that SDK is running in a Sandbox environment)
- Check the logs

Lme know if it works.

**Comment by Amokrane** [comment]
Thanks for your help @hellosagar. Unfortunately, that doesn't work. I think this is expected because our debug build package name is different than the prod one (this allows us to have both a prod and debug build on the same device).

**Comment by Amokrane** [comment]
I was able to test the end-to-end flow by forcing the sandbox environment and verbose logging on the play store's beta channel.

Thanks all for your help.
