### ISSUE TITLE
WebBridge JavaScript files not bundled in library

### ISSUE THREAD

**Issue by aruh** [adjust/android_sdk#553]
### Description

I tried integrating the Adjust WebBridge in an app. I followed the steps detailed in the documentation: [Link](https://help.adjust.com/en/article/get-started-android-sdk).

I tried accessing the `Adjust` object from JavaScript as detailed in the [example in the documentation](https://help.adjust.com/en/article/get-started-android-sdk#web-view-sdk) and [the WebView example in this repository](https://github.com/adjust/android_sdk/blob/859af505601f9a397afcd875c275d4bcc71cc25d/Adjust/example-app-webbridge/src/main/assets/AdjustExample-WebView.html).

Both do the following to add the required `.js` files of the WebBridge:

```HTML
        <script type="text/javascript" src="adjust_event.js"></script>
        <script type="text/javascript" src="adjust_third_party_sharing.js"></script>
        <script type="text/javascript" src="adjust_config.js"></script>
        <script type="text/javascript" src="adjust.js"></script>
```

But when running the app and opening the WebView, the JavaScript Console prints that the file `adjust.js` and all the others can't be found.

From the examples, it seems that the Adjust `.js` files should be present at the root of the `/assets` folder of the apps APK. The Adjust documentation isn't clear on this, so this is an assumption.
I inspected the APK file of the app. There were not `adjust*.js` files in the `/assets` directory.

Given the previous assumption, it seems that the `.js` files should be delivered with the library artifact.

I looked at the [adjust-android-webbridge-4.31.1.jar](https://github.com/adjust/android_sdk/releases/download/v4.31.1/adjust-android-webbridge-4.31.1.jar) file. It does not contain an `/assets` folder. It seems to be missing.

It seems that the Gradle task [`sdk-plugin-webbridge:adjustWebBridgeAndroidJar`](https://github.com/adjust/android_sdk/blob/859af505601f9a397afcd875c275d4bcc71cc25d/Adjust/sdk-plugin-webbridge/build.gradle#L50`) is used to build the `.jar` file of the library. I checked out this repo and executed the task. The resulting `.jar` file does not include the assets.

The `adjustWebBridgeAndroidJar` task contains an instruction that evidently should copy the assets from an intermediate build folder into the created artifact, to create an `/assets` folder with the `*.js` files:

```gradle
    from('build/intermediates/library_assets/release/packageReleaseAssets/out/') {
        into('assets')
    }
``` 

I inspected the `build/` directory, and noticed, that the assets are at a different path: `build/intermediates/library_assets/release/out`.

So I changed the path to that one:
```gradle
    from('build/intermediates/library_assets/release/out/') {
        into('assets')
    }
```
I built the `*.jar` again and included it in my project - replacing the `webbridge-4.31.1` version.

**Results:**
* The `.*jar` file included an `/assets` folder that contained all the `*.js` files listed in the examples.
* The apps APK contained these `*.js` files in it's `/assets` folder.
* The WebView and AdjustWebBridge example I built could load the files and worked properly.

**Solution proposition:**
* Change the intermediate build path of the assets to include them in the library again.

It would also be cool, if the documentation could state, that the `*.js` files are included in the library. It wasn't clear where these files should come from, and them not being in the library, I wondered whether they have to be added manually to the `/assets` folder of the app.

---

### Example and test issues

There are an example and a test in this repository, that use the assets from the library. I didn't run them, thus I don't know whether they work properly or fail.
I suspect that they might be including the asset files correctly, because the include the library not as a library, but as a gradle project:

```gradle
    implementation project(':sdk-plugin-webbridge')
```

Therefore they might work, despite the fact that the released library `*.jar` is missing the `/assets`.

This would mean that they don't really integrate the library as the user would. Thus they can't really serve as an example nor do they test the library integration.

---

### Doubts

Is this assessment correct and is there really a bug? Did I miss something and the `*.js` files should be included differently?

---

### Workaround

For the meantime: Download the `*.js` files [from here](https://github.com/adjust/android_sdk/tree/v4.31.1/Adjust/sdk-plugin-webbridge/src/main/assets) and include them in the `/assets` folder of your app. Keep in mind that the files have to be updated when the Adjust Android SDK in the project is updated.

---

Thank you for your time 😊

**Comment by uerceg** [comment]
Hi @aruh 

And thank you so much for such a detailed and clear message. I'll try to keep my reply shorter. :)

- `Description` & `Example and test issues`: On spot. 👍 
- `Doubts`: So far indeed users of our web bridge were manually adding these files. So one could say that is not really a bug, but I definitely agree that it's also not the most user friendly approach either.
- `Workaround`: Like mentioned in bullet point above, that's how everyone is using web bridge so far.

We had an internal discussion about this ticket and we will try as of next web bridge releases to ship web bridge artifact as AAR with all the assets bundled inside. Will keep you posted and thank you one more time for bringing up this topic.

**Comment by uerceg** [comment]
Hey @aruh,

As of our [latest SDK update](https://github.com/adjust/android_sdk/releases/tag/v4.33.0), all the Javascript resources are now packed inside of web bridge AAR which we started to ship on Maven repo.

Feel free to give it a shot and in case you face any issue or if you have any other question, feel free to comment / reopen.

Cheers!
