### ISSUE TITLE
Attempt to read from field 'java.lang.String com.adjust.sdk.AdjustAttribution.trackerName' on a null object reference

### ISSUE THREAD

**Issue by G00fY2** [adjust/android_sdk#556]
We are using the latest Android Adjust SDK 4.32.0 and see 1500+ crashes (1M+ user base) in the last 30 days in Crashlytics:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.adjust.sdk.AdjustAttribution.trackerName' on a null object reference in method 'void com.adjust.sdk.webbridge.AdjustBridgeUtil$2.run()'
       at com.adjust.sdk.webbridge.AdjustBridgeUtil$2.run(AdjustBridgeUtil.java:117)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

From the source code I can not see an obvious flaw. Maybe it's a rare race-condition.

Would be nice if you could investigate and try to fix this issue.

I am happy to help if you need further information.

**Comment by uerceg** [comment]
Hi @G00fY2,

Thank you for reporting this. Trying to figure out where this might be coming from - are you using attribution getter inside of your web app (`Adjust.getAttribution()` method)?

**Comment by G00fY2** [comment]
Yes, we actually call `Adjust.getAttribution()` in `onCreate` of our application an in the `OnAttributionChangedListener` so in the `AdjustConfig` to pass attributes to Adobe.

**Comment by uerceg** [comment]
Hey @G00fY2,

Thank you for letting us know. We think we have identified what might be causing this on your end. We'll add a fix for this in our next release. Will keep you posted.

**Comment by uerceg** [comment]
@G00fY2,

Just one more follow up question. 

> Yes, we actually call Adjust.getAttribution() in onCreate of our application and in the OnAttributionChangedListener set in the AdjustConfig to pass attributes to Adobe.

☝️ Are you using this natively (and calling native `Adjust.getAttribution()` method or are you invoking `Adjust.getAttribution()` getter from your web app (by pinging our Javascript wrapper inside of the web bridge)?

**Comment by G00fY2** [comment]
We are call `Adjust.getAttribution()` directly in our Kotlin code (fully Kotlin app only with some webviews).

**Comment by uerceg** [comment]
Hm, that is actually pretty awkward. Direct usage of our native Android SDK should never cause [this method](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-plugin-webbridge/src/main/java/com/adjust/sdk/webbridge/AdjustBridgeUtil.java#L107-L137) mentioned in crash stack trace to be invoked. Only way how that method can be invoked is if:

- You are [setting attribution callback](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-plugin-webbridge/src/main/assets/adjust_config.js#L113) on `AdjustConfig` instance in Javascript (so from your web app). This use case scenario should not make you get a `null` for attribution value.
- Or if you are making a call to [attribution getter](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-plugin-webbridge/src/main/assets/adjust.js#L196), but again from Javascript within your web app. This use case scenario can make you get a `null` for attribution value (which is part that needs to be addressed in our next web bridge update).

But if you are not using any of the two things mentioned above, then I am absolutely puzzled what is causing these crashes in your app. 🤔

**Comment by G00fY2** [comment]
I digged through the Crashlytics logs and it looks like this crash only happens after the user navigated to a webview (so the call in the `onCreate` should not be the issue).

But inside our WebView we only use the `AdjustBridge` like this:
Initially we call
```kotlin
(webView.context.applicationContext as? Application)?.let { application ->
    AdjustBridge.registerAndGetInstance(application, webView)
}
AdjustBridge.setWebView(webView)
```
Once we leave the screen we call `AdjustBridge.unregister()`.

Not sure if the crashes can be related to the AdjustBridge?

**Comment by uerceg** [comment]
Thanks for all the additional infos. We'll check this thing a bit more in detail and try to see what might be causing this having your app setup in mind. But at the end of the day, reason for crash is pretty simple: [attribution instance in here](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-plugin-webbridge/src/main/java/com/adjust/sdk/webbridge/AdjustBridgeUtil.java#L117) is `null` and [catch we have](https://github.com/adjust/android_sdk/blob/master/Adjust/sdk-plugin-webbridge/src/main/java/com/adjust/sdk/webbridge/AdjustBridgeUtil.java#L132) is not capturing that NPE. Changing this should help with eliminating crashes, but I'm still puzzled with what might be causing this piece of code to be executed at all based on your app setup you described above. 🤔

Are you loading some remote web page in your web view or is it some local resource? Do you have access to source code of that web app to maybe double check if that web app is making a call to any of the Adjust Javascript API?

**Comment by G00fY2** [comment]
We only load remote websites. Pretty basic stuff. But I can double check if there is some hidden Adjust Javascript API usage outside of the app project that I am currently not aware of.

**Comment by uerceg** [comment]
It'd be great if you can check that. Thanks in advance. 👍

**Comment by JohannesPtaszyk** [comment]
Hey @uerceg small addition from my side: 

We are actually using `Adjust.getAttribution()` from our Website, since we could not otherwise get correct overall data.
I am currently talking to our Web-Team, so they remove that call for now and re-add it, once we could rollout a version with your fix.

Thank you for your help already! :)

**Comment by uerceg** [comment]
Hey @JohannesPtaszyk,

No problem and thanks for the follow up - at least now we know where is the call originating from. :)

In theory you don't really need to remove it. Here's a quick theory behind concept of getting `adid` with our SDK and you can in theory implement that change in your web app which would be semantically the right one and would not be affected by the fix we plan to release.

First thing which Adjust SDK does upon launch ever is attempt to track `session` package where we pretty much record an install coming in from some of your users. As soon as our backend gets this request and records a session, it creates internal mapping for that user in form of `adid` (stands for Adjust identifier) and returns that information back to SDK in response to that initial `session` package. So in theory, moment in which SDK successfully tracks first session ever is actually the moment in which SDK is first becoming aware of `adid` value. If you try to call `adid` getter before that, it's gonna cause `null` to be returned (and as we saw, these NPEs in case of Android web bridge). But this moment I mentioned (moment in which first session gets successfully tracked) is actually a moment you can hook into with defining [session tracking success callback](https://help.adjust.com/en/article/event-and-session-callbacks-android-sdk) on your own on `AdjustConfig` instance. In moment you see that callback get triggered for the first time ever (`adid` is actually one of the things being delivered as information inside of that callback), you can be assured that as long as app lives and internal data doesn't get wiped out, `adid` getter should start to return actual value to you and not `null`.

Not sure if you are doing SDK initialization from web app at all (to even have a chance to define these callbacks there), but in case you are, then maybe making changes with above mentioned things in mind would probably be the best way to go. But if you're not initializing SDK in web app, but instead you're just using this getter call for sake of Adobe, then your suggestion is way to go.

**Comment by JohannesPtaszyk** [comment]
I think we do not initialize the SDK from the web. 
So for now we disabled the tracking, which caused the NPE. 

Thrilled to get an update one the bug is fixed from your side! 
Thank you for the incredibly great responsiveness :)

**Comment by uerceg** [comment]
Hey guys,

Sorry for delay in announcing it in this issue, but since [last SDK update](https://github.com/adjust/android_sdk/releases/tag/v4.33.0), we have added fix for this and hopefully, you should not be facing this issue anymore.

Give it a shot and in case issue is still there or you have any additional questions, feel free to comment / reopen.

Cheers and thank you one more time for reporting this!

**Comment by G00fY2** [comment]
No worries, we already checked the changelog and updated to this version last week. But thanks again for the fix and the additional hint.
