### ISSUE TITLE
Error: getSamsungInstallReferrerDetails and getXiaomiInstallReferrerDetails

### ISSUE THREAD

**Issue by milly-citygo** [adjust/android_sdk#558]
Hi,
I had some weird errors that seems to suggest that I need to add some specific implementations for samsung and xiaomi
<img width="1363" alt="Screenshot 2022-10-20 at 18 16 19" src="https://user-images.githubusercontent.com/108729990/198075068-44ef3cda-c5a9-4ed1-8b63-37c533e727f3.png">
but after I add the specific implementation following those instuctions [here](https://help.adjust.com/fr/article/xiaomi-referrer-plugin), I still have unknown errors
<img width="1366" alt="Screenshot 2022-10-20 at 18 11 30" src="https://user-images.githubusercontent.com/108729990/198075194-1aee3c9d-01ba-4ac7-8511-b44c694a0f9f.png">
But the sdk seems to work since there is “session tracked” in the log. I also tested on a samsung and a xiaomi, I have the same result.

I would like to know if even with those errors the sdk can work properly. If it doesn't how can I fix them?

**Comment by uerceg** [comment]
Hey @milly-citygo,

In case you are not using Xiaomi and Samsung plugins, feel free to ignore these messages completely. SDK works perfectly fine even though you're seeing these lines. It was rather misfortunate log level pick on our end to print them out. In next SDK update, we'll change this not to have them being printed as errors, but something of lower severity (internally we are already working on this).

Thank you for pointing this out. In case you have any other questions / concerns, feel free to comment / reopen.
