### ISSUE TITLE
Unable to get any Device IDs. Please check if Proguard is correctly set with Adjust SDK

### ISSUE THREAD

**Issue by abdulkadirgun** [adjust/android_sdk#564]
![Screen Shot 2022-12-09 at 10 45 53](https://user-images.githubusercontent.com/88149786/206651274-fbfa0ff0-283d-432f-9b05-ee958bbfcf16.png)

Even though I add these rules, I get this error. Can you help me?

```
#for adjust
-keep class com.adjust.sdk.** { *; }
-keep class com.google.android.gms.common.ConnectionResult {
    int SUCCESS;
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient {
    com.google.android.gms.ads.identifier.AdvertisingIdClient$Info getAdvertisingIdInfo(android.content.Context);
}
-keep class com.google.android.gms.ads.identifier.AdvertisingIdClient$Info {
    java.lang.String getId();
    boolean isLimitAdTrackingEnabled();
}
-keep public class com.android.installreferrer.** { *; }
```

**Comment by uerceg** [comment]
Hi @abdulkadirgun,

Are you getting the same message if you turn off ProGuard completely?

Can you set SDK to sandbox mode and log level to verbose, install and run your app where you're gonna initialize SDK inside and send us over the verbose logs? Feel free to omit any sensitive data from the logs you don't wanna share with us.

**Comment by uerceg** [comment]
In case you're still facing this issue, feel free to comment / reopen. Cheers.
