### ISSUE TITLE
Tracked event not show Adjust console

### ISSUE THREAD

**Issue by abalta** [adjust/android_sdk#567]
Hi, I have multimodule (not only :app module) project. I initialize Adjust via app startup library. https://developer.android.com/topic/libraries/app-startup. I track an event just for click button. I don't see any records on Adjust console.

Here is my implementation:

```
class AdjustInitializer : Initializer<Unit> {

    override fun create(context: Context) {
        if (BuildConfig.BUILD_TYPE.contains("debug")) {
            Adjust.onCreate(
                AdjustConfig(
                    context,
                    AdjustToken,
                    AdjustConfig.ENVIRONMENT_SANDBOX
                ).apply {
                    setLogLevel(LogLevel.VERBOSE)
                    // Set event success tracking delegate.
                    setOnEventTrackingSucceededListener { eventSuccessResponseData ->
                        Log.d("adjust", "Event success callback called!")
                        Log.d("adjust", "Event success data: $eventSuccessResponseData")
                    }

                    // Set event failure tracking delegate.
                    setOnEventTrackingFailedListener { eventFailureResponseData ->
                        Log.d("adjust", "Event failure callback called!")
                        Log.d("adjust", "Event failure data: $eventFailureResponseData")
                    }

                })
        } else {
            Adjust.onCreate(
                AdjustConfig(
                    context,
                    AdjustToken,
                    AdjustConfig.ENVIRONMENT_PRODUCTION
                )
            )
        }
        return
    }

    override fun dependencies(): List<Class<out Initializer<*>>> {
        return mutableListOf()
    }
}

```
Here is my Adjust logs:

SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
SANDBOX: Adjust is running in Sandbox mode. Use this setting for testing. Don't forget to set the environment to `production` before publishing!
Attribution file not found
Read Activity state: ec:4 sc:1 ssc:1 sl:0.1 ts:0.1 la:11:12:13 uuid:4cd7a9f0-0547-40c5-b5f5-1434794d40f0
Session Callback parameters file not found
Session Partner parameters file not found
adjust_config.properties file not found in this app
Google Play Services Advertising ID read correctly at start time
Foreground timer configured to fire after 60.0 seconds of starting and cycles every 60.0 seconds
Read Package queue: [session, event't2bgyj', event't2bgyj', event't2bgyj', event't2bgyj']
Package handler read 5 packages
Added package 6 (event't2bgyj')
Wrote Activity state: ec:5 sc:1 ssc:1 sl:0.1 ts:0.1 la:11:12:13 uuid:4cd7a9f0-0547-40c5-b5f5-1434794d40f0
Path:      /event
ClientSdk: android4.33.0
Parameters:
	android_uuid     4cd7a9f0-0547-40c5-b5f5-1434794d40f0
	api_level        33
	app_token        {{xxxx}}
	app_version      1.0.0
	attribution_deeplink 1
	connectivity_type 1
	country          TR
	cpu_type         arm64-v8a
	created_at       2023-01-11T17:05:34.688Z+0300
	device_manufacturer Google
	device_name      Pixel 7 Pro
	device_type      phone
	display_height   2906
	display_width    1440
	environment      sandbox
	event_buffering_enabled 0
	event_count      5
	event_token      t2bgyj
	gps_adid         30895259-60f5-4f8e-bdfa-a4cc8edcc95b
	gps_adid_attempt 1
	gps_adid_src     service
	hardware_name    TQ1A.221205.011
	language         tr
	mcc              286
	mnc              03
	needs_response_details 1
	os_build         TQ1A.221205.011
	os_name          android
	os_version       13
	package_name     {{com.example.blabla}}
	screen_density   high
	screen_format    long
	screen_size      normal
	session_count    1
	session_length   0
	subsession_count 1
	time_spent       0
	tracking_enabled 1
	ui_mode          1
Wrote Package queue: [session, event't2bgyj', event't2bgyj', event't2bgyj', event't2bgyj', event't2bgyj']
Package handler wrote 6 packages
Package handler is paused

**Comment by uerceg** [comment]
Hi @abalta,

Thank you for detailed explanation and logs. Did you implement [this part](https://help.adjust.com/en/article/get-started-android-sdk#session-tracking) in your app when setting up the Adjust SDK?

**Comment by abalta** [comment]
Thank you, @uerceg that part fixed my issue.
