### ISSUE TITLE
ANR caused by adjust_sdk

### ISSUE THREAD

**Issue by kkkVain** [adjust/android_sdk#571]
sdk version: 4.24.1
android.os.BinderProxy.transactNative BinderProxy.java:-2
android.os.BinderProxy.transact BinderProxy.java:629
com.google.android.a.a.a a.java:4
com.google.android.finsky.externalreferrer.IGetInstallReferrerService$Stub$Proxy.a IGetInstallReferrerService.java:4
com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer InstallReferrerClientImpl.java:8
java.lang.reflect.Method.invoke Method.java:-2
com.adjust.sdk.Reflection.invokeMethod Reflection.java:125
com.adjust.sdk.Reflection.invokeInstanceMethod Reflection.java:114
com.adjust.sdk.InstallReferrer.getInstallReferrer InstallReferrer.java:401
com.adjust.sdk.InstallReferrer.onInstallReferrerSetupFinishedInt InstallReferrer.java:322
com.adjust.sdk.InstallReferrer.invoke InstallReferrer.java:301
java.lang.reflect.Proxy.invoke Proxy.java:1006
$Proxy4.onInstallReferrerSetupFinished $Proxy4.java:-1
com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected InstallReferrerClientImpl.java:5
android.app.LoadedApk$ServiceDispatcher.doConnected LoadedApk.java:2114
android.app.LoadedApk$ServiceDispatcher$RunConnection.run LoadedApk.java:2147
android.os.Handler.handleCallback Handler.java:938
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loopOnce Looper.java:210
android.os.Looper.loop Looper.java:299
android.app.ActivityThread.main ActivityThread.java:8280
java.lang.reflect.Method.invoke Method.java:-2
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:576
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1073

Is there any solution?

Thanks.

**Comment by shashanksu** [comment]
Hi @kkkVain ,
Sorry for the late attention here.  Do you still get this ANR?  As per stack trace this seems happening while invoking Google Install Referrer API.  Which version of [Install Referrer Library](https://developer.android.com/google/play/installreferrer/library) are you using?  
Thanks

**Comment by shashanksu** [comment]
Hi @kkkVain,
Closing this one as there no further updates.  In case you still still see this error, please get back. 
Thanks
