### ISSUE TITLE
Update the 'Get started with the Android SDK' documentation

### ISSUE THREAD

**Issue by PhilippNowak96** [adjust/android_sdk#575]
Hey guys,

I have 2 small suggestions for the getting started android documentation of your SDK:

1. It would be nice to also have Kotlin code snippets in the documentation. Although the snippets are very small it's much nicer to see Kotlin code snippets as an Android developer in addition to Java ones.
2. `[Step four: set up Proguard](https://help.adjust.com/en/article/get-started-android-sdk#set-up-proguard)` seems to be unnecessary since you already ship the proguard rules as part of the SDK ([see here](https://github.com/adjust/android_sdk/blob/8c377a81ea84c0e1d5360b22d6abc73f6e196305/Adjust/sdk-core/build.gradle#L11C13-L11C13)) which is the preferred way. So in my opinion it would be enough to mention that proguard rules are already included and developers don't need to care about them for the Adjust SDK.

**Comment by shashanksu** [comment]
Hi @PhilippNowak96 
Thanks for your inputs.  
1. We already have [Kotlin example app](https://github.com/adjust/android_sdk/tree/master/Adjust/example-app-kotlin), but having Kotlin code snippet makes sense.
2. Earlier versions of SDK don't have proguard rules bundled.  But as usage of older versions phases out, sure we can remove those unnecessary steps. 

Closing this issue.  Once again thanks for your valuable suggestions 🍺
