### ISSUE TITLE
`AdjustEvent` properties not public anymore

### ISSUE THREAD

**Issue by svenjacobs** [adjust/android_sdk#583]
Trying to upgrade from `4.35.0` to `4.35.1`, a unit tests starts failing because `AdjustEvent.eventToken` is now `package` protected instead of `public`. Looking at the [source code](https://github.com/adjust/android_sdk/blob/88f938f4c53800a1397ee413d2ac1be51ac6d680/Adjust/sdk-core/src/main/java/com/adjust/sdk/AdjustEvent.java#L10) it seems the properties never were `public` but maybe the class was modified on bytecode-level by the build process?

Was this change intentional? A patch-level update should _imho_ not change the public facing API.

**Comment by shashanksu** [comment]
hello @svenjacobs 

Thanks for reporting this & sorry for all the inconvenience caused.  But indeed our intention was always to have `AdjustEvent.eventToken` as `package` protected.  Unfortunately it was not reflected in the compiled binaries till `4.35.0` despite having it in the [source code](https://github.com/adjust/android_sdk/blob/88f938f4c53800a1397ee413d2ac1be51ac6d680/Adjust/sdk-core/src/main/java/com/adjust/sdk/AdjustEvent.java#L10) like you mentioned.  Apparently with the latest JDK version, this seems fixed.  

Please let us know in case there are more concerns.  

Thank you.

**Comment by svenjacobs** [comment]
Hello @shashanksu,

thanks for the explanation. As mentioned, this change breaks a unit test for us. We have a lightweight wrapper around Adjust and we would like to test if the wrapper sets the correct event properties. Would it be possible for you to add getters for these properties, please?

**Comment by shashanksu** [comment]
Hey @svenjacobs 

Just to share you some good news!  We have now added the getters in the latest [version 4.36.0](https://github.com/adjust/android_sdk/releases/tag/v4.36.0)
Hope this resolves your issue.  Please let us know.

Thank you.

**Comment by svenjacobs** [comment]
Thank you very much 👍🏼
