### ISSUE TITLE
Why can't i download SDK for java codes?

### ISSUE THREAD

**Issue by EysaDun** [adjust/android_sdk#587]
I'm not found git clone link.

**Comment by uerceg** [comment]
Hi @EysaDun,

You can download the ZIP archive of the entire repository (source code included) like this:

<img width="916" alt="Screenshot 2023-12-14 at 10 38 23" src="https://github.com/adjust/android_sdk/assets/1741635/ac91205e-7b50-46a5-adf4-7ad8c5454a6b">

In case you have any further questions, feel free to comment / reopen.

Cheers
