### ISSUE TITLE
Hi, Team. I have a question here about config for tracking.

### ISSUE THREAD

**Issue by EysaDun** [adjust/android_sdk#589]
I was download and view the source code of [example-app-java], but i cannot find which method will effects install and open count statistics of our app.
Maybe it should in 2 java files:
GlobalApplication.java
MainActivity.java
Demo includes many configuration method, I want to know the one for sure. Or, it don't need config anything.
Thanks for your replay.

**Comment by shashanksu** [comment]
Hi @EysaDun,
Please get in touch with the Adjust Support team to know all the configs you need for your account.
Hope this helps.  Closing this one.
Thanks
