### ISSUE TITLE
Backward compatability of android_sdk

### ISSUE THREAD

**Issue by sheetalj2205** [adjust/android_sdk#602]
What is the min. a version of the android app is required if I wanna use the 4.38.4 version of Adjust SDK.
cc: @shashanksu

**Comment by shashanksu** [comment]
Hi @sheetalj2205,
For main SDK version 4.38.4, the minimum Android API supported is [9](https://github.com/adjust/android_sdk/blob/b322fd4a0fe30995b6f28a3c57e8d752b763398f/Adjust/build.gradle#L9).

Hope this answers your question!  Feel free to reopen it otherwise, thanks.
