### ISSUE TITLE
Migration guide doesn't mention that `setAppSecret()` has been removed completely

### ISSUE THREAD

**Issue by nisrulz** [adjust/android_sdk#610]
... and is not needed anymore.

<img width="946" alt="Screenshot 2024-08-09 at 12 16 58" src="https://github.com/user-attachments/assets/83349222-56d1-40a0-98ce-64fa4e413f50">

---

I was able to find the commit in the codebase here, that [it was removed](https://github.com/adjust/android_sdk/commit/8dc8a184cbc5c8634107b4113843dac855651c06). 

- [Migration Guide](https://dev.adjust.com/en/sdk/android/migration/v4-to-v5)
- [Example App from this repo](https://github.com/adjust/android_sdk/blob/master/Adjust/examples/example-app-kotlin/src/main/java/com/adjust/examples/GlobalApplication.kt#L13-L18) doesn't use it either. 

So the understanding is that this is not needed at all.

> Side note: Seems like this is also true for [iOS SDK repo](https://github.com/adjust/ios_sdk/commit/655de53b1f49ad9012ac4331a5b98fd73063c3dc)

**Comment by shashanksu** [comment]
Hi @nisrulz 
Your observation is correct, `adjustConfig.setAppSecret` is no more required and therefore completely removed in v5.
Thanks for reporting, we will update our documentation. 

Hope this helps.  I am closing the issue, please feel free to get back in case any more queries. 
Thank you.

**Comment by L-Andrade** [comment]
@shashanksu The migration guide still does not specify this information. Can you please add it?
