### ISSUE TITLE
setOnDeferredDeeplinkResponseListener can't receive callbackk

### ISSUE THREAD

**Issue by prookiee** [adjust/android_sdk#612]
SDK version 5.0
Deeplink work's fine.
But when I test Deferred deeplink, it doesn't word, I can't get any callback from setOnDeferredDeeplinkResponseListener .

I removed APP from device and forgot device from adjust console ,but deferred deeplink still doesn't work.

**Comment by uerceg** [comment]
Hi @prookiee,

Steps you said you did sound good. However there are still some steps down the road:

- How does your test URL look like? Does it contain `deep_link` parameter inside of it?
- Have you enabled probabilistic matching for the clicks on the link that you are testing?

When you run this test, test install that you track should be attributed to click on your test URL. When SDK's attribution callback is being triggered, do you see that attribution data from there (tracker token, tracker name at least) belong to things from your URL?

**Comment by prookiee** [comment]
Hello @uerceg ,
Thank you for your reply !

This is my deeplink:
https://myapp.go.link?deep_link=myapp&adj_t=1fwu6wmd&adj_campaign=adtest&adj_label=aff_code&adj_engagement_type=fallback_click&adj_fallback=https%3A%2F%2Fmyapp.com&adj_redirect_macos=https%3A%2F%2Fmyapp.com

I have turned on the probabilistic matching.

Here is my attribution information

![2D090C8A-8C58-41CC-B566-17C7A24E8356](https://github.com/user-attachments/assets/d5b7da93-9afa-4eb7-8a73-015e03021465)

**Comment by prookiee** [comment]
Hello @uerceg ,
Thank you for your reply !

This is my deeplink:
https://myapp.go.link?deep_link=myapp&adj_t=1fwu6wmd&adj_campaign=adtest&adj_label=aff_code&adj_engagement_type=fallback_click&adj_fallback=https%3A%2F%2Fmyapp.com&adj_redirect_macos=https%3A%2F%2Fmyapp.com

I have turned on the probabilistic matching.

It looks like the click event is not attributed to my link

![image](https://github.com/user-attachments/assets/01ccec4c-09e6-4afd-b55b-ec6f5f1f8e11)

**Comment by uerceg** [comment]
Yeah, it's ending up being organic (meaning the install you're making is not getting attributed to your click). At this point, I am not sure why, client support teams who are able to debug this are not the ones who are replying in GitHub issues.

Only thing that comes to my mind which you can maybe try is to check SDK verbose logs, see what's your test device Google Advertising ID (called `gps_adid` in the logs that our SDK prints) and then just append it to the test URL (&gps_adid=XXXXXX). This should trigger device ID matching on our end and if everything else during the test has been done correctly, hopefully install should get attributed to the click you make on that URL.

**Comment by prookiee** [comment]
Yeah, thank you for your help.  I hava solved this problem by replacing the branded domain xxx.go.link with app.adjust.com.
And now I can recieve deferred deeplink information normaly.

Thank you for your help.

**Comment by prookiee** [comment]
This is my testing link, hoping to help people who encounter similar problems.

https://app.adjust.com/<your link identification code>?deep_link=<your scheme>%3A%2F%2F<your host>xxx

**Comment by prookiee** [comment]
![image](https://github.com/user-attachments/assets/4918024a-def9-4c90-a035-0ce978e4ab99)
