### ISSUE TITLE
[type] Wrong LogValue.

### ISSUE THREAD

**Issue by holndal** [adjust/android_sdk#613]
https://dev.adjust.com/en/sdk/android/configuration/?version=v5

`LogLevel.SUPPRESS` doesn't exist.

This repository supports `LogLevel.SUPRESS`.

https://github.com/adjust/android_sdk/blob/2fa1a0a4fcaf6adbe045faa9822f0bb46bbf911e/Adjust/sdk-core/src/main/java/com/adjust/sdk/LogLevel.java#L9

I think it should be fixed. Thanks.

**Comment by uerceg** [comment]
Hey @holndal,

Thanks for the report and good catch. We have just shipped v5.0.1 with the fix.

I'll close this issue, but in case you still notice that something's not right, feel free to comment / reopen.

Thank you one more time.

Cheers.
