### ISSUE TITLE
Update Android Studio documentation?

### ISSUE THREAD

**Issue by srini91** [adjust/android_sdk#77]
We use Android Studio to build apps and the documentation to install Adjust SDK is out of date:
https://github.com/adjust/android_sdk/blob/master/doc/android_studio.md

The Google issue is fixed.

A couple of issues:

1) Can you guys update these docs to remove the workaround?  I believe more recent versions of Android Studio allow for importing modules.

2) Is there a way to use Adjust through the Maven central repository, so that installation is just one line in build.gradle?

**Comment by StephenMilone** [comment]
It is appears maven repo is a version behind?  I'm only seeing 3.6.1  please advise.

**Comment by nonelse** [comment]
Thanks for the input.The new version for the adjust SDK uses Android Studio by default and it's on Maven Repository.
Feel free to open a new issue for the new version.
