### ISSUE TITLE
Use of Activity Context - Potential Memory Leak

### ISSUE THREAD

**Issue by PhatJo** [adjust/android_sdk#84]
I notice that the Adjust constructor takes an Activity context, and passes it to an ActivityHandler that extracts the Application’s context:

```java
this.
 context=
 context.getApplicationContext();
```

In my analysis, I find this to be keeping many other objects throughout our app from being released, leading to OutOfMemoryError exceptions and thus crashes. Can this be reworked so it uses the main Application Context directly?

Please find the screenshot of a sample MemoryAnalyzer row. 

![screen shot 2014-11-21 at 5 04 00 pm](https://cloud.githubusercontent.com/assets/1447912/5152171/790d1968-71a0-11e4-951f-be327c749fa6.png)

**Comment by hpadrao** [comment]
Do you have any plans to fix it?

**Comment by samdozor** [comment]
Although I'm not sure how a memory leak would be caused if they're just calling `getApplicationContext()` immediately, this appears to be fixed/changed as of v3.6.1: https://github.com/adjust/android_sdk/releases/tag/v3.6.1

**Comment by hpadrao** [comment]
@samdozor Perfect, thank you very much. 
I'm gonna implement Adjust and was taking a look if there was something weird before.

**Comment by wellle** [comment]
Oh you're right, we already fixed that a month ago with https://github.com/adjust/android_sdk/commit/c39c04a. Thanks :+1:
