### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by WarrenFaith** [adjust/android_sdk#86]
I have added Adjust as a subtree using the latest commit on master (because of the missing imports on tag v3.6.1).

I am unable to run my app as soon as I add Adjust to my project gradle. I only get the following output in the gradle console. Always right after `:subtrees:Adjust:Adjust:jar`

    Error:Cannot convert the provided notation to a File or URI: [src].
    The following types/formats are supported:
      - A String or CharSequence path, e.g 'src/main/java' or '/usr/include'
      - A String or CharSequence URI, e.g 'file:/usr/include'
      - A File instance.
      - A URI or URL instance.

Any clue what might cause this?

**Comment by nonelse** [comment]
@WarrenFaith, have you tried the new adjust android sdk v4? 
It should solve this issue, but feel free to open a new one if it persists or you find something new.
Thanks!

**Comment by eliecerg** [comment]
[Uber-2023-Environmental-Social-and-Governance-Report.pdf](https://github.com/adjust/android_sdk/files/15291474/Uber-2023-Environmental-Social-and-Governance-Report.pdf)
