### ISSUE TITLE
Set environment in code

### ISSUE THREAD

**Issue by maedchenflohmarkt** [adjust/android_sdk#88]
Currently environment is set via meta-data which is defined at compile time. If we could set environment in code it would be easy to just switch environments based on `BuildConfig.DEBUG`.

The current method introduces a possible point of error when creating a deployable apk since the developer has to remember to switch to production.

**Comment by samdozor** [comment]
I wonder if the Adjust team would recommend against just using the `appDidLaunch` method to instantiate the SDK:
https://github.com/adjust/android_sdk/blob/master/Adjust/src/com/adjust/sdk/Adjust.java#L156

**Comment by maedchenflohmarkt** [comment]
Thanks for your help. We are now using Adjust.appDidLaunch in OnCreate of the Application.

```java
Adjust.appDidLaunch(
    getApplicationContext(),
    getResources().getString(R.string.adjust_app_token),
    BuildConfig.DEBUG ? "sandbox" : "production",
    "info",
    true
);
```

Our current SDK version is 3.6.1 since this is the latest one on maven central. I hope adjust will upload 3.6.2 soon and for all future versions. v4 does not seem to be ready for production yet.

**Comment by wellle** [comment]
Yes the environment will be set in code in version 4.

**Comment by shercoder** [comment]
If you're using Gradle then you can use something like this in your `build.gradle`

```
buildTypes {
        release {
            buildConfigField "String", "ADJUST_ENVIRONMENT", "com.adjust.sdk.AdjustConfig.ENVIRONMENT_PRODUCTION"
        }
        debug {
            buildConfigField "String", "ADJUST_ENVIRONMENT", "com.adjust.sdk.AdjustConfig.ENVIRONMENT_SANDBOX"
        }
    }
```

and then just use when configuring Adjust: `BuildConfig.ADJUST_ENVIRONMENT`

**Comment by wellle** [comment]
Since [version 4] you can set the environment programmatically. Check the Readme for details.
