### ISSUE TITLE
Delegate Callbacks in SDK

### ISSUE THREAD

**Issue by kfayzullin** [adjust/android_sdk#92]
We are missing the ability to receive callbacks client-side on 
- session
- install and 
- reattribution events

in the SDK version 4.x.

We need these to be able to sync adjust.io with other tracking tools client-side. 

We need the same information as the one which was available in SDK version 3.x, i.e.:

    - AIActivityKind activityKind indicates what kind of activity was tracked. It has one of these values:
         (AIActivityKindSession, AIActivityKindEvent, AIActivityKindRevenue, AIActivityKindReattribution)
    - NSString trackerToken the tracker token of the current install.
    - NSString trackerName the tracker name of the current install.
    - NSString network the network grouping level of the current install.
    - NSString campaign the campaign grouping level of the current install.
    - NSString adgroup the ad group grouping level of the current install.
    - NSString creative the creative grouping level of the current install.

**Comment by wellle** [comment]
@kfayzullin: Thanks for the input. If any of the tracker related values changes, the `onAttributionChanged` function will be called. So currently you only miss when activities are tracked.

Could you expand on what you want to use it for? Then we might consider adding a second callback function for when an activity was tracked. But we tried to simplify the current callback by only calling it when the attribution actually changes.

**Comment by kfayzullin** [comment]
We are using these callbacks currently for synchronizing adjust.io session tracking with one other tracking/analytics tool. So we get informed about the new session start getting adjust.io callback and forward this information directly to our another tracking tool. This helps to keep all data in sync between the tools.

**Comment by wellle** [comment]
@kfayzullin: I see. Usually we take care of that kind of synchronization via server to server callbacks. Please contact support@adjust.com and tell them about your use case. You should not need to synchronize SDK to SDK.

**Comment by kfayzullin** [comment]
@wellle: Unfortunately, we cannot sync server side, since in this case we won't get user IDs matched. I already talked to Paul Müller. He told me to post it here to be addressed in the next SDK release.

**Comment by wellle** [comment]
Alright, we will consider adding a second callback for SDK version 4.1 that gets executed every time an install, session, reattribution or event got successfully tracked.

**Comment by uerceg** [comment]
Added to latest `4.6.0` release: https://github.com/adjust/android_sdk/releases/tag/v4.6.0
