### ISSUE TITLE
Please consider adding an option to disable ANDROID_ID collection

### ISSUE THREAD

**Issue by docgravel** [adjust/android_sdk#95]
Some security-conscious organizations don't want to ship any libraries that collect ANDROID_ID because its sensitive information.  Those organizations are left with the choice of either forking your library and maintaining a fork with the ANDROID_ID collection turned off or using a competitor.  We would rather not use a fork which will quickly get out of date.  Please consider adding an API like AdjustConfig.setCollectAndroidId(false) that we can call during initialization so we don't have to maintain a fork.

Or if we submitted a pull request with such a feature, would you potentially merge it?

**Comment by nonelse** [comment]
Hi. We have an option to remove the source files that access Android Id and Mac Address. The documentation was removed for v4, but it's back online at: https://github.com/adjust/android_sdk/blob/master/doc/gps_adid.md

You're suggestion it's still good, and we will consider adding it as a soft version that persists after updates.

Thanks for the feedback :)

**Comment by docgravel** [comment]
Ok, thanks for responding.  We will consider that route, but would prefer not to fork.  Maybe we can add a step to our proguarding to remove those classes but still allow us to use the pure library from maven.
