### ISSUE TITLE
Tracking revenue

### ISSUE THREAD

**Issue by hameno** [adjust/android_sdk#97]
Hello,
we are implementing a general app framework and provide several tracking services the user can enable. Inside the framework we have a kiosk system where the user can buy content. We need to be able to track this using different services. One of this tracking service is adjust. While we can track revenues with adjust, we only get the revenue in the users currency. We have no idea what currency is setup in the adjust dashboard. 

In the documentation you state the following:
>  Please note that while the currency token must be set, adjust will not perform a currency conversion.   You should always transmit revenues in the currency that you have set in your adjust dashboard.

This is utter bullshit and basicly prevents any correct usage of your service, as the real revenue will always be wrong if you don't manually hardcode the prices. 

Is there something we are missing?

**Comment by wellle** [comment]
As per the documentation, the revenue tracking can be used correctly as long as you manage to send the proper currency.

We are currently working on that server side currency conversion. Once that's live you can send revenue in any currency and it will be converted on the fly and shown in the dashboard in the currency that you have set up. I will let you know when currency conversion is live.

**Comment by hameno** [comment]
Any idea when that might happen?

**Comment by wellle** [comment]
We're aiming for within the next few weeks.

**Comment by hameno** [comment]
Okay, thanks.

**Comment by scompt** [comment]
I'm still confused by the documentation and your comments above. If my dashboard is in EUR and I track 10 USD, will the correct thing happen right now or do I have to wait the couple weeks until the server-side currency conversion is implemented? 

If I have to wait a couple weeks, what's the behavior in the meantime? Will 10 EUR be tracked even if I send 10 USD?

**Comment by wellle** [comment]
> will the correct thing happen right now

No.

> do I have to wait the couple weeks until the server-side currency conversion is implemented?

Yes.

> Will 10 EUR be tracked even if I send 10 USD?

Yes.

**Comment by scompt** [comment]
Thanks for the clarification.

**Comment by wellle** [comment]
@hameno @scompt: Currency conversion is live!
https://www.adjust.com/overview/features/2015/04/29/currency-conversion-live/

**Comment by hameno** [comment]
Great timing, we just released the app :)
