### ISSUE TITLE
Using Adjust new SDK in Eclipse IDE

### ISSUE THREAD

**Issue by Raheel-Adnan** [adjust/android_sdk#98]
We are working on our Android product and which has not been upgraded to Android Studio yet. Can you please tell me how to use your updated SDK into eclipse project? 
Currently we are using old SDK.

Thanks,

**Comment by Raheel-Adnan** [comment]
We are migrating our project after all. No need to address this issue.

Thanks,

**Comment by wellle** [comment]
Good choice!

For the record: https://github.com/adjust/android_sdk/blob/master/doc/eclipse.md

**Comment by Raheel-Adnan** [comment]
Thanks wellle
